--------------------------------------------------------------------------------
-- COMPRAS_PAGOS (pagina APEX 77) — paquete CRUD + endpoints ORDS.
-- Ejecutar completo como el esquema JOSEGALVEZ. Requiere PKG_AUTH_LUBRIMEC.
--
-- PK id_pago GENERATED BY DEFAULT AS IDENTITY (no se pasa en el INSERT).
-- Multiempresa (cod_empresa). nro_recibo lo ingresa el usuario (NOT NULL).
-- FK id_factura -> compras_cabecera, id_forma -> forma_cobro_pago.
-- LISTAR/OBTENER hacen JOIN para traer descripcion_forma + datos de la factura
-- (nro_comprobante, proveedor) como campos de solo lectura.
-- BUSCAR_COMPRAS alimenta el selector de factura (endpoint compras/buscar).
-- Las formas de pago se listan aparte con formas-cobro-pago (son pocas -> select).
--
-- === 1) PAQUETE PKG_COMPRAS_PAGOS_LUBRIMEC =================================
--------------------------------------------------------------------------------

CREATE OR REPLACE PACKAGE PKG_COMPRAS_PAGOS_LUBRIMEC AS

  PROCEDURE LISTAR(p_token IN VARCHAR2, p_cod_empresa IN NUMBER);
  PROCEDURE OBTENER(p_token IN VARCHAR2, p_id IN NUMBER, p_cod_empresa IN NUMBER);
  PROCEDURE INSERTAR(
      p_token IN VARCHAR2, p_fecha IN VARCHAR2, p_id_factura IN NUMBER,
      p_id_forma IN NUMBER, p_monto IN NUMBER, p_observacion IN VARCHAR2,
      p_nro_recibo IN NUMBER, p_cod_empresa IN NUMBER);
  PROCEDURE ACTUALIZAR(
      p_token IN VARCHAR2, p_id IN NUMBER, p_fecha IN VARCHAR2, p_id_factura IN NUMBER,
      p_id_forma IN NUMBER, p_monto IN NUMBER, p_observacion IN VARCHAR2,
      p_nro_recibo IN NUMBER, p_cod_empresa IN NUMBER);
  PROCEDURE ELIMINAR(p_token IN VARCHAR2, p_id IN NUMBER, p_cod_empresa IN NUMBER);
  PROCEDURE BUSCAR_COMPRAS(p_token IN VARCHAR2, p_cod_empresa IN NUMBER, p_q IN VARCHAR2);

END PKG_COMPRAS_PAGOS_LUBRIMEC;
/

CREATE OR REPLACE PACKAGE BODY PKG_COMPRAS_PAGOS_LUBRIMEC AS

  PROCEDURE p_error(p_status IN NUMBER, p_reason IN VARCHAR2, p_message IN VARCHAR2) IS
  BEGIN
    OWA_UTIL.STATUS_LINE(p_status, p_reason, FALSE);
    APEX_JSON.OPEN_OBJECT;
    APEX_JSON.WRITE('success', FALSE);
    APEX_JSON.WRITE('message', p_message);
    APEX_JSON.CLOSE_OBJECT;
  END p_error;

  FUNCTION f_usuario(p_token IN VARCHAR2) RETURN VARCHAR2 IS
  BEGIN
    RETURN PKG_AUTH_LUBRIMEC.VALIDAR_TOKEN(p_token);
  END f_usuario;

  --------------------------------------------------------------------------
  -- LISTAR (JOIN a forma_cobro_pago, compras_cabecera y personas)
  --------------------------------------------------------------------------
  PROCEDURE LISTAR(p_token IN VARCHAR2, p_cod_empresa IN NUMBER) IS
    l_usuario VARCHAR2(255);
  BEGIN
    l_usuario := f_usuario(p_token);
    IF l_usuario IS NULL THEN
      p_error(401, 'Unauthorized', 'Token invalido o expirado');
      RETURN;
    END IF;

    APEX_JSON.OPEN_OBJECT;
    APEX_JSON.WRITE('success', TRUE);
    APEX_JSON.OPEN_ARRAY('data');
    FOR r IN (
        SELECT pg.id_pago, pg.fecha, pg.id_factura, pg.id_forma, pg.monto,
               pg.observacion, pg.cod_empresa, pg.nro_recibo,
               f.descripcion AS descripcion_forma,
               cc.nro_comprobante, cc.ser_timbrado, cc.tip_comprobante,
               NVL(pe.nombre_fantasia, pe.nombre) AS nombre_proveedor
          FROM compras_pagos pg
          LEFT JOIN forma_cobro_pago f
                 ON f.id_forma = pg.id_forma
          LEFT JOIN compras_cabecera cc
                 ON cc.id_factura = pg.id_factura
          LEFT JOIN personas pe
                 ON pe.cod_persona = cc.cod_persona
                AND pe.cod_empresa = cc.cod_empresa
         WHERE pg.cod_empresa = p_cod_empresa
         ORDER BY pg.id_pago DESC
    ) LOOP
      APEX_JSON.OPEN_OBJECT;
      APEX_JSON.WRITE('id_pago', r.id_pago);
      APEX_JSON.WRITE('fecha', TO_CHAR(r.fecha, 'YYYY-MM-DD'));
      APEX_JSON.WRITE('id_factura', r.id_factura);
      APEX_JSON.WRITE('id_forma', r.id_forma);
      APEX_JSON.WRITE('monto', r.monto);
      APEX_JSON.WRITE('observacion', r.observacion);
      APEX_JSON.WRITE('cod_empresa', r.cod_empresa);
      APEX_JSON.WRITE('nro_recibo', r.nro_recibo);
      APEX_JSON.WRITE('descripcion_forma', r.descripcion_forma);
      APEX_JSON.WRITE('nro_comprobante', r.nro_comprobante);
      APEX_JSON.WRITE('ser_timbrado', r.ser_timbrado);
      APEX_JSON.WRITE('tip_comprobante', r.tip_comprobante);
      APEX_JSON.WRITE('nombre_proveedor', r.nombre_proveedor);
      APEX_JSON.CLOSE_OBJECT;
    END LOOP;
    APEX_JSON.CLOSE_ARRAY;
    APEX_JSON.CLOSE_OBJECT;
  EXCEPTION
    WHEN OTHERS THEN
      p_error(500, 'Internal Server Error', 'Error: ' || SQLERRM);
  END LISTAR;

  --------------------------------------------------------------------------
  -- OBTENER
  --------------------------------------------------------------------------
  PROCEDURE OBTENER(p_token IN VARCHAR2, p_id IN NUMBER, p_cod_empresa IN NUMBER) IS
    l_usuario     VARCHAR2(255);
    l_fecha       compras_pagos.fecha%TYPE;
    l_id_factura  compras_pagos.id_factura%TYPE;
    l_id_forma    compras_pagos.id_forma%TYPE;
    l_monto       compras_pagos.monto%TYPE;
    l_observacion compras_pagos.observacion%TYPE;
    l_nro_recibo  compras_pagos.nro_recibo%TYPE;
    l_desc_forma  forma_cobro_pago.descripcion%TYPE;
    l_nro_comp    compras_cabecera.nro_comprobante%TYPE;
    l_ser         compras_cabecera.ser_timbrado%TYPE;
    l_tip         compras_cabecera.tip_comprobante%TYPE;
    l_proveedor   personas.nombre%TYPE;
  BEGIN
    l_usuario := f_usuario(p_token);
    IF l_usuario IS NULL THEN
      p_error(401, 'Unauthorized', 'Token invalido o expirado');
      RETURN;
    END IF;

    BEGIN
      SELECT pg.fecha, pg.id_factura, pg.id_forma, pg.monto, pg.observacion, pg.nro_recibo,
             f.descripcion, cc.nro_comprobante, cc.ser_timbrado, cc.tip_comprobante,
             NVL(pe.nombre_fantasia, pe.nombre)
        INTO l_fecha, l_id_factura, l_id_forma, l_monto, l_observacion, l_nro_recibo,
             l_desc_forma, l_nro_comp, l_ser, l_tip, l_proveedor
        FROM compras_pagos pg
        LEFT JOIN forma_cobro_pago f ON f.id_forma = pg.id_forma
        LEFT JOIN compras_cabecera cc ON cc.id_factura = pg.id_factura
        LEFT JOIN personas pe
               ON pe.cod_persona = cc.cod_persona
              AND pe.cod_empresa = cc.cod_empresa
       WHERE pg.id_pago = p_id AND pg.cod_empresa = p_cod_empresa;
    EXCEPTION
      WHEN NO_DATA_FOUND THEN
        p_error(404, 'Not Found', 'Pago no encontrado');
        RETURN;
    END;

    APEX_JSON.OPEN_OBJECT;
    APEX_JSON.WRITE('success', TRUE);
    APEX_JSON.OPEN_OBJECT('data');
    APEX_JSON.WRITE('id_pago', p_id);
    APEX_JSON.WRITE('fecha', TO_CHAR(l_fecha, 'YYYY-MM-DD'));
    APEX_JSON.WRITE('id_factura', l_id_factura);
    APEX_JSON.WRITE('id_forma', l_id_forma);
    APEX_JSON.WRITE('monto', l_monto);
    APEX_JSON.WRITE('observacion', l_observacion);
    APEX_JSON.WRITE('cod_empresa', p_cod_empresa);
    APEX_JSON.WRITE('nro_recibo', l_nro_recibo);
    APEX_JSON.WRITE('descripcion_forma', l_desc_forma);
    APEX_JSON.WRITE('nro_comprobante', l_nro_comp);
    APEX_JSON.WRITE('ser_timbrado', l_ser);
    APEX_JSON.WRITE('tip_comprobante', l_tip);
    APEX_JSON.WRITE('nombre_proveedor', l_proveedor);
    APEX_JSON.CLOSE_OBJECT;
    APEX_JSON.CLOSE_OBJECT;
  EXCEPTION
    WHEN OTHERS THEN
      p_error(500, 'Internal Server Error', 'Error: ' || SQLERRM);
  END OBTENER;

  --------------------------------------------------------------------------
  -- INSERTAR (PK IDENTITY; FK controladas)
  --------------------------------------------------------------------------
  PROCEDURE INSERTAR(
      p_token IN VARCHAR2, p_fecha IN VARCHAR2, p_id_factura IN NUMBER,
      p_id_forma IN NUMBER, p_monto IN NUMBER, p_observacion IN VARCHAR2,
      p_nro_recibo IN NUMBER, p_cod_empresa IN NUMBER) IS
    l_usuario VARCHAR2(255);
    l_id      compras_pagos.id_pago%TYPE;
    l_fecha   DATE := TO_DATE(p_fecha, 'YYYY-MM-DD');
  BEGIN
    l_usuario := f_usuario(p_token);
    IF l_usuario IS NULL THEN
      p_error(401, 'Unauthorized', 'Token invalido o expirado');
      RETURN;
    END IF;

    IF l_fecha IS NULL THEN
      p_error(400, 'Bad Request', 'La fecha es obligatoria'); RETURN;
    END IF;
    IF p_id_factura IS NULL THEN
      p_error(400, 'Bad Request', 'La factura es obligatoria'); RETURN;
    END IF;
    IF p_id_forma IS NULL THEN
      p_error(400, 'Bad Request', 'La forma de pago es obligatoria'); RETURN;
    END IF;
    IF p_monto IS NULL THEN
      p_error(400, 'Bad Request', 'El monto es obligatorio'); RETURN;
    END IF;
    IF p_nro_recibo IS NULL THEN
      p_error(400, 'Bad Request', 'El nro de recibo es obligatorio'); RETURN;
    END IF;
    IF p_cod_empresa IS NULL THEN
      p_error(400, 'Bad Request', 'cod_empresa es obligatorio'); RETURN;
    END IF;

    INSERT INTO compras_pagos (fecha, id_factura, id_forma, monto, observacion, cod_empresa, nro_recibo)
    VALUES (l_fecha, p_id_factura, p_id_forma, p_monto, p_observacion, p_cod_empresa, p_nro_recibo)
    RETURNING id_pago INTO l_id;
    COMMIT;

    OWA_UTIL.STATUS_LINE(201, 'Created', FALSE);
    APEX_JSON.OPEN_OBJECT;
    APEX_JSON.WRITE('success', TRUE);
    APEX_JSON.WRITE('message', 'Pago creado');
    APEX_JSON.WRITE('id_pago', l_id);
    APEX_JSON.CLOSE_OBJECT;
  EXCEPTION
    WHEN OTHERS THEN
      ROLLBACK;
      -- -2291: FK padre no existe (factura o forma inexistente)
      IF SQLCODE = -2291 THEN
        p_error(400, 'Bad Request', 'La factura o la forma de pago indicada no existe');
      ELSE
        p_error(500, 'Internal Server Error', 'Error: ' || SQLERRM);
      END IF;
  END INSERTAR;

  --------------------------------------------------------------------------
  -- ACTUALIZAR
  --------------------------------------------------------------------------
  PROCEDURE ACTUALIZAR(
      p_token IN VARCHAR2, p_id IN NUMBER, p_fecha IN VARCHAR2, p_id_factura IN NUMBER,
      p_id_forma IN NUMBER, p_monto IN NUMBER, p_observacion IN VARCHAR2,
      p_nro_recibo IN NUMBER, p_cod_empresa IN NUMBER) IS
    l_usuario VARCHAR2(255);
    l_fecha   DATE := TO_DATE(p_fecha, 'YYYY-MM-DD');
  BEGIN
    l_usuario := f_usuario(p_token);
    IF l_usuario IS NULL THEN
      p_error(401, 'Unauthorized', 'Token invalido o expirado');
      RETURN;
    END IF;

    IF l_fecha IS NULL THEN
      p_error(400, 'Bad Request', 'La fecha es obligatoria'); RETURN;
    END IF;
    IF p_id_factura IS NULL THEN
      p_error(400, 'Bad Request', 'La factura es obligatoria'); RETURN;
    END IF;
    IF p_id_forma IS NULL THEN
      p_error(400, 'Bad Request', 'La forma de pago es obligatoria'); RETURN;
    END IF;
    IF p_monto IS NULL THEN
      p_error(400, 'Bad Request', 'El monto es obligatorio'); RETURN;
    END IF;
    IF p_nro_recibo IS NULL THEN
      p_error(400, 'Bad Request', 'El nro de recibo es obligatorio'); RETURN;
    END IF;

    UPDATE compras_pagos
       SET fecha       = l_fecha,
           id_factura  = p_id_factura,
           id_forma    = p_id_forma,
           monto       = p_monto,
           observacion = p_observacion,
           nro_recibo  = p_nro_recibo
     WHERE id_pago = p_id AND cod_empresa = p_cod_empresa;

    IF SQL%ROWCOUNT = 0 THEN
      ROLLBACK;
      p_error(404, 'Not Found', 'Pago no encontrado');
      RETURN;
    END IF;
    COMMIT;

    APEX_JSON.OPEN_OBJECT;
    APEX_JSON.WRITE('success', TRUE);
    APEX_JSON.WRITE('message', 'Pago actualizado');
    APEX_JSON.CLOSE_OBJECT;
  EXCEPTION
    WHEN OTHERS THEN
      ROLLBACK;
      IF SQLCODE = -2291 THEN
        p_error(400, 'Bad Request', 'La factura o la forma de pago indicada no existe');
      ELSE
        p_error(500, 'Internal Server Error', 'Error: ' || SQLERRM);
      END IF;
  END ACTUALIZAR;

  --------------------------------------------------------------------------
  -- ELIMINAR
  --------------------------------------------------------------------------
  PROCEDURE ELIMINAR(p_token IN VARCHAR2, p_id IN NUMBER, p_cod_empresa IN NUMBER) IS
    l_usuario VARCHAR2(255);
  BEGIN
    l_usuario := f_usuario(p_token);
    IF l_usuario IS NULL THEN
      p_error(401, 'Unauthorized', 'Token invalido o expirado');
      RETURN;
    END IF;

    DELETE FROM compras_pagos
     WHERE id_pago = p_id AND cod_empresa = p_cod_empresa;

    IF SQL%ROWCOUNT = 0 THEN
      ROLLBACK;
      p_error(404, 'Not Found', 'Pago no encontrado');
      RETURN;
    END IF;
    COMMIT;

    APEX_JSON.OPEN_OBJECT;
    APEX_JSON.WRITE('success', TRUE);
    APEX_JSON.WRITE('message', 'Pago eliminado');
    APEX_JSON.CLOSE_OBJECT;
  EXCEPTION
    WHEN OTHERS THEN
      ROLLBACK;
      p_error(500, 'Internal Server Error', 'Error: ' || SQLERRM);
  END ELIMINAR;

  --------------------------------------------------------------------------
  -- BUSCAR_COMPRAS (para el selector de factura). Hasta 30 facturas de la
  -- empresa que matcheen por id_factura / nro_comprobante / ser_timbrado /
  -- nombre del proveedor. Con q vacio, las ultimas por id_factura.
  --------------------------------------------------------------------------
  PROCEDURE BUSCAR_COMPRAS(p_token IN VARCHAR2, p_cod_empresa IN NUMBER, p_q IN VARCHAR2) IS
    l_usuario VARCHAR2(255);
    l_q       VARCHAR2(400) := '%' || UPPER(TRIM(p_q)) || '%';
  BEGIN
    l_usuario := f_usuario(p_token);
    IF l_usuario IS NULL THEN
      p_error(401, 'Unauthorized', 'Token invalido o expirado');
      RETURN;
    END IF;

    APEX_JSON.OPEN_OBJECT;
    APEX_JSON.WRITE('success', TRUE);
    APEX_JSON.OPEN_ARRAY('data');
    -- Solo facturas de compra (FCR) con saldo pendiente segun pkg_compras.
    FOR r IN (
        SELECT cc.id_factura, cc.nro_comprobante, cc.ser_timbrado, cc.tip_comprobante,
               cc.fec_comprobante,
               NVL(pe.nombre_fantasia, pe.nombre) AS nombre_proveedor
          FROM compras_cabecera cc
          JOIN personas pe
                 ON pe.cod_persona = cc.cod_persona
                AND pe.cod_empresa = cc.cod_empresa
         WHERE cc.cod_empresa = p_cod_empresa
           AND cc.tip_comprobante = 'FCR'
           AND PKG_COMPRAS.FN_SALDO_PROVEEDOR(p_cod_empresa, cc.id_factura) = 'S'
           AND (
                 TRIM(p_q) IS NULL
                 OR TO_CHAR(cc.id_factura) LIKE l_q
                 OR TO_CHAR(cc.nro_comprobante) LIKE l_q
                 OR UPPER(cc.ser_timbrado) LIKE l_q
                 OR UPPER(pe.nombre) LIKE l_q
                 OR UPPER(pe.nombre_fantasia) LIKE l_q
               )
         ORDER BY cc.fec_comprobante ASC
         FETCH FIRST 30 ROWS ONLY
    ) LOOP
      APEX_JSON.OPEN_OBJECT;
      APEX_JSON.WRITE('id_factura', r.id_factura);
      APEX_JSON.WRITE('nro_comprobante', r.nro_comprobante);
      APEX_JSON.WRITE('ser_timbrado', r.ser_timbrado);
      APEX_JSON.WRITE('tip_comprobante', r.tip_comprobante);
      APEX_JSON.WRITE('fec_comprobante', TO_CHAR(r.fec_comprobante, 'YYYY-MM-DD'));
      APEX_JSON.WRITE('nombre_proveedor', r.nombre_proveedor);
      APEX_JSON.CLOSE_OBJECT;
    END LOOP;
    APEX_JSON.CLOSE_ARRAY;
    APEX_JSON.CLOSE_OBJECT;
  EXCEPTION
    WHEN OTHERS THEN
      p_error(500, 'Internal Server Error', 'Error: ' || SQLERRM);
  END BUSCAR_COMPRAS;

END PKG_COMPRAS_PAGOS_LUBRIMEC;
/

--------------------------------------------------------------------------------
-- === 2) ENDPOINTS ORDS =====================================================
--
--   GET    /lubrimec/compras-pagos?cod_empresa=:n     -> listar
--   GET    /lubrimec/compras-pagos/:id                -> obtener
--   POST   /lubrimec/compras-pagos                    -> insertar
--   PUT    /lubrimec/compras-pagos/:id                -> actualizar
--   DELETE /lubrimec/compras-pagos/:id                -> eliminar
--   GET    /lubrimec/compras/buscar?cod_empresa=:n&q=:q -> selector de facturas
--------------------------------------------------------------------------------

BEGIN
  BEGIN ORDS.DELETE_HANDLER('lubrimec', 'compras-pagos', 'GET');        EXCEPTION WHEN OTHERS THEN NULL; END;
  BEGIN ORDS.DELETE_HANDLER('lubrimec', 'compras-pagos', 'POST');       EXCEPTION WHEN OTHERS THEN NULL; END;
  BEGIN ORDS.DELETE_HANDLER('lubrimec', 'compras-pagos/:id', 'GET');    EXCEPTION WHEN OTHERS THEN NULL; END;
  BEGIN ORDS.DELETE_HANDLER('lubrimec', 'compras-pagos/:id', 'PUT');    EXCEPTION WHEN OTHERS THEN NULL; END;
  BEGIN ORDS.DELETE_HANDLER('lubrimec', 'compras-pagos/:id', 'DELETE'); EXCEPTION WHEN OTHERS THEN NULL; END;
  BEGIN ORDS.DELETE_HANDLER('lubrimec', 'compras/buscar', 'GET');       EXCEPTION WHEN OTHERS THEN NULL; END;

  ----------------------------------------------------------------------------
  -- Plantilla coleccion: /compras-pagos
  ----------------------------------------------------------------------------
  BEGIN
    ORDS.DEFINE_TEMPLATE(
        p_module_name => 'lubrimec',
        p_pattern     => 'compras-pagos',
        p_priority    => 0,
        p_etag_type   => 'HASH',
        p_comments    => NULL);
  EXCEPTION WHEN OTHERS THEN NULL; END;

  -- GET /compras-pagos?cod_empresa=:n  -> listar
  ORDS.DEFINE_HANDLER(
      p_module_name => 'lubrimec',
      p_pattern     => 'compras-pagos',
      p_method      => 'GET',
      p_source_type => 'plsql/block',
      p_source      => q'~
DECLARE
    l_token       VARCHAR2(256); l_pos PLS_INTEGER;
    l_query       VARCHAR2(4000); l_cod_empresa VARCHAR2(20);
    FUNCTION get_qs(p_qs IN VARCHAR2, p_key IN VARCHAR2) RETURN VARCHAR2 IS
        l_p PLS_INTEGER; l_e PLS_INTEGER; l_v VARCHAR2(4000);
    BEGIN
        l_p := INSTR('&' || p_qs, '&' || p_key || '=');
        IF l_p = 0 THEN RETURN NULL; END IF;
        l_p := l_p + LENGTH(p_key) + 1;
        l_e := INSTR(p_qs || '&', '&', l_p);
        l_v := SUBSTR(p_qs, l_p, l_e - l_p);
        l_v := REPLACE(l_v, '+', ' ');
        RETURN UTL_URL.UNESCAPE(l_v);
    END;
BEGIN
    OWA_UTIL.MIME_HEADER('application/json', FALSE);
    HTP.P('Access-Control-Allow-Origin: *');
    HTP.P('Access-Control-Allow-Methods: GET, POST, PUT, DELETE, OPTIONS');
    HTP.P('Access-Control-Allow-Headers: Authorization, Content-Type');
    OWA_UTIL.HTTP_HEADER_CLOSE;
    l_token := :authorization;
    IF l_token IS NOT NULL THEN
        l_pos := INSTR(UPPER(l_token), 'BEARER ');
        IF l_pos > 0 THEN l_token := TRIM(SUBSTR(l_token, l_pos + 7)); END IF;
    END IF;
    l_query       := OWA_UTIL.GET_CGI_ENV('QUERY_STRING');
    l_cod_empresa := get_qs(l_query, 'cod_empresa');
    PKG_COMPRAS_PAGOS_LUBRIMEC.LISTAR(p_token => l_token, p_cod_empresa => TO_NUMBER(l_cod_empresa));
END;
~');

  ORDS.DEFINE_PARAMETER(
      p_module_name        => 'lubrimec',
      p_pattern            => 'compras-pagos',
      p_method             => 'GET',
      p_name               => 'Authorization',
      p_bind_variable_name => 'authorization',
      p_source_type        => 'HEADER',
      p_param_type         => 'STRING',
      p_access_method      => 'IN');

  -- POST /compras-pagos  -> insertar
  ORDS.DEFINE_HANDLER(
      p_module_name => 'lubrimec',
      p_pattern     => 'compras-pagos',
      p_method      => 'POST',
      p_source_type => 'plsql/block',
      p_source      => q'~
DECLARE l_token VARCHAR2(256); l_pos PLS_INTEGER;
BEGIN
    OWA_UTIL.MIME_HEADER('application/json', FALSE);
    HTP.P('Access-Control-Allow-Origin: *');
    HTP.P('Access-Control-Allow-Methods: GET, POST, PUT, DELETE, OPTIONS');
    HTP.P('Access-Control-Allow-Headers: Authorization, Content-Type');
    OWA_UTIL.HTTP_HEADER_CLOSE;
    l_token := :authorization;
    IF l_token IS NOT NULL THEN
        l_pos := INSTR(UPPER(l_token), 'BEARER ');
        IF l_pos > 0 THEN l_token := TRIM(SUBSTR(l_token, l_pos + 7)); END IF;
    END IF;
    PKG_COMPRAS_PAGOS_LUBRIMEC.INSERTAR(
        p_token => l_token, p_fecha => :fecha, p_id_factura => TO_NUMBER(:id_factura),
        p_id_forma => TO_NUMBER(:id_forma), p_monto => TO_NUMBER(:monto),
        p_observacion => :observacion, p_nro_recibo => TO_NUMBER(:nro_recibo),
        p_cod_empresa => TO_NUMBER(:cod_empresa));
END;
~');

  ORDS.DEFINE_PARAMETER(
      p_module_name        => 'lubrimec',
      p_pattern            => 'compras-pagos',
      p_method             => 'POST',
      p_name               => 'Authorization',
      p_bind_variable_name => 'authorization',
      p_source_type        => 'HEADER',
      p_param_type         => 'STRING',
      p_access_method      => 'IN');

  ----------------------------------------------------------------------------
  -- Plantilla item: /compras-pagos/:id
  ----------------------------------------------------------------------------
  BEGIN
    ORDS.DEFINE_TEMPLATE(
        p_module_name => 'lubrimec',
        p_pattern     => 'compras-pagos/:id',
        p_priority    => 0,
        p_etag_type   => 'HASH',
        p_comments    => NULL);
  EXCEPTION WHEN OTHERS THEN NULL; END;

  -- GET /compras-pagos/:id  -> obtener
  ORDS.DEFINE_HANDLER(
      p_module_name => 'lubrimec',
      p_pattern     => 'compras-pagos/:id',
      p_method      => 'GET',
      p_source_type => 'plsql/block',
      p_source      => q'~
DECLARE
    l_token       VARCHAR2(256); l_pos PLS_INTEGER;
    l_query       VARCHAR2(4000); l_cod_empresa VARCHAR2(20);
    FUNCTION get_qs(p_qs IN VARCHAR2, p_key IN VARCHAR2) RETURN VARCHAR2 IS
        l_p PLS_INTEGER; l_e PLS_INTEGER; l_v VARCHAR2(4000);
    BEGIN
        l_p := INSTR('&' || p_qs, '&' || p_key || '=');
        IF l_p = 0 THEN RETURN NULL; END IF;
        l_p := l_p + LENGTH(p_key) + 1;
        l_e := INSTR(p_qs || '&', '&', l_p);
        l_v := SUBSTR(p_qs, l_p, l_e - l_p);
        l_v := REPLACE(l_v, '+', ' ');
        RETURN UTL_URL.UNESCAPE(l_v);
    END;
BEGIN
    OWA_UTIL.MIME_HEADER('application/json', FALSE);
    HTP.P('Access-Control-Allow-Origin: *');
    HTP.P('Access-Control-Allow-Methods: GET, POST, PUT, DELETE, OPTIONS');
    HTP.P('Access-Control-Allow-Headers: Authorization, Content-Type');
    OWA_UTIL.HTTP_HEADER_CLOSE;
    l_token := :authorization;
    IF l_token IS NOT NULL THEN
        l_pos := INSTR(UPPER(l_token), 'BEARER ');
        IF l_pos > 0 THEN l_token := TRIM(SUBSTR(l_token, l_pos + 7)); END IF;
    END IF;
    l_query       := OWA_UTIL.GET_CGI_ENV('QUERY_STRING');
    l_cod_empresa := get_qs(l_query, 'cod_empresa');
    PKG_COMPRAS_PAGOS_LUBRIMEC.OBTENER(
        p_token => l_token, p_id => TO_NUMBER(:id), p_cod_empresa => TO_NUMBER(l_cod_empresa));
END;
~');

  ORDS.DEFINE_PARAMETER(
      p_module_name        => 'lubrimec',
      p_pattern            => 'compras-pagos/:id',
      p_method             => 'GET',
      p_name               => 'Authorization',
      p_bind_variable_name => 'authorization',
      p_source_type        => 'HEADER',
      p_param_type         => 'STRING',
      p_access_method      => 'IN');

  -- PUT /compras-pagos/:id  -> actualizar
  ORDS.DEFINE_HANDLER(
      p_module_name => 'lubrimec',
      p_pattern     => 'compras-pagos/:id',
      p_method      => 'PUT',
      p_source_type => 'plsql/block',
      p_source      => q'~
DECLARE l_token VARCHAR2(256); l_pos PLS_INTEGER;
BEGIN
    OWA_UTIL.MIME_HEADER('application/json', FALSE);
    HTP.P('Access-Control-Allow-Origin: *');
    HTP.P('Access-Control-Allow-Methods: GET, POST, PUT, DELETE, OPTIONS');
    HTP.P('Access-Control-Allow-Headers: Authorization, Content-Type');
    OWA_UTIL.HTTP_HEADER_CLOSE;
    l_token := :authorization;
    IF l_token IS NOT NULL THEN
        l_pos := INSTR(UPPER(l_token), 'BEARER ');
        IF l_pos > 0 THEN l_token := TRIM(SUBSTR(l_token, l_pos + 7)); END IF;
    END IF;
    PKG_COMPRAS_PAGOS_LUBRIMEC.ACTUALIZAR(
        p_token => l_token, p_id => TO_NUMBER(:id), p_fecha => :fecha,
        p_id_factura => TO_NUMBER(:id_factura), p_id_forma => TO_NUMBER(:id_forma),
        p_monto => TO_NUMBER(:monto), p_observacion => :observacion,
        p_nro_recibo => TO_NUMBER(:nro_recibo), p_cod_empresa => TO_NUMBER(:cod_empresa));
END;
~');

  ORDS.DEFINE_PARAMETER(
      p_module_name        => 'lubrimec',
      p_pattern            => 'compras-pagos/:id',
      p_method             => 'PUT',
      p_name               => 'Authorization',
      p_bind_variable_name => 'authorization',
      p_source_type        => 'HEADER',
      p_param_type         => 'STRING',
      p_access_method      => 'IN');

  -- DELETE /compras-pagos/:id  -> eliminar
  ORDS.DEFINE_HANDLER(
      p_module_name => 'lubrimec',
      p_pattern     => 'compras-pagos/:id',
      p_method      => 'DELETE',
      p_source_type => 'plsql/block',
      p_source      => q'~
DECLARE
    l_token       VARCHAR2(256); l_pos PLS_INTEGER;
    l_query       VARCHAR2(4000); l_cod_empresa VARCHAR2(20);
    FUNCTION get_qs(p_qs IN VARCHAR2, p_key IN VARCHAR2) RETURN VARCHAR2 IS
        l_p PLS_INTEGER; l_e PLS_INTEGER; l_v VARCHAR2(4000);
    BEGIN
        l_p := INSTR('&' || p_qs, '&' || p_key || '=');
        IF l_p = 0 THEN RETURN NULL; END IF;
        l_p := l_p + LENGTH(p_key) + 1;
        l_e := INSTR(p_qs || '&', '&', l_p);
        l_v := SUBSTR(p_qs, l_p, l_e - l_p);
        l_v := REPLACE(l_v, '+', ' ');
        RETURN UTL_URL.UNESCAPE(l_v);
    END;
BEGIN
    OWA_UTIL.MIME_HEADER('application/json', FALSE);
    HTP.P('Access-Control-Allow-Origin: *');
    HTP.P('Access-Control-Allow-Methods: GET, POST, PUT, DELETE, OPTIONS');
    HTP.P('Access-Control-Allow-Headers: Authorization, Content-Type');
    OWA_UTIL.HTTP_HEADER_CLOSE;
    l_token := :authorization;
    IF l_token IS NOT NULL THEN
        l_pos := INSTR(UPPER(l_token), 'BEARER ');
        IF l_pos > 0 THEN l_token := TRIM(SUBSTR(l_token, l_pos + 7)); END IF;
    END IF;
    l_query       := OWA_UTIL.GET_CGI_ENV('QUERY_STRING');
    l_cod_empresa := get_qs(l_query, 'cod_empresa');
    PKG_COMPRAS_PAGOS_LUBRIMEC.ELIMINAR(
        p_token => l_token, p_id => TO_NUMBER(:id), p_cod_empresa => TO_NUMBER(l_cod_empresa));
END;
~');

  ORDS.DEFINE_PARAMETER(
      p_module_name        => 'lubrimec',
      p_pattern            => 'compras-pagos/:id',
      p_method             => 'DELETE',
      p_name               => 'Authorization',
      p_bind_variable_name => 'authorization',
      p_source_type        => 'HEADER',
      p_param_type         => 'STRING',
      p_access_method      => 'IN');

  ----------------------------------------------------------------------------
  -- /compras/buscar  -> selector de facturas del formulario
  ----------------------------------------------------------------------------
  BEGIN
    ORDS.DEFINE_TEMPLATE(
        p_module_name => 'lubrimec',
        p_pattern     => 'compras/buscar',
        p_priority    => 0,
        p_etag_type   => 'HASH',
        p_comments    => NULL);
  EXCEPTION WHEN OTHERS THEN NULL; END;

  ORDS.DEFINE_HANDLER(
      p_module_name => 'lubrimec',
      p_pattern     => 'compras/buscar',
      p_method      => 'GET',
      p_source_type => 'plsql/block',
      p_source      => q'~
DECLARE
    l_token       VARCHAR2(256); l_pos PLS_INTEGER;
    l_query       VARCHAR2(4000); l_cod_empresa VARCHAR2(20); l_q VARCHAR2(4000);
    FUNCTION get_qs(p_qs IN VARCHAR2, p_key IN VARCHAR2) RETURN VARCHAR2 IS
        l_p PLS_INTEGER; l_e PLS_INTEGER; l_v VARCHAR2(4000);
    BEGIN
        l_p := INSTR('&' || p_qs, '&' || p_key || '=');
        IF l_p = 0 THEN RETURN NULL; END IF;
        l_p := l_p + LENGTH(p_key) + 1;
        l_e := INSTR(p_qs || '&', '&', l_p);
        l_v := SUBSTR(p_qs, l_p, l_e - l_p);
        l_v := REPLACE(l_v, '+', ' ');
        RETURN UTL_URL.UNESCAPE(l_v);
    END;
BEGIN
    OWA_UTIL.MIME_HEADER('application/json', FALSE);
    HTP.P('Access-Control-Allow-Origin: *');
    HTP.P('Access-Control-Allow-Methods: GET, OPTIONS');
    HTP.P('Access-Control-Allow-Headers: Authorization, Content-Type');
    OWA_UTIL.HTTP_HEADER_CLOSE;
    l_token := :authorization;
    IF l_token IS NOT NULL THEN
        l_pos := INSTR(UPPER(l_token), 'BEARER ');
        IF l_pos > 0 THEN l_token := TRIM(SUBSTR(l_token, l_pos + 7)); END IF;
    END IF;
    l_query       := OWA_UTIL.GET_CGI_ENV('QUERY_STRING');
    l_cod_empresa := get_qs(l_query, 'cod_empresa');
    l_q           := get_qs(l_query, 'q');
    PKG_COMPRAS_PAGOS_LUBRIMEC.BUSCAR_COMPRAS(
        p_token => l_token, p_cod_empresa => TO_NUMBER(l_cod_empresa), p_q => l_q);
END;
~');

  ORDS.DEFINE_PARAMETER(
      p_module_name        => 'lubrimec',
      p_pattern            => 'compras/buscar',
      p_method             => 'GET',
      p_name               => 'Authorization',
      p_bind_variable_name => 'authorization',
      p_source_type        => 'HEADER',
      p_param_type         => 'STRING',
      p_access_method      => 'IN');

  COMMIT;
EXCEPTION
  WHEN OTHERS THEN
    ROLLBACK;
    RAISE;
END;
/
