--------------------------------------------------------------------------------
-- CONTEO_EFECTIVO (pagina APEX 85, modal 86) — paquete CRUD + endpoints ORDS.
-- Ejecutar completo como el esquema JOSEGALVEZ. Requiere PKG_AUTH_LUBRIMEC.
--
-- PK id_conteo GENERATED BY DEFAULT AS IDENTITY (no se pasa en el INSERT, se
-- devuelve con RETURNING). Multiempresa (cod_empresa). total = valor * cantidad.
-- UK (fecha, valor) -> 409 en duplicado. FK (valor, cod_moneda) -> monedas_detalle.
--
-- Permisos (igual que APEX): el usuario 'JOSEG' ve todo y puede filtrar por fecha;
-- cualquier otro usuario solo ve el conteo del dia de hoy. Se pasa p_app_user
-- (viene del token / sesion) para decidir.
--
-- El select de moneda usa el endpoint existente /monedas; el select de valores del
-- billete (con imagen) usa /monedas/:id/detalle. Aqui no se replican esos endpoints.
--
-- === 1) PAQUETE PKG_CONTEO_EFECTIVO_LUBRIMEC ===============================
--------------------------------------------------------------------------------

CREATE OR REPLACE PACKAGE PKG_CONTEO_EFECTIVO_LUBRIMEC AS

  PROCEDURE LISTAR(p_token IN VARCHAR2, p_cod_empresa IN NUMBER,
                   p_app_user IN VARCHAR2, p_fecha IN VARCHAR2, p_dias IN NUMBER);
  PROCEDURE OBTENER(p_token IN VARCHAR2, p_id IN NUMBER, p_cod_empresa IN NUMBER);
  PROCEDURE INSERTAR(
      p_token IN VARCHAR2, p_fecha IN VARCHAR2, p_valor IN NUMBER,
      p_cantidad IN NUMBER, p_cod_moneda IN NUMBER, p_cod_empresa IN NUMBER);
  PROCEDURE ACTUALIZAR(
      p_token IN VARCHAR2, p_id IN NUMBER, p_fecha IN VARCHAR2, p_valor IN NUMBER,
      p_cantidad IN NUMBER, p_cod_moneda IN NUMBER, p_cod_empresa IN NUMBER);
  PROCEDURE ELIMINAR(p_token IN VARCHAR2, p_id IN NUMBER, p_cod_empresa IN NUMBER);
  -- Panel de totales de control (solo JOSEG). Replica los calculos del APEX pag 85.
  PROCEDURE RESUMEN(p_token IN VARCHAR2, p_cod_empresa IN NUMBER,
                    p_app_user IN VARCHAR2, p_fecha IN VARCHAR2);

END PKG_CONTEO_EFECTIVO_LUBRIMEC;
/

CREATE OR REPLACE PACKAGE BODY PKG_CONTEO_EFECTIVO_LUBRIMEC AS

  PROCEDURE p_error(p_status IN NUMBER, p_reason IN VARCHAR2, p_message IN VARCHAR2) IS
  BEGIN
    OWA_UTIL.STATUS_LINE(p_status, p_reason, FALSE);
    APEX_JSON.OPEN_OBJECT;
    APEX_JSON.WRITE('success', FALSE);
    APEX_JSON.WRITE('message', p_message);
    APEX_JSON.CLOSE_OBJECT;
  END p_error;

  FUNCTION f_usuario(p_token IN VARCHAR2) RETURN VARCHAR2 IS
  BEGIN
    RETURN PKG_AUTH_LUBRIMEC.VALIDAR_TOKEN(p_token);
  END f_usuario;

  --------------------------------------------------------------------------
  -- LISTAR (JOIN a monedas_detalle para nombre_imagen/mime; total calculado).
  -- Permiso: JOSEG filtra por p_fecha (o ve todo si viene NULL); el resto solo hoy.
  --------------------------------------------------------------------------
  PROCEDURE LISTAR(p_token IN VARCHAR2, p_cod_empresa IN NUMBER,
                   p_app_user IN VARCHAR2, p_fecha IN VARCHAR2, p_dias IN NUMBER) IS
    l_usuario VARCHAR2(255);
    l_es_admin BOOLEAN := (UPPER(NVL(p_app_user, '-')) = 'JOSEG');
    l_fecha    DATE := TO_DATE(p_fecha, 'YYYY-MM-DD');
    -- Ventana de dias hacia atras (default 3). 0 o NULL = sin limite (todo).
    l_dias     NUMBER := NVL(p_dias, 3);
  BEGIN
    l_usuario := f_usuario(p_token);
    IF l_usuario IS NULL THEN
      p_error(401, 'Unauthorized', 'Token invalido o expirado');
      RETURN;
    END IF;

    APEX_JSON.OPEN_OBJECT;
    APEX_JSON.WRITE('success', TRUE);
    APEX_JSON.OPEN_ARRAY('data');
    FOR r IN (
        SELECT a.id_conteo, a.fecha, a.valor, a.cantidad, a.cod_moneda, a.cod_empresa,
               NVL(a.valor, 0) * NVL(a.cantidad, 0) AS total,
               m.descripcion AS moneda
          FROM conteo_efectivo a
          LEFT JOIN monedas m ON m.cod_moneda = a.cod_moneda
         WHERE a.cod_empresa = p_cod_empresa
           AND (
                 -- JOSEG: si eligio fecha, esa fecha; si no, los ultimos l_dias
                 -- dias (o todo si l_dias <= 0).
                 (l_es_admin AND (
                     (l_fecha IS NOT NULL AND TRUNC(a.fecha) = l_fecha)
                     OR (l_fecha IS NULL AND (l_dias <= 0
                          OR TRUNC(a.fecha) >= TRUNC(SYSDATE) - (l_dias - 1)))
                 ))
                 -- resto: solo hoy
                 OR (NOT l_es_admin AND TRUNC(a.fecha) = TRUNC(SYSDATE))
               )
         ORDER BY a.fecha DESC, a.valor ASC
    ) LOOP
      APEX_JSON.OPEN_OBJECT;
      APEX_JSON.WRITE('id_conteo', r.id_conteo);
      APEX_JSON.WRITE('fecha', TO_CHAR(r.fecha, 'YYYY-MM-DD'));
      APEX_JSON.WRITE('valor', r.valor);
      APEX_JSON.WRITE('cantidad', r.cantidad);
      APEX_JSON.WRITE('cod_moneda', r.cod_moneda);
      APEX_JSON.WRITE('moneda', r.moneda);
      APEX_JSON.WRITE('total', r.total);
      APEX_JSON.WRITE('cod_empresa', r.cod_empresa);
      APEX_JSON.CLOSE_OBJECT;
    END LOOP;
    APEX_JSON.CLOSE_ARRAY;
    APEX_JSON.CLOSE_OBJECT;
  EXCEPTION
    WHEN OTHERS THEN
      p_error(500, 'Internal Server Error', 'Error: ' || SQLERRM);
  END LISTAR;

  --------------------------------------------------------------------------
  -- OBTENER
  --------------------------------------------------------------------------
  PROCEDURE OBTENER(p_token IN VARCHAR2, p_id IN NUMBER, p_cod_empresa IN NUMBER) IS
    l_usuario    VARCHAR2(255);
    l_fecha      conteo_efectivo.fecha%TYPE;
    l_valor      conteo_efectivo.valor%TYPE;
    l_cantidad   conteo_efectivo.cantidad%TYPE;
    l_cod_moneda conteo_efectivo.cod_moneda%TYPE;
  BEGIN
    l_usuario := f_usuario(p_token);
    IF l_usuario IS NULL THEN
      p_error(401, 'Unauthorized', 'Token invalido o expirado');
      RETURN;
    END IF;

    BEGIN
      SELECT fecha, valor, cantidad, cod_moneda
        INTO l_fecha, l_valor, l_cantidad, l_cod_moneda
        FROM conteo_efectivo
       WHERE id_conteo = p_id AND cod_empresa = p_cod_empresa;
    EXCEPTION
      WHEN NO_DATA_FOUND THEN
        p_error(404, 'Not Found', 'Conteo no encontrado');
        RETURN;
    END;

    APEX_JSON.OPEN_OBJECT;
    APEX_JSON.WRITE('success', TRUE);
    APEX_JSON.OPEN_OBJECT('data');
    APEX_JSON.WRITE('id_conteo', p_id);
    APEX_JSON.WRITE('fecha', TO_CHAR(l_fecha, 'YYYY-MM-DD'));
    APEX_JSON.WRITE('valor', l_valor);
    APEX_JSON.WRITE('cantidad', l_cantidad);
    APEX_JSON.WRITE('cod_moneda', l_cod_moneda);
    APEX_JSON.WRITE('total', NVL(l_valor, 0) * NVL(l_cantidad, 0));
    APEX_JSON.WRITE('cod_empresa', p_cod_empresa);
    APEX_JSON.CLOSE_OBJECT;
    APEX_JSON.CLOSE_OBJECT;
  EXCEPTION
    WHEN OTHERS THEN
      p_error(500, 'Internal Server Error', 'Error: ' || SQLERRM);
  END OBTENER;

  --------------------------------------------------------------------------
  -- INSERTAR (PK IDENTITY; UK fecha+valor -> 409; FK valor+moneda -> 400)
  --------------------------------------------------------------------------
  PROCEDURE INSERTAR(
      p_token IN VARCHAR2, p_fecha IN VARCHAR2, p_valor IN NUMBER,
      p_cantidad IN NUMBER, p_cod_moneda IN NUMBER, p_cod_empresa IN NUMBER) IS
    l_usuario VARCHAR2(255);
    l_id      conteo_efectivo.id_conteo%TYPE;
    l_fecha   DATE := TO_DATE(p_fecha, 'YYYY-MM-DD');
  BEGIN
    l_usuario := f_usuario(p_token);
    IF l_usuario IS NULL THEN
      p_error(401, 'Unauthorized', 'Token invalido o expirado');
      RETURN;
    END IF;

    IF l_fecha IS NULL THEN
      p_error(400, 'Bad Request', 'La fecha es obligatoria'); RETURN;
    END IF;
    IF p_valor IS NULL THEN
      p_error(400, 'Bad Request', 'El valor es obligatorio'); RETURN;
    END IF;
    IF p_cantidad IS NULL THEN
      p_error(400, 'Bad Request', 'La cantidad es obligatoria'); RETURN;
    END IF;
    IF p_cod_moneda IS NULL THEN
      p_error(400, 'Bad Request', 'La moneda es obligatoria'); RETURN;
    END IF;
    IF p_cod_empresa IS NULL THEN
      p_error(400, 'Bad Request', 'cod_empresa es obligatorio'); RETURN;
    END IF;

    INSERT INTO conteo_efectivo (fecha, valor, cantidad, cod_moneda, cod_empresa)
    VALUES (l_fecha, p_valor, p_cantidad, p_cod_moneda, p_cod_empresa)
    RETURNING id_conteo INTO l_id;
    COMMIT;

    OWA_UTIL.STATUS_LINE(201, 'Created', FALSE);
    APEX_JSON.OPEN_OBJECT;
    APEX_JSON.WRITE('success', TRUE);
    APEX_JSON.WRITE('message', 'Conteo creado');
    APEX_JSON.WRITE('id_conteo', l_id);
    APEX_JSON.CLOSE_OBJECT;
  EXCEPTION
    WHEN DUP_VAL_ON_INDEX THEN
      ROLLBACK;
      p_error(409, 'Conflict', 'Ya existe un conteo para esa fecha y valor');
    WHEN OTHERS THEN
      ROLLBACK;
      -- -2291: FK padre no existe (valor/moneda inexistente en monedas_detalle)
      IF SQLCODE = -2291 THEN
        p_error(400, 'Bad Request', 'El valor no corresponde a la moneda indicada');
      ELSE
        p_error(500, 'Internal Server Error', 'Error: ' || SQLERRM);
      END IF;
  END INSERTAR;

  --------------------------------------------------------------------------
  -- ACTUALIZAR
  --------------------------------------------------------------------------
  PROCEDURE ACTUALIZAR(
      p_token IN VARCHAR2, p_id IN NUMBER, p_fecha IN VARCHAR2, p_valor IN NUMBER,
      p_cantidad IN NUMBER, p_cod_moneda IN NUMBER, p_cod_empresa IN NUMBER) IS
    l_usuario VARCHAR2(255);
    l_fecha   DATE := TO_DATE(p_fecha, 'YYYY-MM-DD');
  BEGIN
    l_usuario := f_usuario(p_token);
    IF l_usuario IS NULL THEN
      p_error(401, 'Unauthorized', 'Token invalido o expirado');
      RETURN;
    END IF;

    IF l_fecha IS NULL THEN
      p_error(400, 'Bad Request', 'La fecha es obligatoria'); RETURN;
    END IF;
    IF p_valor IS NULL THEN
      p_error(400, 'Bad Request', 'El valor es obligatorio'); RETURN;
    END IF;
    IF p_cantidad IS NULL THEN
      p_error(400, 'Bad Request', 'La cantidad es obligatoria'); RETURN;
    END IF;
    IF p_cod_moneda IS NULL THEN
      p_error(400, 'Bad Request', 'La moneda es obligatoria'); RETURN;
    END IF;

    UPDATE conteo_efectivo
       SET fecha      = l_fecha,
           valor      = p_valor,
           cantidad   = p_cantidad,
           cod_moneda = p_cod_moneda
     WHERE id_conteo = p_id AND cod_empresa = p_cod_empresa;

    IF SQL%ROWCOUNT = 0 THEN
      ROLLBACK;
      p_error(404, 'Not Found', 'Conteo no encontrado');
      RETURN;
    END IF;
    COMMIT;

    APEX_JSON.OPEN_OBJECT;
    APEX_JSON.WRITE('success', TRUE);
    APEX_JSON.WRITE('message', 'Conteo actualizado');
    APEX_JSON.CLOSE_OBJECT;
  EXCEPTION
    WHEN DUP_VAL_ON_INDEX THEN
      ROLLBACK;
      p_error(409, 'Conflict', 'Ya existe un conteo para esa fecha y valor');
    WHEN OTHERS THEN
      ROLLBACK;
      IF SQLCODE = -2291 THEN
        p_error(400, 'Bad Request', 'El valor no corresponde a la moneda indicada');
      ELSE
        p_error(500, 'Internal Server Error', 'Error: ' || SQLERRM);
      END IF;
  END ACTUALIZAR;

  --------------------------------------------------------------------------
  -- ELIMINAR
  --------------------------------------------------------------------------
  PROCEDURE ELIMINAR(p_token IN VARCHAR2, p_id IN NUMBER, p_cod_empresa IN NUMBER) IS
    l_usuario VARCHAR2(255);
  BEGIN
    l_usuario := f_usuario(p_token);
    IF l_usuario IS NULL THEN
      p_error(401, 'Unauthorized', 'Token invalido o expirado');
      RETURN;
    END IF;

    DELETE FROM conteo_efectivo
     WHERE id_conteo = p_id AND cod_empresa = p_cod_empresa;

    IF SQL%ROWCOUNT = 0 THEN
      ROLLBACK;
      p_error(404, 'Not Found', 'Conteo no encontrado');
      RETURN;
    END IF;
    COMMIT;

    APEX_JSON.OPEN_OBJECT;
    APEX_JSON.WRITE('success', TRUE);
    APEX_JSON.WRITE('message', 'Conteo eliminado');
    APEX_JSON.CLOSE_OBJECT;
  EXCEPTION
    WHEN OTHERS THEN
      ROLLBACK;
      p_error(500, 'Internal Server Error', 'Error: ' || SQLERRM);
  END ELIMINAR;

  --------------------------------------------------------------------------
  -- RESUMEN: 7 totales de control del dia (solo JOSEG). Cada calculo va en su
  -- propio bloque con EXCEPTION -> 0, igual que el APEX (nunca rompe el panel).
  -- p_fecha en YYYY-MM-DD (del front); internamente se compara como dd/mm/yyyy
  -- contra los TO_CHAR de las tablas, como en el APEX original.
  --------------------------------------------------------------------------
  PROCEDURE RESUMEN(p_token IN VARCHAR2, p_cod_empresa IN NUMBER,
                    p_app_user IN VARCHAR2, p_fecha IN VARCHAR2) IS
    l_usuario         VARCHAR2(255);
    l_fecha_txt       VARCHAR2(10);  -- dd/mm/yyyy (como usa el APEX)
    l_efectivo        NUMBER := 0;   -- cobros efectivo del dia (id_forma = 1)
    l_no_efectivo     NUMBER := 0;   -- otras formas de cobro (id_forma <> 1)
    l_conteo_anterior NUMBER := 0;   -- ultimo conteo anterior a la fecha
    l_total_conteo    NUMBER := 0;   -- suma valor*cantidad del dia (grilla)
    l_pagos           NUMBER := 0;   -- pagos a proveedores del dia
    l_retiro          NUMBER := 0;   -- retiros de efectivo del dia
    l_total_caja      NUMBER := 0;
    l_diferencia      NUMBER := 0;
  BEGIN
    l_usuario := f_usuario(p_token);
    IF l_usuario IS NULL THEN
      p_error(401, 'Unauthorized', 'Token invalido o expirado');
      RETURN;
    END IF;

    -- Panel solo para JOSEG: si no es, devuelve visible=false sin numeros.
    IF UPPER(NVL(p_app_user, '-')) <> 'JOSEG' THEN
      APEX_JSON.OPEN_OBJECT;
      APEX_JSON.WRITE('success', TRUE);
      APEX_JSON.OPEN_OBJECT('data');
      APEX_JSON.WRITE('visible', FALSE);
      APEX_JSON.CLOSE_OBJECT;
      APEX_JSON.CLOSE_OBJECT;
      RETURN;
    END IF;

    l_fecha_txt := TO_CHAR(TO_DATE(p_fecha, 'YYYY-MM-DD'), 'dd/mm/yyyy');

    -- 1) Total en efectivo del dia (V_COBROS_CLIENTES, id_forma = 1)
    BEGIN
      SELECT SUM(total) INTO l_efectivo
        FROM v_cobros_clientes
       WHERE cod_empresa = p_cod_empresa AND id_forma = 1
         AND fecha = l_fecha_txt AND cod_vendedor NOT IN (81, 141);
    EXCEPTION WHEN OTHERS THEN l_efectivo := 0; END;

    -- 2) Otras formas de cobro (id_forma <> 1)
    BEGIN
      SELECT SUM(total) INTO l_no_efectivo
        FROM v_cobros_clientes
       WHERE cod_empresa = p_cod_empresa AND id_forma <> 1
         AND fecha = l_fecha_txt AND cod_vendedor NOT IN (81, 141);
    EXCEPTION WHEN OTHERS THEN l_no_efectivo := 0; END;

    -- 3) Conteo del dia anterior (ultimo conteo con fecha < la fecha dada)
    BEGIN
      SELECT SUM(total_conteo) INTO l_conteo_anterior
        FROM (SELECT SUM(NVL(a.valor,0) * NVL(a.cantidad,0)) total_conteo,
                     TO_CHAR(a.fecha,'dd/mm/yyyy') fecha
                FROM conteo_efectivo a
               WHERE a.cod_empresa = p_cod_empresa
               GROUP BY TO_CHAR(a.fecha,'dd/mm/yyyy'))
       WHERE TO_DATE(fecha,'dd/mm/yyyy') < TO_DATE(l_fecha_txt,'dd/mm/yyyy')
         AND TO_DATE(fecha,'dd/mm/yyyy') =
             (SELECT MAX(TO_DATE(fecha,'dd/mm/yyyy'))
                FROM (SELECT TO_CHAR(a.fecha,'dd/mm/yyyy') fecha
                        FROM conteo_efectivo a
                       WHERE a.cod_empresa = p_cod_empresa
                       GROUP BY TO_CHAR(a.fecha,'dd/mm/yyyy'))
               WHERE TO_DATE(fecha,'dd/mm/yyyy') < TO_DATE(l_fecha_txt,'dd/mm/yyyy'));
    EXCEPTION WHEN OTHERS THEN l_conteo_anterior := 0; END;

    -- 4) Total del conteo del dia (grilla)
    BEGIN
      SELECT SUM(NVL(a.valor,0) * NVL(a.cantidad,0)) INTO l_total_conteo
        FROM conteo_efectivo a
       WHERE a.cod_empresa = p_cod_empresa
         AND TO_CHAR(a.fecha,'dd/mm/yyyy') = l_fecha_txt;
    EXCEPTION WHEN OTHERS THEN l_total_conteo := 0; END;

    -- 5) Pagos a proveedores del dia (COMPRAS_DETALLE)
    BEGIN
      SELECT SUM(NVL(b.cantidad,0) * NVL(b.precio,0)) INTO l_pagos
        FROM compras_cabecera a, compras_detalle b
       WHERE a.cod_empresa = p_cod_empresa
         AND TO_CHAR(a.fec_comprobante,'dd/mm/yyyy') = l_fecha_txt
         AND a.id_factura = b.id_factura
         AND a.id_comprador NOT IN (81);
    EXCEPTION WHEN OTHERS THEN l_pagos := 0; END;

    -- 6) Retiro de efectivo del dia (RENDICIONES_CAJAS)
    BEGIN
      SELECT SUM(NVL(a.total_retiro,0)) INTO l_retiro
        FROM rendiciones_cajas a
       WHERE a.cod_empresa = p_cod_empresa
         AND TO_CHAR(a.fecha,'dd/mm/yyyy') = l_fecha_txt;
    EXCEPTION WHEN OTHERS THEN l_retiro := 0; END;

    -- Total en caja = efectivo + conteo_anterior - pagos - retiros
    l_total_caja := NVL(l_efectivo,0) + NVL(l_conteo_anterior,0)
                    - NVL(l_pagos,0) - NVL(l_retiro,0);
    -- Diferencia = total contado del dia - total_caja
    l_diferencia := NVL(l_total_conteo,0) - l_total_caja;

    APEX_JSON.OPEN_OBJECT;
    APEX_JSON.WRITE('success', TRUE);
    APEX_JSON.OPEN_OBJECT('data');
    APEX_JSON.WRITE('visible', TRUE);
    APEX_JSON.WRITE('total_efectivo', NVL(l_efectivo, 0));
    APEX_JSON.WRITE('no_efectivo', NVL(l_no_efectivo, 0));
    APEX_JSON.WRITE('conteo_anterior', NVL(l_conteo_anterior, 0));
    APEX_JSON.WRITE('total_conteo', NVL(l_total_conteo, 0));
    APEX_JSON.WRITE('pagos', NVL(l_pagos, 0));
    APEX_JSON.WRITE('retiro_efectivo', NVL(l_retiro, 0));
    APEX_JSON.WRITE('total_caja', l_total_caja);
    APEX_JSON.WRITE('diferencia', l_diferencia);
    APEX_JSON.CLOSE_OBJECT;
    APEX_JSON.CLOSE_OBJECT;
  EXCEPTION
    WHEN OTHERS THEN
      p_error(500, 'Internal Server Error', 'Error: ' || SQLERRM);
  END RESUMEN;

END PKG_CONTEO_EFECTIVO_LUBRIMEC;
/

--------------------------------------------------------------------------------
-- === 2) ENDPOINTS ORDS =====================================================
--
--   GET    /lubrimec/conteo-efectivo?cod_empresa=:n&app_user=:u&fecha=:f  -> listar
--   GET    /lubrimec/conteo-efectivo/:id?cod_empresa=:n                   -> obtener
--   POST   /lubrimec/conteo-efectivo                                      -> insertar
--   PUT    /lubrimec/conteo-efectivo/:id                                  -> actualizar
--   DELETE /lubrimec/conteo-efectivo/:id?cod_empresa=:n                   -> eliminar
--------------------------------------------------------------------------------

BEGIN
  BEGIN ORDS.DELETE_HANDLER('lubrimec', 'conteo-efectivo', 'GET');        EXCEPTION WHEN OTHERS THEN NULL; END;
  BEGIN ORDS.DELETE_HANDLER('lubrimec', 'conteo-efectivo', 'POST');       EXCEPTION WHEN OTHERS THEN NULL; END;
  BEGIN ORDS.DELETE_HANDLER('lubrimec', 'conteo-efectivo/:id', 'GET');    EXCEPTION WHEN OTHERS THEN NULL; END;
  BEGIN ORDS.DELETE_HANDLER('lubrimec', 'conteo-efectivo/:id', 'PUT');    EXCEPTION WHEN OTHERS THEN NULL; END;
  BEGIN ORDS.DELETE_HANDLER('lubrimec', 'conteo-efectivo/:id', 'DELETE'); EXCEPTION WHEN OTHERS THEN NULL; END;
  BEGIN ORDS.DELETE_HANDLER('lubrimec', 'conteo-efectivo/resumen', 'GET'); EXCEPTION WHEN OTHERS THEN NULL; END;

  ----------------------------------------------------------------------------
  -- Plantilla coleccion: /conteo-efectivo
  ----------------------------------------------------------------------------
  BEGIN
    ORDS.DEFINE_TEMPLATE(
        p_module_name => 'lubrimec',
        p_pattern     => 'conteo-efectivo',
        p_priority    => 0,
        p_etag_type   => 'HASH',
        p_comments    => NULL);
  EXCEPTION WHEN OTHERS THEN NULL; END;

  -- GET /conteo-efectivo?cod_empresa=:n&app_user=:u&fecha=:f  -> listar
  ORDS.DEFINE_HANDLER(
      p_module_name => 'lubrimec',
      p_pattern     => 'conteo-efectivo',
      p_method      => 'GET',
      p_source_type => 'plsql/block',
      p_source      => q'~
DECLARE
    l_token       VARCHAR2(256); l_pos PLS_INTEGER;
    l_query       VARCHAR2(4000); l_cod_empresa VARCHAR2(20);
    l_app_user    VARCHAR2(255); l_fecha VARCHAR2(20); l_dias VARCHAR2(20);
    FUNCTION get_qs(p_qs IN VARCHAR2, p_key IN VARCHAR2) RETURN VARCHAR2 IS
        l_p PLS_INTEGER; l_e PLS_INTEGER; l_v VARCHAR2(4000);
    BEGIN
        l_p := INSTR('&' || p_qs, '&' || p_key || '=');
        IF l_p = 0 THEN RETURN NULL; END IF;
        l_p := l_p + LENGTH(p_key) + 1;
        l_e := INSTR(p_qs || '&', '&', l_p);
        l_v := SUBSTR(p_qs, l_p, l_e - l_p);
        l_v := REPLACE(l_v, '+', ' ');
        RETURN UTL_URL.UNESCAPE(l_v);
    END;
BEGIN
    OWA_UTIL.MIME_HEADER('application/json', FALSE);
    HTP.P('Access-Control-Allow-Origin: *');
    HTP.P('Access-Control-Allow-Methods: GET, POST, PUT, DELETE, OPTIONS');
    HTP.P('Access-Control-Allow-Headers: Authorization, Content-Type');
    OWA_UTIL.HTTP_HEADER_CLOSE;
    l_token := :authorization;
    IF l_token IS NOT NULL THEN
        l_pos := INSTR(UPPER(l_token), 'BEARER ');
        IF l_pos > 0 THEN l_token := TRIM(SUBSTR(l_token, l_pos + 7)); END IF;
    END IF;
    l_query       := OWA_UTIL.GET_CGI_ENV('QUERY_STRING');
    l_cod_empresa := get_qs(l_query, 'cod_empresa');
    l_app_user    := get_qs(l_query, 'app_user');
    l_fecha       := get_qs(l_query, 'fecha');
    l_dias        := get_qs(l_query, 'dias');
    PKG_CONTEO_EFECTIVO_LUBRIMEC.LISTAR(
        p_token => l_token, p_cod_empresa => TO_NUMBER(l_cod_empresa),
        p_app_user => l_app_user, p_fecha => l_fecha,
        p_dias => CASE WHEN l_dias IS NULL THEN NULL ELSE TO_NUMBER(l_dias) END);
END;
~');

  ORDS.DEFINE_PARAMETER(
      p_module_name => 'lubrimec', p_pattern => 'conteo-efectivo', p_method => 'GET',
      p_name => 'Authorization', p_bind_variable_name => 'authorization',
      p_source_type => 'HEADER', p_param_type => 'STRING', p_access_method => 'IN');

  -- POST /conteo-efectivo  -> insertar
  ORDS.DEFINE_HANDLER(
      p_module_name => 'lubrimec',
      p_pattern     => 'conteo-efectivo',
      p_method      => 'POST',
      p_source_type => 'plsql/block',
      p_source      => q'~
DECLARE l_token VARCHAR2(256); l_pos PLS_INTEGER;
BEGIN
    OWA_UTIL.MIME_HEADER('application/json', FALSE);
    HTP.P('Access-Control-Allow-Origin: *');
    HTP.P('Access-Control-Allow-Methods: GET, POST, PUT, DELETE, OPTIONS');
    HTP.P('Access-Control-Allow-Headers: Authorization, Content-Type');
    OWA_UTIL.HTTP_HEADER_CLOSE;
    l_token := :authorization;
    IF l_token IS NOT NULL THEN
        l_pos := INSTR(UPPER(l_token), 'BEARER ');
        IF l_pos > 0 THEN l_token := TRIM(SUBSTR(l_token, l_pos + 7)); END IF;
    END IF;
    PKG_CONTEO_EFECTIVO_LUBRIMEC.INSERTAR(
        p_token => l_token, p_fecha => :fecha, p_valor => TO_NUMBER(:valor),
        p_cantidad => TO_NUMBER(:cantidad), p_cod_moneda => TO_NUMBER(:cod_moneda),
        p_cod_empresa => TO_NUMBER(:cod_empresa));
END;
~');

  ORDS.DEFINE_PARAMETER(
      p_module_name => 'lubrimec', p_pattern => 'conteo-efectivo', p_method => 'POST',
      p_name => 'Authorization', p_bind_variable_name => 'authorization',
      p_source_type => 'HEADER', p_param_type => 'STRING', p_access_method => 'IN');

  ----------------------------------------------------------------------------
  -- Plantilla item: /conteo-efectivo/:id
  ----------------------------------------------------------------------------
  BEGIN
    ORDS.DEFINE_TEMPLATE(
        p_module_name => 'lubrimec',
        p_pattern     => 'conteo-efectivo/:id',
        p_priority    => 0,
        p_etag_type   => 'HASH',
        p_comments    => NULL);
  EXCEPTION WHEN OTHERS THEN NULL; END;

  -- GET /conteo-efectivo/:id  -> obtener
  ORDS.DEFINE_HANDLER(
      p_module_name => 'lubrimec',
      p_pattern     => 'conteo-efectivo/:id',
      p_method      => 'GET',
      p_source_type => 'plsql/block',
      p_source      => q'~
DECLARE
    l_token       VARCHAR2(256); l_pos PLS_INTEGER;
    l_query       VARCHAR2(4000); l_cod_empresa VARCHAR2(20);
    FUNCTION get_qs(p_qs IN VARCHAR2, p_key IN VARCHAR2) RETURN VARCHAR2 IS
        l_p PLS_INTEGER; l_e PLS_INTEGER; l_v VARCHAR2(4000);
    BEGIN
        l_p := INSTR('&' || p_qs, '&' || p_key || '=');
        IF l_p = 0 THEN RETURN NULL; END IF;
        l_p := l_p + LENGTH(p_key) + 1;
        l_e := INSTR(p_qs || '&', '&', l_p);
        l_v := SUBSTR(p_qs, l_p, l_e - l_p);
        l_v := REPLACE(l_v, '+', ' ');
        RETURN UTL_URL.UNESCAPE(l_v);
    END;
BEGIN
    OWA_UTIL.MIME_HEADER('application/json', FALSE);
    HTP.P('Access-Control-Allow-Origin: *');
    HTP.P('Access-Control-Allow-Methods: GET, POST, PUT, DELETE, OPTIONS');
    HTP.P('Access-Control-Allow-Headers: Authorization, Content-Type');
    OWA_UTIL.HTTP_HEADER_CLOSE;
    l_token := :authorization;
    IF l_token IS NOT NULL THEN
        l_pos := INSTR(UPPER(l_token), 'BEARER ');
        IF l_pos > 0 THEN l_token := TRIM(SUBSTR(l_token, l_pos + 7)); END IF;
    END IF;
    l_query       := OWA_UTIL.GET_CGI_ENV('QUERY_STRING');
    l_cod_empresa := get_qs(l_query, 'cod_empresa');
    PKG_CONTEO_EFECTIVO_LUBRIMEC.OBTENER(
        p_token => l_token, p_id => TO_NUMBER(:id), p_cod_empresa => TO_NUMBER(l_cod_empresa));
END;
~');

  ORDS.DEFINE_PARAMETER(
      p_module_name => 'lubrimec', p_pattern => 'conteo-efectivo/:id', p_method => 'GET',
      p_name => 'Authorization', p_bind_variable_name => 'authorization',
      p_source_type => 'HEADER', p_param_type => 'STRING', p_access_method => 'IN');

  -- PUT /conteo-efectivo/:id  -> actualizar
  ORDS.DEFINE_HANDLER(
      p_module_name => 'lubrimec',
      p_pattern     => 'conteo-efectivo/:id',
      p_method      => 'PUT',
      p_source_type => 'plsql/block',
      p_source      => q'~
DECLARE l_token VARCHAR2(256); l_pos PLS_INTEGER;
BEGIN
    OWA_UTIL.MIME_HEADER('application/json', FALSE);
    HTP.P('Access-Control-Allow-Origin: *');
    HTP.P('Access-Control-Allow-Methods: GET, POST, PUT, DELETE, OPTIONS');
    HTP.P('Access-Control-Allow-Headers: Authorization, Content-Type');
    OWA_UTIL.HTTP_HEADER_CLOSE;
    l_token := :authorization;
    IF l_token IS NOT NULL THEN
        l_pos := INSTR(UPPER(l_token), 'BEARER ');
        IF l_pos > 0 THEN l_token := TRIM(SUBSTR(l_token, l_pos + 7)); END IF;
    END IF;
    PKG_CONTEO_EFECTIVO_LUBRIMEC.ACTUALIZAR(
        p_token => l_token, p_id => TO_NUMBER(:id), p_fecha => :fecha,
        p_valor => TO_NUMBER(:valor), p_cantidad => TO_NUMBER(:cantidad),
        p_cod_moneda => TO_NUMBER(:cod_moneda), p_cod_empresa => TO_NUMBER(:cod_empresa));
END;
~');

  ORDS.DEFINE_PARAMETER(
      p_module_name => 'lubrimec', p_pattern => 'conteo-efectivo/:id', p_method => 'PUT',
      p_name => 'Authorization', p_bind_variable_name => 'authorization',
      p_source_type => 'HEADER', p_param_type => 'STRING', p_access_method => 'IN');

  -- DELETE /conteo-efectivo/:id  -> eliminar
  ORDS.DEFINE_HANDLER(
      p_module_name => 'lubrimec',
      p_pattern     => 'conteo-efectivo/:id',
      p_method      => 'DELETE',
      p_source_type => 'plsql/block',
      p_source      => q'~
DECLARE
    l_token       VARCHAR2(256); l_pos PLS_INTEGER;
    l_query       VARCHAR2(4000); l_cod_empresa VARCHAR2(20);
    FUNCTION get_qs(p_qs IN VARCHAR2, p_key IN VARCHAR2) RETURN VARCHAR2 IS
        l_p PLS_INTEGER; l_e PLS_INTEGER; l_v VARCHAR2(4000);
    BEGIN
        l_p := INSTR('&' || p_qs, '&' || p_key || '=');
        IF l_p = 0 THEN RETURN NULL; END IF;
        l_p := l_p + LENGTH(p_key) + 1;
        l_e := INSTR(p_qs || '&', '&', l_p);
        l_v := SUBSTR(p_qs, l_p, l_e - l_p);
        l_v := REPLACE(l_v, '+', ' ');
        RETURN UTL_URL.UNESCAPE(l_v);
    END;
BEGIN
    OWA_UTIL.MIME_HEADER('application/json', FALSE);
    HTP.P('Access-Control-Allow-Origin: *');
    HTP.P('Access-Control-Allow-Methods: GET, POST, PUT, DELETE, OPTIONS');
    HTP.P('Access-Control-Allow-Headers: Authorization, Content-Type');
    OWA_UTIL.HTTP_HEADER_CLOSE;
    l_token := :authorization;
    IF l_token IS NOT NULL THEN
        l_pos := INSTR(UPPER(l_token), 'BEARER ');
        IF l_pos > 0 THEN l_token := TRIM(SUBSTR(l_token, l_pos + 7)); END IF;
    END IF;
    l_query       := OWA_UTIL.GET_CGI_ENV('QUERY_STRING');
    l_cod_empresa := get_qs(l_query, 'cod_empresa');
    PKG_CONTEO_EFECTIVO_LUBRIMEC.ELIMINAR(
        p_token => l_token, p_id => TO_NUMBER(:id), p_cod_empresa => TO_NUMBER(l_cod_empresa));
END;
~');

  ORDS.DEFINE_PARAMETER(
      p_module_name => 'lubrimec', p_pattern => 'conteo-efectivo/:id', p_method => 'DELETE',
      p_name => 'Authorization', p_bind_variable_name => 'authorization',
      p_source_type => 'HEADER', p_param_type => 'STRING', p_access_method => 'IN');

  ----------------------------------------------------------------------------
  -- /conteo-efectivo/resumen  -> panel de 7 totales de control (solo JOSEG)
  -- Prioridad 1 para que ORDS la matchee antes que /conteo-efectivo/:id
  -- (si cayera en :id, 'resumen' rompe el TO_NUMBER(:id) -> 400).
  ----------------------------------------------------------------------------
  BEGIN
    ORDS.DEFINE_TEMPLATE(
        p_module_name => 'lubrimec',
        p_pattern     => 'conteo-efectivo/resumen',
        p_priority    => 1,
        p_etag_type   => 'HASH',
        p_comments    => NULL);
  EXCEPTION WHEN OTHERS THEN NULL; END;

  ORDS.DEFINE_HANDLER(
      p_module_name => 'lubrimec',
      p_pattern     => 'conteo-efectivo/resumen',
      p_method      => 'GET',
      p_source_type => 'plsql/block',
      p_source      => q'~
DECLARE
    l_token       VARCHAR2(256); l_pos PLS_INTEGER;
    l_query       VARCHAR2(4000); l_cod_empresa VARCHAR2(20);
    l_app_user    VARCHAR2(255); l_fecha VARCHAR2(20);
    FUNCTION get_qs(p_qs IN VARCHAR2, p_key IN VARCHAR2) RETURN VARCHAR2 IS
        l_p PLS_INTEGER; l_e PLS_INTEGER; l_v VARCHAR2(4000);
    BEGIN
        l_p := INSTR('&' || p_qs, '&' || p_key || '=');
        IF l_p = 0 THEN RETURN NULL; END IF;
        l_p := l_p + LENGTH(p_key) + 1;
        l_e := INSTR(p_qs || '&', '&', l_p);
        l_v := SUBSTR(p_qs, l_p, l_e - l_p);
        l_v := REPLACE(l_v, '+', ' ');
        RETURN UTL_URL.UNESCAPE(l_v);
    END;
BEGIN
    OWA_UTIL.MIME_HEADER('application/json', FALSE);
    HTP.P('Access-Control-Allow-Origin: *');
    HTP.P('Access-Control-Allow-Methods: GET, OPTIONS');
    HTP.P('Access-Control-Allow-Headers: Authorization, Content-Type');
    OWA_UTIL.HTTP_HEADER_CLOSE;
    l_token := :authorization;
    IF l_token IS NOT NULL THEN
        l_pos := INSTR(UPPER(l_token), 'BEARER ');
        IF l_pos > 0 THEN l_token := TRIM(SUBSTR(l_token, l_pos + 7)); END IF;
    END IF;
    l_query       := OWA_UTIL.GET_CGI_ENV('QUERY_STRING');
    l_cod_empresa := get_qs(l_query, 'cod_empresa');
    l_app_user    := get_qs(l_query, 'app_user');
    l_fecha       := get_qs(l_query, 'fecha');
    PKG_CONTEO_EFECTIVO_LUBRIMEC.RESUMEN(
        p_token => l_token, p_cod_empresa => TO_NUMBER(l_cod_empresa),
        p_app_user => l_app_user, p_fecha => l_fecha);
END;
~');

  ORDS.DEFINE_PARAMETER(
      p_module_name => 'lubrimec', p_pattern => 'conteo-efectivo/resumen', p_method => 'GET',
      p_name => 'Authorization', p_bind_variable_name => 'authorization',
      p_source_type => 'HEADER', p_param_type => 'STRING', p_access_method => 'IN');

  COMMIT;
EXCEPTION
  WHEN OTHERS THEN
    ROLLBACK;
    RAISE;
END;
/
