--------------------------------------------------------------------------------
-- NUMEROS_VOUCHERS (pagina APEX 71) — paquete CRUD + endpoints ORDS.
-- Ejecutar completo como el esquema JOSEGALVEZ. Requiere PKG_AUTH_LUBRIMEC.
--
-- PK id_voucher GENERATED BY DEFAULT AS IDENTITY (RETURNING). FK id_persona ->
-- personas. La tabla NO tiene cod_empresa; se recibe cod_empresa solo para el JOIN
-- a personas (multiempresa) y para el buscador. Rango numero_desde/hasta,
-- fecha_vencimiento (NOT NULL), porcentaje_descuento (nullable).
-- BUSCAR_PERSONAS alimenta el selector (endpoint personas/buscar).
--
-- === 1) PAQUETE PKG_NUMEROS_VOUCHERS_LUBRIMEC =============================
--------------------------------------------------------------------------------

CREATE OR REPLACE PACKAGE PKG_NUMEROS_VOUCHERS_LUBRIMEC AS

  PROCEDURE LISTAR(p_token IN VARCHAR2, p_cod_empresa IN NUMBER);
  PROCEDURE OBTENER(p_token IN VARCHAR2, p_id IN NUMBER, p_cod_empresa IN NUMBER);
  PROCEDURE INSERTAR(
      p_token IN VARCHAR2, p_id_persona IN NUMBER, p_numero_desde IN NUMBER,
      p_numero_hasta IN NUMBER, p_fecha_vencimiento IN VARCHAR2,
      p_porcentaje_descuento IN NUMBER);
  PROCEDURE ACTUALIZAR(
      p_token IN VARCHAR2, p_id IN NUMBER, p_id_persona IN NUMBER, p_numero_desde IN NUMBER,
      p_numero_hasta IN NUMBER, p_fecha_vencimiento IN VARCHAR2,
      p_porcentaje_descuento IN NUMBER);
  PROCEDURE ELIMINAR(p_token IN VARCHAR2, p_id IN NUMBER);
  PROCEDURE BUSCAR_PERSONAS(p_token IN VARCHAR2, p_cod_empresa IN NUMBER, p_q IN VARCHAR2);

END PKG_NUMEROS_VOUCHERS_LUBRIMEC;
/

CREATE OR REPLACE PACKAGE BODY PKG_NUMEROS_VOUCHERS_LUBRIMEC AS

  PROCEDURE p_error(p_status IN NUMBER, p_reason IN VARCHAR2, p_message IN VARCHAR2) IS
  BEGIN
    OWA_UTIL.STATUS_LINE(p_status, p_reason, FALSE);
    APEX_JSON.OPEN_OBJECT;
    APEX_JSON.WRITE('success', FALSE);
    APEX_JSON.WRITE('message', p_message);
    APEX_JSON.CLOSE_OBJECT;
  END p_error;

  FUNCTION f_usuario(p_token IN VARCHAR2) RETURN VARCHAR2 IS
  BEGIN
    RETURN PKG_AUTH_LUBRIMEC.VALIDAR_TOKEN(p_token);
  END f_usuario;

  --------------------------------------------------------------------------
  -- LISTAR (JOIN a personas para el nombre; cod_empresa solo para el JOIN)
  --------------------------------------------------------------------------
  PROCEDURE LISTAR(p_token IN VARCHAR2, p_cod_empresa IN NUMBER) IS
    l_usuario VARCHAR2(255);
  BEGIN
    l_usuario := f_usuario(p_token);
    IF l_usuario IS NULL THEN
      p_error(401, 'Unauthorized', 'Token invalido o expirado');
      RETURN;
    END IF;

    APEX_JSON.OPEN_OBJECT;
    APEX_JSON.WRITE('success', TRUE);
    APEX_JSON.OPEN_ARRAY('data');
    FOR r IN (
        SELECT v.id_voucher, v.id_persona, v.numero_desde, v.numero_hasta,
               v.fecha_vencimiento, v.porcentaje_descuento,
               NVL(pe.nombre_fantasia, pe.nombre) AS nombre_persona
          FROM numeros_vouchers v
          LEFT JOIN personas pe
                 ON pe.cod_persona = v.id_persona
                AND pe.cod_empresa = p_cod_empresa
         ORDER BY v.id_voucher DESC
    ) LOOP
      APEX_JSON.OPEN_OBJECT;
      APEX_JSON.WRITE('id_voucher', r.id_voucher);
      APEX_JSON.WRITE('id_persona', r.id_persona);
      APEX_JSON.WRITE('numero_desde', r.numero_desde);
      APEX_JSON.WRITE('numero_hasta', r.numero_hasta);
      APEX_JSON.WRITE('fecha_vencimiento', TO_CHAR(r.fecha_vencimiento, 'YYYY-MM-DD'));
      APEX_JSON.WRITE('porcentaje_descuento', r.porcentaje_descuento);
      APEX_JSON.WRITE('nombre_persona', r.nombre_persona);
      APEX_JSON.CLOSE_OBJECT;
    END LOOP;
    APEX_JSON.CLOSE_ARRAY;
    APEX_JSON.CLOSE_OBJECT;
  EXCEPTION
    WHEN OTHERS THEN
      p_error(500, 'Internal Server Error', 'Error: ' || SQLERRM);
  END LISTAR;

  --------------------------------------------------------------------------
  -- OBTENER
  --------------------------------------------------------------------------
  PROCEDURE OBTENER(p_token IN VARCHAR2, p_id IN NUMBER, p_cod_empresa IN NUMBER) IS
    l_usuario   VARCHAR2(255);
    l_persona   numeros_vouchers.id_persona%TYPE;
    l_desde     numeros_vouchers.numero_desde%TYPE;
    l_hasta     numeros_vouchers.numero_hasta%TYPE;
    l_venc      numeros_vouchers.fecha_vencimiento%TYPE;
    l_porc      numeros_vouchers.porcentaje_descuento%TYPE;
    l_nombre    personas.nombre%TYPE;
  BEGIN
    l_usuario := f_usuario(p_token);
    IF l_usuario IS NULL THEN
      p_error(401, 'Unauthorized', 'Token invalido o expirado');
      RETURN;
    END IF;

    BEGIN
      SELECT v.id_persona, v.numero_desde, v.numero_hasta, v.fecha_vencimiento,
             v.porcentaje_descuento, NVL(pe.nombre_fantasia, pe.nombre)
        INTO l_persona, l_desde, l_hasta, l_venc, l_porc, l_nombre
        FROM numeros_vouchers v
        LEFT JOIN personas pe
               ON pe.cod_persona = v.id_persona
              AND pe.cod_empresa = p_cod_empresa
       WHERE v.id_voucher = p_id;
    EXCEPTION
      WHEN NO_DATA_FOUND THEN
        p_error(404, 'Not Found', 'Voucher no encontrado');
        RETURN;
    END;

    APEX_JSON.OPEN_OBJECT;
    APEX_JSON.WRITE('success', TRUE);
    APEX_JSON.OPEN_OBJECT('data');
    APEX_JSON.WRITE('id_voucher', p_id);
    APEX_JSON.WRITE('id_persona', l_persona);
    APEX_JSON.WRITE('numero_desde', l_desde);
    APEX_JSON.WRITE('numero_hasta', l_hasta);
    APEX_JSON.WRITE('fecha_vencimiento', TO_CHAR(l_venc, 'YYYY-MM-DD'));
    APEX_JSON.WRITE('porcentaje_descuento', l_porc);
    APEX_JSON.WRITE('nombre_persona', l_nombre);
    APEX_JSON.CLOSE_OBJECT;
    APEX_JSON.CLOSE_OBJECT;
  EXCEPTION
    WHEN OTHERS THEN
      p_error(500, 'Internal Server Error', 'Error: ' || SQLERRM);
  END OBTENER;

  --------------------------------------------------------------------------
  -- INSERTAR (PK IDENTITY; RETURNING). FK id_persona -> -2291 = 400.
  --------------------------------------------------------------------------
  PROCEDURE INSERTAR(
      p_token IN VARCHAR2, p_id_persona IN NUMBER, p_numero_desde IN NUMBER,
      p_numero_hasta IN NUMBER, p_fecha_vencimiento IN VARCHAR2,
      p_porcentaje_descuento IN NUMBER) IS
    l_usuario VARCHAR2(255);
    l_id      numeros_vouchers.id_voucher%TYPE;
    l_venc    DATE := TO_DATE(p_fecha_vencimiento, 'YYYY-MM-DD');
  BEGIN
    l_usuario := f_usuario(p_token);
    IF l_usuario IS NULL THEN
      p_error(401, 'Unauthorized', 'Token invalido o expirado');
      RETURN;
    END IF;

    IF p_id_persona IS NULL THEN
      p_error(400, 'Bad Request', 'La persona es obligatoria'); RETURN;
    END IF;
    IF p_numero_desde IS NULL THEN
      p_error(400, 'Bad Request', 'El numero desde es obligatorio'); RETURN;
    END IF;
    IF p_numero_hasta IS NULL THEN
      p_error(400, 'Bad Request', 'El numero hasta es obligatorio'); RETURN;
    END IF;
    IF l_venc IS NULL THEN
      p_error(400, 'Bad Request', 'La fecha de vencimiento es obligatoria'); RETURN;
    END IF;

    INSERT INTO numeros_vouchers (
        id_persona, numero_desde, numero_hasta, fecha_vencimiento, porcentaje_descuento)
    VALUES (p_id_persona, p_numero_desde, p_numero_hasta, l_venc, p_porcentaje_descuento)
    RETURNING id_voucher INTO l_id;
    COMMIT;

    OWA_UTIL.STATUS_LINE(201, 'Created', FALSE);
    APEX_JSON.OPEN_OBJECT;
    APEX_JSON.WRITE('success', TRUE);
    APEX_JSON.WRITE('message', 'Voucher creado');
    APEX_JSON.WRITE('id_voucher', l_id);
    APEX_JSON.CLOSE_OBJECT;
  EXCEPTION
    WHEN OTHERS THEN
      ROLLBACK;
      IF SQLCODE = -2291 THEN
        p_error(400, 'Bad Request', 'La persona indicada no existe');
      ELSE
        p_error(500, 'Internal Server Error', 'Error: ' || SQLERRM);
      END IF;
  END INSERTAR;

  --------------------------------------------------------------------------
  -- ACTUALIZAR
  --------------------------------------------------------------------------
  PROCEDURE ACTUALIZAR(
      p_token IN VARCHAR2, p_id IN NUMBER, p_id_persona IN NUMBER, p_numero_desde IN NUMBER,
      p_numero_hasta IN NUMBER, p_fecha_vencimiento IN VARCHAR2,
      p_porcentaje_descuento IN NUMBER) IS
    l_usuario VARCHAR2(255);
    l_venc    DATE := TO_DATE(p_fecha_vencimiento, 'YYYY-MM-DD');
  BEGIN
    l_usuario := f_usuario(p_token);
    IF l_usuario IS NULL THEN
      p_error(401, 'Unauthorized', 'Token invalido o expirado');
      RETURN;
    END IF;

    IF p_id_persona IS NULL THEN
      p_error(400, 'Bad Request', 'La persona es obligatoria'); RETURN;
    END IF;
    IF p_numero_desde IS NULL THEN
      p_error(400, 'Bad Request', 'El numero desde es obligatorio'); RETURN;
    END IF;
    IF p_numero_hasta IS NULL THEN
      p_error(400, 'Bad Request', 'El numero hasta es obligatorio'); RETURN;
    END IF;
    IF l_venc IS NULL THEN
      p_error(400, 'Bad Request', 'La fecha de vencimiento es obligatoria'); RETURN;
    END IF;

    UPDATE numeros_vouchers
       SET id_persona           = p_id_persona,
           numero_desde         = p_numero_desde,
           numero_hasta         = p_numero_hasta,
           fecha_vencimiento    = l_venc,
           porcentaje_descuento = p_porcentaje_descuento
     WHERE id_voucher = p_id;

    IF SQL%ROWCOUNT = 0 THEN
      ROLLBACK;
      p_error(404, 'Not Found', 'Voucher no encontrado');
      RETURN;
    END IF;
    COMMIT;

    APEX_JSON.OPEN_OBJECT;
    APEX_JSON.WRITE('success', TRUE);
    APEX_JSON.WRITE('message', 'Voucher actualizado');
    APEX_JSON.CLOSE_OBJECT;
  EXCEPTION
    WHEN OTHERS THEN
      ROLLBACK;
      IF SQLCODE = -2291 THEN
        p_error(400, 'Bad Request', 'La persona indicada no existe');
      ELSE
        p_error(500, 'Internal Server Error', 'Error: ' || SQLERRM);
      END IF;
  END ACTUALIZAR;

  --------------------------------------------------------------------------
  -- ELIMINAR
  --------------------------------------------------------------------------
  PROCEDURE ELIMINAR(p_token IN VARCHAR2, p_id IN NUMBER) IS
    l_usuario VARCHAR2(255);
  BEGIN
    l_usuario := f_usuario(p_token);
    IF l_usuario IS NULL THEN
      p_error(401, 'Unauthorized', 'Token invalido o expirado');
      RETURN;
    END IF;

    DELETE FROM numeros_vouchers WHERE id_voucher = p_id;

    IF SQL%ROWCOUNT = 0 THEN
      ROLLBACK;
      p_error(404, 'Not Found', 'Voucher no encontrado');
      RETURN;
    END IF;
    COMMIT;

    APEX_JSON.OPEN_OBJECT;
    APEX_JSON.WRITE('success', TRUE);
    APEX_JSON.WRITE('message', 'Voucher eliminado');
    APEX_JSON.CLOSE_OBJECT;
  EXCEPTION
    WHEN OTHERS THEN
      ROLLBACK;
      p_error(500, 'Internal Server Error', 'Error: ' || SQLERRM);
  END ELIMINAR;

  --------------------------------------------------------------------------
  -- BUSCAR_PERSONAS (selector). Hasta 30 personas de la empresa que matcheen
  -- por nombre / nombre_fantasia / ruc / ci / cod_persona.
  --------------------------------------------------------------------------
  PROCEDURE BUSCAR_PERSONAS(p_token IN VARCHAR2, p_cod_empresa IN NUMBER, p_q IN VARCHAR2) IS
    l_usuario VARCHAR2(255);
    l_q       VARCHAR2(400) := '%' || UPPER(TRIM(p_q)) || '%';
  BEGIN
    l_usuario := f_usuario(p_token);
    IF l_usuario IS NULL THEN
      p_error(401, 'Unauthorized', 'Token invalido o expirado');
      RETURN;
    END IF;

    APEX_JSON.OPEN_OBJECT;
    APEX_JSON.WRITE('success', TRUE);
    APEX_JSON.OPEN_ARRAY('data');
    FOR r IN (
        SELECT cod_persona,
               NVL(nombre_fantasia, nombre) AS nombre,
               nro_ruc, nro_ci
          FROM personas
         WHERE cod_empresa = p_cod_empresa
           AND (
                 TRIM(p_q) IS NULL
                 OR UPPER(nombre) LIKE l_q
                 OR UPPER(nombre_fantasia) LIKE l_q
                 OR UPPER(nro_ruc) LIKE l_q
                 OR UPPER(nro_ci) LIKE l_q
                 OR TO_CHAR(cod_persona) LIKE l_q
               )
         ORDER BY NVL(nombre_fantasia, nombre)
         FETCH FIRST 30 ROWS ONLY
    ) LOOP
      APEX_JSON.OPEN_OBJECT;
      APEX_JSON.WRITE('cod_persona', r.cod_persona);
      APEX_JSON.WRITE('nombre', r.nombre);
      APEX_JSON.WRITE('nro_ruc', r.nro_ruc);
      APEX_JSON.WRITE('nro_ci', r.nro_ci);
      APEX_JSON.CLOSE_OBJECT;
    END LOOP;
    APEX_JSON.CLOSE_ARRAY;
    APEX_JSON.CLOSE_OBJECT;
  EXCEPTION
    WHEN OTHERS THEN
      p_error(500, 'Internal Server Error', 'Error: ' || SQLERRM);
  END BUSCAR_PERSONAS;

END PKG_NUMEROS_VOUCHERS_LUBRIMEC;
/

--------------------------------------------------------------------------------
-- === 2) ENDPOINTS ORDS =====================================================
--
--   GET    /lubrimec/numeros-vouchers?cod_empresa=:n     -> listar
--   GET    /lubrimec/numeros-vouchers/:id?cod_empresa=:n -> obtener
--   POST   /lubrimec/numeros-vouchers                    -> insertar
--   PUT    /lubrimec/numeros-vouchers/:id                -> actualizar
--   DELETE /lubrimec/numeros-vouchers/:id                -> eliminar
--   GET    /lubrimec/personas/buscar?cod_empresa=:n&q=:q -> selector de personas
--------------------------------------------------------------------------------

BEGIN
  BEGIN ORDS.DELETE_HANDLER('lubrimec', 'numeros-vouchers', 'GET');        EXCEPTION WHEN OTHERS THEN NULL; END;
  BEGIN ORDS.DELETE_HANDLER('lubrimec', 'numeros-vouchers', 'POST');       EXCEPTION WHEN OTHERS THEN NULL; END;
  BEGIN ORDS.DELETE_HANDLER('lubrimec', 'numeros-vouchers/:id', 'GET');    EXCEPTION WHEN OTHERS THEN NULL; END;
  BEGIN ORDS.DELETE_HANDLER('lubrimec', 'numeros-vouchers/:id', 'PUT');    EXCEPTION WHEN OTHERS THEN NULL; END;
  BEGIN ORDS.DELETE_HANDLER('lubrimec', 'numeros-vouchers/:id', 'DELETE'); EXCEPTION WHEN OTHERS THEN NULL; END;
  BEGIN ORDS.DELETE_HANDLER('lubrimec', 'personas/buscar', 'GET');         EXCEPTION WHEN OTHERS THEN NULL; END;

  ----------------------------------------------------------------------------
  -- Plantilla coleccion: /numeros-vouchers
  ----------------------------------------------------------------------------
  BEGIN
    ORDS.DEFINE_TEMPLATE(
        p_module_name => 'lubrimec',
        p_pattern     => 'numeros-vouchers',
        p_priority    => 0,
        p_etag_type   => 'HASH',
        p_comments    => NULL);
  EXCEPTION WHEN OTHERS THEN NULL; END;

  -- GET /numeros-vouchers?cod_empresa=:n  -> listar
  ORDS.DEFINE_HANDLER(
      p_module_name => 'lubrimec',
      p_pattern     => 'numeros-vouchers',
      p_method      => 'GET',
      p_source_type => 'plsql/block',
      p_source      => q'~
DECLARE
    l_token       VARCHAR2(256); l_pos PLS_INTEGER;
    l_query       VARCHAR2(4000); l_cod_empresa VARCHAR2(20);
    FUNCTION get_qs(p_qs IN VARCHAR2, p_key IN VARCHAR2) RETURN VARCHAR2 IS
        l_p PLS_INTEGER; l_e PLS_INTEGER; l_v VARCHAR2(4000);
    BEGIN
        l_p := INSTR('&' || p_qs, '&' || p_key || '=');
        IF l_p = 0 THEN RETURN NULL; END IF;
        l_p := l_p + LENGTH(p_key) + 1;
        l_e := INSTR(p_qs || '&', '&', l_p);
        l_v := SUBSTR(p_qs, l_p, l_e - l_p);
        l_v := REPLACE(l_v, '+', ' ');
        RETURN UTL_URL.UNESCAPE(l_v);
    END;
BEGIN
    OWA_UTIL.MIME_HEADER('application/json', FALSE);
    HTP.P('Access-Control-Allow-Origin: *');
    HTP.P('Access-Control-Allow-Methods: GET, POST, PUT, DELETE, OPTIONS');
    HTP.P('Access-Control-Allow-Headers: Authorization, Content-Type');
    OWA_UTIL.HTTP_HEADER_CLOSE;
    l_token := :authorization;
    IF l_token IS NOT NULL THEN
        l_pos := INSTR(UPPER(l_token), 'BEARER ');
        IF l_pos > 0 THEN l_token := TRIM(SUBSTR(l_token, l_pos + 7)); END IF;
    END IF;
    l_query       := OWA_UTIL.GET_CGI_ENV('QUERY_STRING');
    l_cod_empresa := get_qs(l_query, 'cod_empresa');
    PKG_NUMEROS_VOUCHERS_LUBRIMEC.LISTAR(p_token => l_token, p_cod_empresa => TO_NUMBER(l_cod_empresa));
END;
~');

  ORDS.DEFINE_PARAMETER(
      p_module_name => 'lubrimec', p_pattern => 'numeros-vouchers', p_method => 'GET',
      p_name => 'Authorization', p_bind_variable_name => 'authorization',
      p_source_type => 'HEADER', p_param_type => 'STRING', p_access_method => 'IN');

  -- POST /numeros-vouchers  -> insertar
  ORDS.DEFINE_HANDLER(
      p_module_name => 'lubrimec',
      p_pattern     => 'numeros-vouchers',
      p_method      => 'POST',
      p_source_type => 'plsql/block',
      p_source      => q'~
DECLARE l_token VARCHAR2(256); l_pos PLS_INTEGER;
BEGIN
    OWA_UTIL.MIME_HEADER('application/json', FALSE);
    HTP.P('Access-Control-Allow-Origin: *');
    HTP.P('Access-Control-Allow-Methods: GET, POST, PUT, DELETE, OPTIONS');
    HTP.P('Access-Control-Allow-Headers: Authorization, Content-Type');
    OWA_UTIL.HTTP_HEADER_CLOSE;
    l_token := :authorization;
    IF l_token IS NOT NULL THEN
        l_pos := INSTR(UPPER(l_token), 'BEARER ');
        IF l_pos > 0 THEN l_token := TRIM(SUBSTR(l_token, l_pos + 7)); END IF;
    END IF;
    PKG_NUMEROS_VOUCHERS_LUBRIMEC.INSERTAR(
        p_token => l_token, p_id_persona => TO_NUMBER(:id_persona),
        p_numero_desde => TO_NUMBER(:numero_desde), p_numero_hasta => TO_NUMBER(:numero_hasta),
        p_fecha_vencimiento => :fecha_vencimiento,
        p_porcentaje_descuento => TO_NUMBER(:porcentaje_descuento));
END;
~');

  ORDS.DEFINE_PARAMETER(
      p_module_name => 'lubrimec', p_pattern => 'numeros-vouchers', p_method => 'POST',
      p_name => 'Authorization', p_bind_variable_name => 'authorization',
      p_source_type => 'HEADER', p_param_type => 'STRING', p_access_method => 'IN');

  ----------------------------------------------------------------------------
  -- Plantilla item: /numeros-vouchers/:id
  ----------------------------------------------------------------------------
  BEGIN
    ORDS.DEFINE_TEMPLATE(
        p_module_name => 'lubrimec',
        p_pattern     => 'numeros-vouchers/:id',
        p_priority    => 0,
        p_etag_type   => 'HASH',
        p_comments    => NULL);
  EXCEPTION WHEN OTHERS THEN NULL; END;

  -- GET /numeros-vouchers/:id  -> obtener
  ORDS.DEFINE_HANDLER(
      p_module_name => 'lubrimec',
      p_pattern     => 'numeros-vouchers/:id',
      p_method      => 'GET',
      p_source_type => 'plsql/block',
      p_source      => q'~
DECLARE
    l_token       VARCHAR2(256); l_pos PLS_INTEGER;
    l_query       VARCHAR2(4000); l_cod_empresa VARCHAR2(20);
    FUNCTION get_qs(p_qs IN VARCHAR2, p_key IN VARCHAR2) RETURN VARCHAR2 IS
        l_p PLS_INTEGER; l_e PLS_INTEGER; l_v VARCHAR2(4000);
    BEGIN
        l_p := INSTR('&' || p_qs, '&' || p_key || '=');
        IF l_p = 0 THEN RETURN NULL; END IF;
        l_p := l_p + LENGTH(p_key) + 1;
        l_e := INSTR(p_qs || '&', '&', l_p);
        l_v := SUBSTR(p_qs, l_p, l_e - l_p);
        l_v := REPLACE(l_v, '+', ' ');
        RETURN UTL_URL.UNESCAPE(l_v);
    END;
BEGIN
    OWA_UTIL.MIME_HEADER('application/json', FALSE);
    HTP.P('Access-Control-Allow-Origin: *');
    HTP.P('Access-Control-Allow-Methods: GET, POST, PUT, DELETE, OPTIONS');
    HTP.P('Access-Control-Allow-Headers: Authorization, Content-Type');
    OWA_UTIL.HTTP_HEADER_CLOSE;
    l_token := :authorization;
    IF l_token IS NOT NULL THEN
        l_pos := INSTR(UPPER(l_token), 'BEARER ');
        IF l_pos > 0 THEN l_token := TRIM(SUBSTR(l_token, l_pos + 7)); END IF;
    END IF;
    l_query       := OWA_UTIL.GET_CGI_ENV('QUERY_STRING');
    l_cod_empresa := get_qs(l_query, 'cod_empresa');
    PKG_NUMEROS_VOUCHERS_LUBRIMEC.OBTENER(
        p_token => l_token, p_id => TO_NUMBER(:id), p_cod_empresa => TO_NUMBER(l_cod_empresa));
END;
~');

  ORDS.DEFINE_PARAMETER(
      p_module_name => 'lubrimec', p_pattern => 'numeros-vouchers/:id', p_method => 'GET',
      p_name => 'Authorization', p_bind_variable_name => 'authorization',
      p_source_type => 'HEADER', p_param_type => 'STRING', p_access_method => 'IN');

  -- PUT /numeros-vouchers/:id  -> actualizar
  ORDS.DEFINE_HANDLER(
      p_module_name => 'lubrimec',
      p_pattern     => 'numeros-vouchers/:id',
      p_method      => 'PUT',
      p_source_type => 'plsql/block',
      p_source      => q'~
DECLARE l_token VARCHAR2(256); l_pos PLS_INTEGER;
BEGIN
    OWA_UTIL.MIME_HEADER('application/json', FALSE);
    HTP.P('Access-Control-Allow-Origin: *');
    HTP.P('Access-Control-Allow-Methods: GET, POST, PUT, DELETE, OPTIONS');
    HTP.P('Access-Control-Allow-Headers: Authorization, Content-Type');
    OWA_UTIL.HTTP_HEADER_CLOSE;
    l_token := :authorization;
    IF l_token IS NOT NULL THEN
        l_pos := INSTR(UPPER(l_token), 'BEARER ');
        IF l_pos > 0 THEN l_token := TRIM(SUBSTR(l_token, l_pos + 7)); END IF;
    END IF;
    PKG_NUMEROS_VOUCHERS_LUBRIMEC.ACTUALIZAR(
        p_token => l_token, p_id => TO_NUMBER(:id), p_id_persona => TO_NUMBER(:id_persona),
        p_numero_desde => TO_NUMBER(:numero_desde), p_numero_hasta => TO_NUMBER(:numero_hasta),
        p_fecha_vencimiento => :fecha_vencimiento,
        p_porcentaje_descuento => TO_NUMBER(:porcentaje_descuento));
END;
~');

  ORDS.DEFINE_PARAMETER(
      p_module_name => 'lubrimec', p_pattern => 'numeros-vouchers/:id', p_method => 'PUT',
      p_name => 'Authorization', p_bind_variable_name => 'authorization',
      p_source_type => 'HEADER', p_param_type => 'STRING', p_access_method => 'IN');

  -- DELETE /numeros-vouchers/:id  -> eliminar
  ORDS.DEFINE_HANDLER(
      p_module_name => 'lubrimec',
      p_pattern     => 'numeros-vouchers/:id',
      p_method      => 'DELETE',
      p_source_type => 'plsql/block',
      p_source      => q'~
DECLARE l_token VARCHAR2(256); l_pos PLS_INTEGER;
BEGIN
    OWA_UTIL.MIME_HEADER('application/json', FALSE);
    HTP.P('Access-Control-Allow-Origin: *');
    HTP.P('Access-Control-Allow-Methods: GET, POST, PUT, DELETE, OPTIONS');
    HTP.P('Access-Control-Allow-Headers: Authorization, Content-Type');
    OWA_UTIL.HTTP_HEADER_CLOSE;
    l_token := :authorization;
    IF l_token IS NOT NULL THEN
        l_pos := INSTR(UPPER(l_token), 'BEARER ');
        IF l_pos > 0 THEN l_token := TRIM(SUBSTR(l_token, l_pos + 7)); END IF;
    END IF;
    PKG_NUMEROS_VOUCHERS_LUBRIMEC.ELIMINAR(p_token => l_token, p_id => TO_NUMBER(:id));
END;
~');

  ORDS.DEFINE_PARAMETER(
      p_module_name => 'lubrimec', p_pattern => 'numeros-vouchers/:id', p_method => 'DELETE',
      p_name => 'Authorization', p_bind_variable_name => 'authorization',
      p_source_type => 'HEADER', p_param_type => 'STRING', p_access_method => 'IN');

  ----------------------------------------------------------------------------
  -- /personas/buscar  -> selector de personas del formulario
  ----------------------------------------------------------------------------
  BEGIN
    ORDS.DEFINE_TEMPLATE(
        p_module_name => 'lubrimec',
        p_pattern     => 'personas/buscar',
        p_priority    => 0,
        p_etag_type   => 'HASH',
        p_comments    => NULL);
  EXCEPTION WHEN OTHERS THEN NULL; END;

  ORDS.DEFINE_HANDLER(
      p_module_name => 'lubrimec',
      p_pattern     => 'personas/buscar',
      p_method      => 'GET',
      p_source_type => 'plsql/block',
      p_source      => q'~
DECLARE
    l_token       VARCHAR2(256); l_pos PLS_INTEGER;
    l_query       VARCHAR2(4000); l_cod_empresa VARCHAR2(20); l_q VARCHAR2(4000);
    FUNCTION get_qs(p_qs IN VARCHAR2, p_key IN VARCHAR2) RETURN VARCHAR2 IS
        l_p PLS_INTEGER; l_e PLS_INTEGER; l_v VARCHAR2(4000);
    BEGIN
        l_p := INSTR('&' || p_qs, '&' || p_key || '=');
        IF l_p = 0 THEN RETURN NULL; END IF;
        l_p := l_p + LENGTH(p_key) + 1;
        l_e := INSTR(p_qs || '&', '&', l_p);
        l_v := SUBSTR(p_qs, l_p, l_e - l_p);
        l_v := REPLACE(l_v, '+', ' ');
        RETURN UTL_URL.UNESCAPE(l_v);
    END;
BEGIN
    OWA_UTIL.MIME_HEADER('application/json', FALSE);
    HTP.P('Access-Control-Allow-Origin: *');
    HTP.P('Access-Control-Allow-Methods: GET, OPTIONS');
    HTP.P('Access-Control-Allow-Headers: Authorization, Content-Type');
    OWA_UTIL.HTTP_HEADER_CLOSE;
    l_token := :authorization;
    IF l_token IS NOT NULL THEN
        l_pos := INSTR(UPPER(l_token), 'BEARER ');
        IF l_pos > 0 THEN l_token := TRIM(SUBSTR(l_token, l_pos + 7)); END IF;
    END IF;
    l_query       := OWA_UTIL.GET_CGI_ENV('QUERY_STRING');
    l_cod_empresa := get_qs(l_query, 'cod_empresa');
    l_q           := get_qs(l_query, 'q');
    PKG_NUMEROS_VOUCHERS_LUBRIMEC.BUSCAR_PERSONAS(
        p_token => l_token, p_cod_empresa => TO_NUMBER(l_cod_empresa), p_q => l_q);
END;
~');

  ORDS.DEFINE_PARAMETER(
      p_module_name => 'lubrimec', p_pattern => 'personas/buscar', p_method => 'GET',
      p_name => 'Authorization', p_bind_variable_name => 'authorization',
      p_source_type => 'HEADER', p_param_type => 'STRING', p_access_method => 'IN');

  COMMIT;
EXCEPTION
  WHEN OTHERS THEN
    ROLLBACK;
    RAISE;
END;
/
