--------------------------------------------------------------------------------
-- PRECIOS_VENTAS (pagina APEX 34) — paquete CRUD + endpoints ORDS.
-- Ejecutar completo como el esquema JOSEGALVEZ. Requiere PKG_AUTH_LUBRIMEC.
--
-- PK id_precio GENERATED BY DEFAULT ON NULL AS IDENTITY (no se pasa en el INSERT).
-- NOT NULL: id_articulo, fecha, precio_venta, cod_empresa.
-- Opcionales: porc_recargo, precio_compra, nro_linea, id_factura (FK a
-- COMPRAS_CABECERA, factura de compra que origino el precio; sin selector de
-- linea real, nro_linea es un numero libre que ingresa el usuario).
--
-- TRIGGERS EN LA TABLA (viven en la BD, no se tocan aqui):
--   TR_INSERT_FECHA: BEFORE INSERT fija fecha = SYSTIMESTAMP (el INSERT del
--     paquete NO debe mandar fecha; el trigger la sobreescribe igual).
--   TRG_PRECIOS_VENTAS_AIU: AFTER INSERT actualiza ARTICULOS.precio_venta y
--     costo_ultima_compra con el precio recien insertado (asume que el ultimo
--     id_precio de un articulo es su precio vigente).
--
-- GOTCHA (por eso el CRUD completo pisa el trigger a mano en ACTUALIZAR/
-- ELIMINAR): el trigger es SOLO AFTER INSERT. Si se edita o borra el registro
-- que resulta ser el MAS RECIENTE de un articulo, ARTICULOS.precio_venta
-- queda desincronizado del historial porque nadie vuelve a calcularlo. Para
-- evitarlo, ACTUALIZAR y ELIMINAR, cuando tocan el precio vigente (el de
-- mayor id_precio para ese articulo+empresa), recalculan a mano el precio
-- vigente resultante y actualizan ARTICULOS.
--
-- === 1) PAQUETE PKG_PRECIOS_VENTAS_LUBRIMEC ================================
--------------------------------------------------------------------------------

CREATE OR REPLACE PACKAGE PKG_PRECIOS_VENTAS_LUBRIMEC AS

  PROCEDURE LISTAR(p_token IN VARCHAR2, p_cod_empresa IN NUMBER, p_id_articulo IN NUMBER DEFAULT NULL);
  PROCEDURE OBTENER(p_token IN VARCHAR2, p_id_precio IN NUMBER, p_cod_empresa IN NUMBER);
  -- Replica el DA "DATOS" + "precio_venta_anterior" + "CALCULO" de la pagina
  -- APEX 35: al elegir un articulo (opcionalmente ligado a una factura de
  -- compra) devuelve los valores sugeridos para el formulario.
  PROCEDURE SUGERIR(
      p_token IN VARCHAR2, p_cod_empresa IN NUMBER,
      p_id_factura IN NUMBER, p_id_articulo IN NUMBER);
  -- LOV cascada de articulos de la pagina 35 (P35_ID_ARTICULO): si hay factura,
  -- los articulos INACTIVOS (es_activo='N') de su COMPRAS_DETALLE aun sin precio
  -- cargado; si no, todos los articulos inactivos. Lista completa, filtro en el front.
  PROCEDURE ARTICULOS_FACTURA(
      p_token IN VARCHAR2, p_cod_empresa IN NUMBER, p_id_factura IN NUMBER);
  -- LOV de facturas de compra de la pagina 35 (P35_ID_FACTURA, LOV compartida
  -- COMPRAS_CABECERA.ID_FACTURA): solo facturas con lineas PENDIENTES de cargar
  -- precio: tip_comprobante <> 'AJS', alguna linea con precio<>0 sin registro en
  -- PRECIOS_VENTAS (por factura+nro_linea) y cuyo articulo este inactivo
  -- (es_activo='N'). Lista completa, filtro en el front.
  PROCEDURE BUSCAR_COMPRAS(p_token IN VARCHAR2, p_cod_empresa IN NUMBER);
  PROCEDURE INSERTAR(
      p_token IN VARCHAR2, p_id_articulo IN NUMBER, p_porc_recargo IN NUMBER,
      p_precio_compra IN NUMBER, p_precio_venta IN NUMBER, p_cod_empresa IN NUMBER,
      p_nro_linea IN NUMBER, p_id_factura IN NUMBER);
  PROCEDURE ACTUALIZAR(
      p_token IN VARCHAR2, p_id_precio IN NUMBER, p_id_articulo IN NUMBER,
      p_porc_recargo IN NUMBER, p_precio_compra IN NUMBER, p_precio_venta IN NUMBER,
      p_cod_empresa IN NUMBER, p_nro_linea IN NUMBER, p_id_factura IN NUMBER);
  PROCEDURE ELIMINAR(p_token IN VARCHAR2, p_id_precio IN NUMBER, p_cod_empresa IN NUMBER);

END PKG_PRECIOS_VENTAS_LUBRIMEC;
/

CREATE OR REPLACE PACKAGE BODY PKG_PRECIOS_VENTAS_LUBRIMEC AS

  PROCEDURE p_error(p_status IN NUMBER, p_reason IN VARCHAR2, p_message IN VARCHAR2) IS
  BEGIN
    OWA_UTIL.STATUS_LINE(p_status, p_reason, FALSE);
    APEX_JSON.OPEN_OBJECT;
    APEX_JSON.WRITE('success', FALSE);
    APEX_JSON.WRITE('message', p_message);
    APEX_JSON.CLOSE_OBJECT;
  END p_error;

  FUNCTION f_usuario(p_token IN VARCHAR2) RETURN VARCHAR2 IS
  BEGIN
    RETURN PKG_AUTH_LUBRIMEC.VALIDAR_TOKEN(p_token);
  END f_usuario;

  -- Resincroniza ARTICULOS con el precio vigente (mayor id_precio) de un
  -- articulo, o lo deja en NULL de precio_venta si no queda ningun registro.
  -- Se llama tras ACTUALIZAR/ELIMINAR cuando pudieron afectar el precio vigente.
  PROCEDURE p_resincronizar_articulo(p_cod_empresa IN NUMBER, p_id_articulo IN NUMBER) IS
    l_precio_compra precios_ventas.precio_compra%TYPE;
    l_precio_venta  precios_ventas.precio_venta%TYPE;
  BEGIN
    BEGIN
      SELECT precio_compra, precio_venta
        INTO l_precio_compra, l_precio_venta
        FROM (
          SELECT precio_compra, precio_venta
            FROM precios_ventas
           WHERE cod_empresa = p_cod_empresa
             AND id_articulo = p_id_articulo
           ORDER BY id_precio DESC
        )
       WHERE ROWNUM = 1;

      UPDATE articulos
         SET costo_ultima_compra = l_precio_compra,
             precio_venta        = l_precio_venta
       WHERE cod_empresa = p_cod_empresa
         AND id_articulo = p_id_articulo;
    EXCEPTION
      WHEN NO_DATA_FOUND THEN
        NULL; -- sin precios restantes: se deja el ultimo valor conocido en articulos
    END;
  END p_resincronizar_articulo;

  --------------------------------------------------------------------------
  -- LISTAR (historial de precios de la empresa; p_id_articulo opcional filtra)
  --------------------------------------------------------------------------
  PROCEDURE LISTAR(p_token IN VARCHAR2, p_cod_empresa IN NUMBER, p_id_articulo IN NUMBER DEFAULT NULL) IS
    l_usuario VARCHAR2(255);
  BEGIN
    l_usuario := f_usuario(p_token);
    IF l_usuario IS NULL THEN
      p_error(401, 'Unauthorized', 'Token invalido o expirado');
      RETURN;
    END IF;

    APEX_JSON.OPEN_OBJECT;
    APEX_JSON.WRITE('success', TRUE);
    APEX_JSON.OPEN_ARRAY('data');
    -- Mismos JOINs/columnas que el IR de la pagina 34 (rubro, marca, oem, margen)
    FOR r IN (
        SELECT p.id_precio, p.id_articulo, ar.descripcion AS descripcion_articulo,
               p.porc_recargo,
               TO_CHAR(p.fecha, 'YYYY-MM-DD"T"HH24:MI:SS') fecha,
               p.precio_compra, p.precio_venta, p.cod_empresa,
               p.nro_linea, p.id_factura,
               CASE WHEN NVL(p.precio_compra, 0) <> 0
                    THEN ((p.precio_venta - p.precio_compra) / p.precio_compra) * 100
               END AS margen,
               ru.descripcion AS rubro,
               ma.descripcion AS marca,
               ar.codigo_oem
          FROM precios_ventas p
          LEFT JOIN articulos ar ON ar.id_articulo = p.id_articulo
                                 AND ar.cod_empresa = p.cod_empresa
          LEFT JOIN rubros ru ON ru.id_rubro = ar.id_rubro
                              AND ru.cod_empresa = ar.cod_empresa
          LEFT JOIN marcas ma ON ma.id_marca = ar.id_marca
                              AND ma.cod_empresa = ar.cod_empresa
         WHERE p.cod_empresa = p_cod_empresa
           AND (p_id_articulo IS NULL OR p.id_articulo = p_id_articulo)
         ORDER BY p.id_precio DESC
    ) LOOP
      APEX_JSON.OPEN_OBJECT;
      APEX_JSON.WRITE('id_precio', r.id_precio);
      APEX_JSON.WRITE('id_articulo', r.id_articulo);
      APEX_JSON.WRITE('descripcion_articulo', r.descripcion_articulo);
      APEX_JSON.WRITE('porc_recargo', r.porc_recargo);
      APEX_JSON.WRITE('fecha', r.fecha);
      APEX_JSON.WRITE('precio_compra', r.precio_compra);
      APEX_JSON.WRITE('precio_venta', r.precio_venta);
      APEX_JSON.WRITE('cod_empresa', r.cod_empresa);
      APEX_JSON.WRITE('nro_linea', r.nro_linea);
      APEX_JSON.WRITE('id_factura', r.id_factura);
      APEX_JSON.WRITE('margen', r.margen);
      APEX_JSON.WRITE('rubro', r.rubro);
      APEX_JSON.WRITE('marca', r.marca);
      APEX_JSON.WRITE('codigo_oem', r.codigo_oem);
      APEX_JSON.CLOSE_OBJECT;
    END LOOP;
    APEX_JSON.CLOSE_ARRAY;
    APEX_JSON.CLOSE_OBJECT;
  EXCEPTION
    WHEN OTHERS THEN
      p_error(500, 'Internal Server Error', 'Error: ' || SQLERRM);
  END LISTAR;

  --------------------------------------------------------------------------
  -- OBTENER
  --------------------------------------------------------------------------
  PROCEDURE OBTENER(p_token IN VARCHAR2, p_id_precio IN NUMBER, p_cod_empresa IN NUMBER) IS
    l_usuario VARCHAR2(255);
    r         precios_ventas%ROWTYPE;
    l_desc    articulos.descripcion%TYPE;
  BEGIN
    l_usuario := f_usuario(p_token);
    IF l_usuario IS NULL THEN
      p_error(401, 'Unauthorized', 'Token invalido o expirado');
      RETURN;
    END IF;

    BEGIN
      SELECT * INTO r
        FROM precios_ventas
       WHERE id_precio = p_id_precio
         AND cod_empresa = p_cod_empresa;
    EXCEPTION
      WHEN NO_DATA_FOUND THEN
        p_error(404, 'Not Found', 'Precio no encontrado');
        RETURN;
    END;

    BEGIN
      SELECT descripcion INTO l_desc FROM articulos
       WHERE id_articulo = r.id_articulo AND cod_empresa = r.cod_empresa;
    EXCEPTION WHEN NO_DATA_FOUND THEN l_desc := NULL; END;

    APEX_JSON.OPEN_OBJECT;
    APEX_JSON.WRITE('success', TRUE);
    APEX_JSON.OPEN_OBJECT('data');
    APEX_JSON.WRITE('id_precio', r.id_precio);
    APEX_JSON.WRITE('id_articulo', r.id_articulo);
    APEX_JSON.WRITE('descripcion_articulo', l_desc);
    APEX_JSON.WRITE('porc_recargo', r.porc_recargo);
    APEX_JSON.WRITE('fecha', TO_CHAR(r.fecha, 'YYYY-MM-DD"T"HH24:MI:SS'));
    APEX_JSON.WRITE('precio_compra', r.precio_compra);
    APEX_JSON.WRITE('precio_venta', r.precio_venta);
    APEX_JSON.WRITE('cod_empresa', r.cod_empresa);
    APEX_JSON.WRITE('nro_linea', r.nro_linea);
    APEX_JSON.WRITE('id_factura', r.id_factura);
    APEX_JSON.CLOSE_OBJECT;
    APEX_JSON.CLOSE_OBJECT;
  EXCEPTION
    WHEN OTHERS THEN
      p_error(500, 'Internal Server Error', 'Error: ' || SQLERRM);
  END OBTENER;

  --------------------------------------------------------------------------
  -- SUGERIR (DA "DATOS" + "precio_venta_anterior" + "CALCULO" de la pag 35).
  -- Al elegir un articulo (con o sin factura de compra):
  --   precio_compra, nro_linea, porc_recargo (del rubro), precio_venta sugerido
  --   (recargo sobre compra + delivery prorrateado, redondeo hacia arriba al
  --   millar) y precio_venta_anterior (pkg_ventas.fn_precio_venta).
  --------------------------------------------------------------------------
  PROCEDURE SUGERIR(
      p_token IN VARCHAR2, p_cod_empresa IN NUMBER,
      p_id_factura IN NUMBER, p_id_articulo IN NUMBER) IS
    l_usuario       VARCHAR2(255);
    l_precio_compra NUMBER;
    l_nro_linea     NUMBER;
    l_porc_recargo  NUMBER;
    l_precio_venta  NUMBER;
    l_cant          NUMBER := 0;   -- cantidad total de la factura (para prorratear)
    l_delivery      NUMBER := 0;   -- costo_delivery de la factura
    l_anterior      NUMBER;
  BEGIN
    l_usuario := f_usuario(p_token);
    IF l_usuario IS NULL THEN
      p_error(401, 'Unauthorized', 'Token invalido o expirado');
      RETURN;
    END IF;

    -- Precio de venta anterior (vigente) del articulo. Si la funcion falla o
    -- devuelve NULL, cae al precio_venta de ARTICULOS (el trigger
    -- TRG_PRECIOS_VENTAS_AIU lo mantiene como precio vigente).
    BEGIN
      l_anterior := PKG_VENTAS.FN_PRECIO_VENTA(p_cod_empresa, p_id_articulo);
    EXCEPTION WHEN OTHERS THEN l_anterior := NULL; END;
    IF l_anterior IS NULL THEN
      BEGIN
        SELECT precio_venta INTO l_anterior
          FROM articulos
         WHERE cod_empresa = p_cod_empresa AND id_articulo = p_id_articulo;
      EXCEPTION WHEN OTHERS THEN l_anterior := NULL; END;
    END IF;

    -- Delivery de la factura y cantidad total (solo si hay factura)
    IF p_id_factura IS NOT NULL THEN
      BEGIN
        SELECT NVL(costo_delivery, 0) INTO l_delivery
          FROM compras_cabecera
         WHERE cod_empresa = p_cod_empresa AND id_factura = p_id_factura;
      EXCEPTION WHEN OTHERS THEN l_delivery := 0; END;

      BEGIN
        SELECT SUM(NVL(cantidad, 0)) INTO l_cant
          FROM compras_detalle
         WHERE cod_empresa = p_cod_empresa AND id_factura = p_id_factura;
      EXCEPTION WHEN OTHERS THEN l_cant := 0; END;
    END IF;

    -- Datos de la linea de compra + recargo del rubro (misma query del DA "DATOS")
    BEGIN
      SELECT d.precio, d.nro_linea, ru.porc_recargo
        INTO l_precio_compra, l_nro_linea, l_porc_recargo
        FROM compras_detalle d
        JOIN articulos ar ON ar.cod_empresa = d.cod_empresa
                          AND ar.id_articulo = d.id_articulo
        JOIN rubros ru ON ru.cod_empresa = ar.cod_empresa
                       AND ru.id_rubro = ar.id_rubro
       WHERE d.cod_empresa = p_cod_empresa
         AND (d.id_factura = p_id_factura OR p_id_factura IS NULL)
         AND d.id_articulo = p_id_articulo
         AND NVL(d.precio, 0) <> 0
         AND ROWNUM = 1;
    EXCEPTION
      WHEN NO_DATA_FOUND THEN
        -- Sin linea de compra: recargo del rubro del articulo, sin precio de compra
        l_precio_compra := NULL;
        l_nro_linea     := NULL;
        BEGIN
          SELECT ru.porc_recargo INTO l_porc_recargo
            FROM articulos ar
            JOIN rubros ru ON ru.cod_empresa = ar.cod_empresa
                           AND ru.id_rubro = ar.id_rubro
           WHERE ar.cod_empresa = p_cod_empresa AND ar.id_articulo = p_id_articulo;
        EXCEPTION WHEN OTHERS THEN l_porc_recargo := NULL; END;
    END;

    -- precio_venta sugerido: base = precio_compra + delivery prorrateado;
    -- venta = CEIL((base + base*recargo/100) / 1000) * 1000
    IF l_precio_compra IS NOT NULL AND l_porc_recargo IS NOT NULL THEN
      DECLARE
        l_base NUMBER;
      BEGIN
        l_base := NVL(l_precio_compra, 0)
                  + CASE WHEN l_cant > 0 AND l_delivery > 0
                         THEN l_delivery / l_cant ELSE 0 END;
        l_precio_venta := CEIL(((l_porc_recargo / 100) * l_base + l_base) / 1000) * 1000;
      END;
    END IF;

    APEX_JSON.OPEN_OBJECT;
    APEX_JSON.WRITE('success', TRUE);
    APEX_JSON.OPEN_OBJECT('data');
    APEX_JSON.WRITE('precio_compra', l_precio_compra);
    APEX_JSON.WRITE('nro_linea', l_nro_linea);
    APEX_JSON.WRITE('porc_recargo', l_porc_recargo);
    APEX_JSON.WRITE('precio_venta', l_precio_venta);
    APEX_JSON.WRITE('precio_venta_anterior', l_anterior);
    APEX_JSON.CLOSE_OBJECT;
    APEX_JSON.CLOSE_OBJECT;
  EXCEPTION
    WHEN OTHERS THEN
      p_error(500, 'Internal Server Error', 'Error: ' || SQLERRM);
  END SUGERIR;

  --------------------------------------------------------------------------
  -- ARTICULOS_FACTURA (LOV de P35_ID_ARTICULO, replica exacta del APEX).
  -- Con factura: articulos INACTIVOS (es_activo='N') de su COMPRAS_DETALLE
  -- (precio<>0) que aun no tengan precio cargado para esa linea. Sin factura:
  -- todos los articulos inactivos. Lista completa (sin q ni tope): filtra el front.
  --------------------------------------------------------------------------
  PROCEDURE ARTICULOS_FACTURA(
      p_token IN VARCHAR2, p_cod_empresa IN NUMBER, p_id_factura IN NUMBER) IS
    l_usuario VARCHAR2(255);
  BEGIN
    l_usuario := f_usuario(p_token);
    IF l_usuario IS NULL THEN
      p_error(401, 'Unauthorized', 'Token invalido o expirado');
      RETURN;
    END IF;

    APEX_JSON.OPEN_OBJECT;
    APEX_JSON.WRITE('success', TRUE);
    APEX_JSON.OPEN_ARRAY('data');
    FOR r IN (
        SELECT b.id_articulo, b.descripcion, b.codigo_oem
          FROM compras_detalle a
          JOIN articulos b ON a.cod_empresa = b.cod_empresa
                          AND a.id_articulo = b.id_articulo
         WHERE p_id_factura IS NOT NULL
           AND a.cod_empresa = p_cod_empresa
           AND a.id_factura = p_id_factura
           AND NVL(a.precio, 0) <> 0
           AND NVL(b.es_activo, 'S') = 'N'
           AND NOT EXISTS (
                 SELECT 1 FROM precios_ventas c
                  WHERE a.cod_empresa = c.cod_empresa
                    AND a.id_factura = c.id_factura
                    AND a.nro_linea = c.nro_linea)
        UNION ALL
        SELECT a.id_articulo, a.descripcion, a.codigo_oem
          FROM articulos a
         WHERE p_id_factura IS NULL
           AND a.cod_empresa = p_cod_empresa
           AND NVL(a.es_activo, 'S') = 'N'
        ORDER BY 2
    ) LOOP
      APEX_JSON.OPEN_OBJECT;
      APEX_JSON.WRITE('id_articulo', r.id_articulo);
      APEX_JSON.WRITE('descripcion', r.descripcion);
      APEX_JSON.WRITE('codigo_oem', r.codigo_oem);
      APEX_JSON.CLOSE_OBJECT;
    END LOOP;
    APEX_JSON.CLOSE_ARRAY;
    APEX_JSON.CLOSE_OBJECT;
  EXCEPTION
    WHEN OTHERS THEN
      p_error(500, 'Internal Server Error', 'Error: ' || SQLERRM);
  END ARTICULOS_FACTURA;

  --------------------------------------------------------------------------
  -- BUSCAR_COMPRAS (LOV de P35_ID_FACTURA, replica de la LOV compartida
  -- COMPRAS_CABECERA.ID_FACTURA del APEX): solo facturas con lineas
  -- PENDIENTES de cargar precio — no AJS, linea con precio<>0 sin registro
  -- en PRECIOS_VENTAS (factura+nro_linea) y articulo inactivo (es_activo='N').
  -- Lista completa: filtra el front.
  --------------------------------------------------------------------------
  PROCEDURE BUSCAR_COMPRAS(p_token IN VARCHAR2, p_cod_empresa IN NUMBER) IS
    l_usuario VARCHAR2(255);
  BEGIN
    l_usuario := f_usuario(p_token);
    IF l_usuario IS NULL THEN
      p_error(401, 'Unauthorized', 'Token invalido o expirado');
      RETURN;
    END IF;

    APEX_JSON.OPEN_OBJECT;
    APEX_JSON.WRITE('success', TRUE);
    APEX_JSON.OPEN_ARRAY('data');
    FOR r IN (
        SELECT cc.id_factura, cc.nro_comprobante, cc.ser_timbrado, cc.tip_comprobante,
               cc.fec_comprobante,
               NVL(pe.nombre_fantasia, pe.nombre) AS nombre_proveedor
          FROM compras_cabecera cc
          LEFT JOIN personas pe
                 ON pe.cod_persona = cc.cod_persona
                AND pe.cod_empresa = cc.cod_empresa
         WHERE cc.cod_empresa = p_cod_empresa
           AND cc.tip_comprobante NOT IN ('AJS') -- ajuste de stock
           AND EXISTS (
                 SELECT 1
                   FROM compras_detalle a
                  WHERE a.cod_empresa = cc.cod_empresa
                    AND a.id_factura = cc.id_factura
                    AND NVL(a.precio, 0) <> 0
                    AND NOT EXISTS (
                          SELECT 1 FROM precios_ventas c
                           WHERE c.cod_empresa = a.cod_empresa
                             AND c.id_factura = a.id_factura
                             AND c.nro_linea = a.nro_linea)
                    AND EXISTS (
                          SELECT 1 FROM articulos ar
                           WHERE ar.cod_empresa = a.cod_empresa
                             AND ar.id_articulo = a.id_articulo
                             AND NVL(ar.es_activo, 'S') = 'N'))
         ORDER BY cc.id_factura DESC
    ) LOOP
      APEX_JSON.OPEN_OBJECT;
      APEX_JSON.WRITE('id_factura', r.id_factura);
      APEX_JSON.WRITE('nro_comprobante', r.nro_comprobante);
      APEX_JSON.WRITE('ser_timbrado', r.ser_timbrado);
      APEX_JSON.WRITE('tip_comprobante', r.tip_comprobante);
      APEX_JSON.WRITE('fec_comprobante', TO_CHAR(r.fec_comprobante, 'YYYY-MM-DD'));
      APEX_JSON.WRITE('nombre_proveedor', r.nombre_proveedor);
      APEX_JSON.CLOSE_OBJECT;
    END LOOP;
    APEX_JSON.CLOSE_ARRAY;
    APEX_JSON.CLOSE_OBJECT;
  EXCEPTION
    WHEN OTHERS THEN
      p_error(500, 'Internal Server Error', 'Error: ' || SQLERRM);
  END BUSCAR_COMPRAS;

  --------------------------------------------------------------------------
  -- INSERTAR (id por IDENTITY; fecha la fija el trigger TR_INSERT_FECHA;
  -- el trigger TRG_PRECIOS_VENTAS_AIU sincroniza ARTICULOS solo)
  --------------------------------------------------------------------------
  PROCEDURE INSERTAR(
      p_token IN VARCHAR2, p_id_articulo IN NUMBER, p_porc_recargo IN NUMBER,
      p_precio_compra IN NUMBER, p_precio_venta IN NUMBER, p_cod_empresa IN NUMBER,
      p_nro_linea IN NUMBER, p_id_factura IN NUMBER) IS
    l_usuario  VARCHAR2(255);
    l_id_precio precios_ventas.id_precio%TYPE;
  BEGIN
    l_usuario := f_usuario(p_token);
    IF l_usuario IS NULL THEN
      p_error(401, 'Unauthorized', 'Token invalido o expirado');
      RETURN;
    END IF;

    IF p_id_articulo IS NULL THEN
      p_error(400, 'Bad Request', 'El articulo es obligatorio'); RETURN;
    END IF;
    IF p_precio_venta IS NULL THEN
      p_error(400, 'Bad Request', 'El precio de venta es obligatorio'); RETURN;
    END IF;
    IF p_cod_empresa IS NULL THEN
      p_error(400, 'Bad Request', 'La empresa es obligatoria'); RETURN;
    END IF;

    INSERT INTO precios_ventas (
        id_articulo, porc_recargo, precio_compra, precio_venta, cod_empresa,
        nro_linea, id_factura)
    VALUES (
        p_id_articulo, p_porc_recargo, p_precio_compra, p_precio_venta, p_cod_empresa,
        p_nro_linea, p_id_factura)
    RETURNING id_precio INTO l_id_precio;
    COMMIT;

    OWA_UTIL.STATUS_LINE(201, 'Created', FALSE);
    APEX_JSON.OPEN_OBJECT;
    APEX_JSON.WRITE('success', TRUE);
    APEX_JSON.WRITE('message', 'Precio registrado');
    APEX_JSON.WRITE('id_precio', l_id_precio);
    APEX_JSON.CLOSE_OBJECT;
  EXCEPTION
    WHEN OTHERS THEN
      ROLLBACK;
      IF SQLCODE = -2291 THEN
        p_error(400, 'Bad Request', 'Articulo, empresa o factura de compra inexistente');
      ELSE
        p_error(500, 'Internal Server Error', 'Error: ' || SQLERRM);
      END IF;
  END INSERTAR;

  --------------------------------------------------------------------------
  -- ACTUALIZAR (resincroniza ARTICULOS si el registro tocado era, o pasa a
  -- ser, el precio vigente del articulo)
  --------------------------------------------------------------------------
  PROCEDURE ACTUALIZAR(
      p_token IN VARCHAR2, p_id_precio IN NUMBER, p_id_articulo IN NUMBER,
      p_porc_recargo IN NUMBER, p_precio_compra IN NUMBER, p_precio_venta IN NUMBER,
      p_cod_empresa IN NUMBER, p_nro_linea IN NUMBER, p_id_factura IN NUMBER) IS
    l_usuario        VARCHAR2(255);
    l_id_articulo_ant precios_ventas.id_articulo%TYPE;
  BEGIN
    l_usuario := f_usuario(p_token);
    IF l_usuario IS NULL THEN
      p_error(401, 'Unauthorized', 'Token invalido o expirado');
      RETURN;
    END IF;

    IF p_id_articulo IS NULL THEN
      p_error(400, 'Bad Request', 'El articulo es obligatorio'); RETURN;
    END IF;
    IF p_precio_venta IS NULL THEN
      p_error(400, 'Bad Request', 'El precio de venta es obligatorio'); RETURN;
    END IF;

    BEGIN
      SELECT id_articulo INTO l_id_articulo_ant
        FROM precios_ventas
       WHERE id_precio = p_id_precio AND cod_empresa = p_cod_empresa;
    EXCEPTION
      WHEN NO_DATA_FOUND THEN
        p_error(404, 'Not Found', 'Precio no encontrado');
        RETURN;
    END;

    UPDATE precios_ventas
       SET id_articulo   = p_id_articulo,
           porc_recargo  = p_porc_recargo,
           precio_compra = p_precio_compra,
           precio_venta  = p_precio_venta,
           nro_linea     = p_nro_linea,
           id_factura    = p_id_factura
     WHERE id_precio = p_id_precio
       AND cod_empresa = p_cod_empresa;

    IF SQL%ROWCOUNT = 0 THEN
      ROLLBACK;
      p_error(404, 'Not Found', 'Precio no encontrado');
      RETURN;
    END IF;

    -- El UPDATE no dispara el trigger AIU: resincronizar a mano el/los
    -- articulos que pudieron perder su precio vigente (el anterior, si
    -- cambio de articulo, y el nuevo/actual).
    p_resincronizar_articulo(p_cod_empresa, p_id_articulo);
    IF l_id_articulo_ant != p_id_articulo THEN
      p_resincronizar_articulo(p_cod_empresa, l_id_articulo_ant);
    END IF;

    COMMIT;

    APEX_JSON.OPEN_OBJECT;
    APEX_JSON.WRITE('success', TRUE);
    APEX_JSON.WRITE('message', 'Precio actualizado');
    APEX_JSON.CLOSE_OBJECT;
  EXCEPTION
    WHEN OTHERS THEN
      ROLLBACK;
      IF SQLCODE = -2291 THEN
        p_error(400, 'Bad Request', 'Articulo, empresa o factura de compra inexistente');
      ELSE
        p_error(500, 'Internal Server Error', 'Error: ' || SQLERRM);
      END IF;
  END ACTUALIZAR;

  --------------------------------------------------------------------------
  -- ELIMINAR (resincroniza ARTICULOS con el precio vigente restante)
  --------------------------------------------------------------------------
  PROCEDURE ELIMINAR(p_token IN VARCHAR2, p_id_precio IN NUMBER, p_cod_empresa IN NUMBER) IS
    l_usuario    VARCHAR2(255);
    l_id_articulo precios_ventas.id_articulo%TYPE;
  BEGIN
    l_usuario := f_usuario(p_token);
    IF l_usuario IS NULL THEN
      p_error(401, 'Unauthorized', 'Token invalido o expirado');
      RETURN;
    END IF;

    BEGIN
      SELECT id_articulo INTO l_id_articulo
        FROM precios_ventas
       WHERE id_precio = p_id_precio AND cod_empresa = p_cod_empresa;
    EXCEPTION
      WHEN NO_DATA_FOUND THEN
        p_error(404, 'Not Found', 'Precio no encontrado');
        RETURN;
    END;

    DELETE FROM precios_ventas
     WHERE id_precio = p_id_precio
       AND cod_empresa = p_cod_empresa;

    IF SQL%ROWCOUNT = 0 THEN
      ROLLBACK;
      p_error(404, 'Not Found', 'Precio no encontrado');
      RETURN;
    END IF;

    p_resincronizar_articulo(p_cod_empresa, l_id_articulo);
    COMMIT;

    APEX_JSON.OPEN_OBJECT;
    APEX_JSON.WRITE('success', TRUE);
    APEX_JSON.WRITE('message', 'Precio eliminado');
    APEX_JSON.CLOSE_OBJECT;
  EXCEPTION
    WHEN OTHERS THEN
      ROLLBACK;
      p_error(500, 'Internal Server Error', 'Error: ' || SQLERRM);
  END ELIMINAR;

END PKG_PRECIOS_VENTAS_LUBRIMEC;
/

--------------------------------------------------------------------------------
-- === 2) ENDPOINTS ORDS =====================================================
--
--   GET    /lubrimec/precios-ventas?cod_empresa=:n[&id_articulo=:n]  -> listar
--   GET    /lubrimec/precios-ventas/sugerir?cod_empresa&id_articulo[&id_factura] -> sugeridos
--   GET    /lubrimec/precios-ventas/articulos?cod_empresa[&id_factura] -> LOV articulos
--   GET    /lubrimec/precios-ventas/compras?cod_empresa=:n            -> LOV facturas
--   GET    /lubrimec/precios-ventas/:id?cod_empresa=:n               -> obtener
--   POST   /lubrimec/precios-ventas                                  -> insertar
--   PUT    /lubrimec/precios-ventas/:id                               -> actualizar
--   DELETE /lubrimec/precios-ventas/:id?cod_empresa=:n               -> eliminar
--
-- NOTA: /sugerir y /articulos usan p_priority => 1 para matchear ANTES que
-- /precios-ventas/:id (prioridad 0); si no, "sugerir"/"articulos" caerian en
-- :id y TO_NUMBER reventaria -> 400.
--------------------------------------------------------------------------------

BEGIN
  BEGIN ORDS.DELETE_HANDLER('lubrimec', 'precios-ventas', 'GET');            EXCEPTION WHEN OTHERS THEN NULL; END;
  BEGIN ORDS.DELETE_HANDLER('lubrimec', 'precios-ventas', 'POST');           EXCEPTION WHEN OTHERS THEN NULL; END;
  BEGIN ORDS.DELETE_HANDLER('lubrimec', 'precios-ventas/sugerir', 'GET');    EXCEPTION WHEN OTHERS THEN NULL; END;
  BEGIN ORDS.DELETE_HANDLER('lubrimec', 'precios-ventas/articulos', 'GET');  EXCEPTION WHEN OTHERS THEN NULL; END;
  BEGIN ORDS.DELETE_HANDLER('lubrimec', 'precios-ventas/compras', 'GET');    EXCEPTION WHEN OTHERS THEN NULL; END;
  BEGIN ORDS.DELETE_HANDLER('lubrimec', 'precios-ventas/:id', 'GET');    EXCEPTION WHEN OTHERS THEN NULL; END;
  BEGIN ORDS.DELETE_HANDLER('lubrimec', 'precios-ventas/:id', 'PUT');    EXCEPTION WHEN OTHERS THEN NULL; END;
  BEGIN ORDS.DELETE_HANDLER('lubrimec', 'precios-ventas/:id', 'DELETE'); EXCEPTION WHEN OTHERS THEN NULL; END;

  ----------------------------------------------------------------------------
  -- /precios-ventas
  ----------------------------------------------------------------------------
  BEGIN
    ORDS.DEFINE_TEMPLATE(p_module_name => 'lubrimec', p_pattern => 'precios-ventas',
        p_priority => 0, p_etag_type => 'HASH', p_comments => NULL);
  EXCEPTION WHEN OTHERS THEN NULL; END;

  ORDS.DEFINE_HANDLER(
      p_module_name => 'lubrimec', p_pattern => 'precios-ventas', p_method => 'GET',
      p_source_type => 'plsql/block',
      p_source      => q'~
DECLARE
    l_token VARCHAR2(256); l_pos PLS_INTEGER;
    l_qs VARCHAR2(4000); l_cod_empresa VARCHAR2(20); l_id_articulo VARCHAR2(20);
    FUNCTION get_qs(p_qs IN VARCHAR2, p_key IN VARCHAR2) RETURN VARCHAR2 IS
        l_p PLS_INTEGER; l_e PLS_INTEGER; l_v VARCHAR2(4000);
    BEGIN
        l_p := INSTR('&' || p_qs, '&' || p_key || '=');
        IF l_p = 0 THEN RETURN NULL; END IF;
        l_p := l_p + LENGTH(p_key) + 1;
        l_e := INSTR(p_qs || '&', '&', l_p);
        l_v := SUBSTR(p_qs, l_p, l_e - l_p);
        l_v := REPLACE(l_v, '+', ' ');
        RETURN UTL_URL.UNESCAPE(l_v);
    END;
BEGIN
    OWA_UTIL.MIME_HEADER('application/json', FALSE);
    HTP.P('Access-Control-Allow-Origin: *');
    HTP.P('Access-Control-Allow-Methods: GET, POST, PUT, DELETE, OPTIONS');
    HTP.P('Access-Control-Allow-Headers: Authorization, Content-Type');
    OWA_UTIL.HTTP_HEADER_CLOSE;
    l_token := :authorization;
    IF l_token IS NOT NULL THEN
        l_pos := INSTR(UPPER(l_token), 'BEARER ');
        IF l_pos > 0 THEN l_token := TRIM(SUBSTR(l_token, l_pos + 7)); END IF;
    END IF;
    l_qs := OWA_UTIL.GET_CGI_ENV('QUERY_STRING');
    l_cod_empresa := get_qs(l_qs, 'cod_empresa');
    l_id_articulo := get_qs(l_qs, 'id_articulo');
    PKG_PRECIOS_VENTAS_LUBRIMEC.LISTAR(
        p_token => l_token, p_cod_empresa => TO_NUMBER(l_cod_empresa),
        p_id_articulo => TO_NUMBER(l_id_articulo));
END;
~');
  ORDS.DEFINE_PARAMETER(p_module_name => 'lubrimec', p_pattern => 'precios-ventas', p_method => 'GET',
      p_name => 'Authorization', p_bind_variable_name => 'authorization',
      p_source_type => 'HEADER', p_param_type => 'STRING', p_access_method => 'IN');

  ORDS.DEFINE_HANDLER(
      p_module_name => 'lubrimec', p_pattern => 'precios-ventas', p_method => 'POST',
      p_source_type => 'plsql/block',
      p_source      => q'~
DECLARE l_token VARCHAR2(256); l_pos PLS_INTEGER;
BEGIN
    OWA_UTIL.MIME_HEADER('application/json', FALSE);
    HTP.P('Access-Control-Allow-Origin: *');
    HTP.P('Access-Control-Allow-Methods: GET, POST, PUT, DELETE, OPTIONS');
    HTP.P('Access-Control-Allow-Headers: Authorization, Content-Type');
    OWA_UTIL.HTTP_HEADER_CLOSE;
    l_token := :authorization;
    IF l_token IS NOT NULL THEN
        l_pos := INSTR(UPPER(l_token), 'BEARER ');
        IF l_pos > 0 THEN l_token := TRIM(SUBSTR(l_token, l_pos + 7)); END IF;
    END IF;
    PKG_PRECIOS_VENTAS_LUBRIMEC.INSERTAR(
        p_token => l_token, p_id_articulo => TO_NUMBER(:id_articulo),
        p_porc_recargo => TO_NUMBER(:porc_recargo),
        p_precio_compra => TO_NUMBER(:precio_compra),
        p_precio_venta => TO_NUMBER(:precio_venta),
        p_cod_empresa => TO_NUMBER(:cod_empresa),
        p_nro_linea => TO_NUMBER(:nro_linea),
        p_id_factura => TO_NUMBER(:id_factura));
END;
~');
  ORDS.DEFINE_PARAMETER(p_module_name => 'lubrimec', p_pattern => 'precios-ventas', p_method => 'POST',
      p_name => 'Authorization', p_bind_variable_name => 'authorization',
      p_source_type => 'HEADER', p_param_type => 'STRING', p_access_method => 'IN');

  ----------------------------------------------------------------------------
  -- /precios-ventas/sugerir  (segmento fijo, prioridad 1)
  ----------------------------------------------------------------------------
  BEGIN
    ORDS.DEFINE_TEMPLATE(p_module_name => 'lubrimec', p_pattern => 'precios-ventas/sugerir',
        p_priority => 1, p_etag_type => 'HASH', p_comments => NULL);
  EXCEPTION WHEN OTHERS THEN NULL; END;

  ORDS.DEFINE_HANDLER(
      p_module_name => 'lubrimec', p_pattern => 'precios-ventas/sugerir', p_method => 'GET',
      p_source_type => 'plsql/block',
      p_source      => q'~
DECLARE
    l_token VARCHAR2(256); l_pos PLS_INTEGER;
    l_qs VARCHAR2(4000); l_cod_empresa VARCHAR2(20); l_id_factura VARCHAR2(20); l_id_articulo VARCHAR2(20);
    FUNCTION get_qs(p_qs IN VARCHAR2, p_key IN VARCHAR2) RETURN VARCHAR2 IS
        l_p PLS_INTEGER; l_e PLS_INTEGER; l_v VARCHAR2(4000);
    BEGIN
        l_p := INSTR('&' || p_qs, '&' || p_key || '=');
        IF l_p = 0 THEN RETURN NULL; END IF;
        l_p := l_p + LENGTH(p_key) + 1;
        l_e := INSTR(p_qs || '&', '&', l_p);
        l_v := SUBSTR(p_qs, l_p, l_e - l_p);
        l_v := REPLACE(l_v, '+', ' ');
        RETURN UTL_URL.UNESCAPE(l_v);
    END;
BEGIN
    OWA_UTIL.MIME_HEADER('application/json', FALSE);
    HTP.P('Access-Control-Allow-Origin: *');
    HTP.P('Access-Control-Allow-Methods: GET, OPTIONS');
    HTP.P('Access-Control-Allow-Headers: Authorization, Content-Type');
    OWA_UTIL.HTTP_HEADER_CLOSE;
    l_token := :authorization;
    IF l_token IS NOT NULL THEN
        l_pos := INSTR(UPPER(l_token), 'BEARER ');
        IF l_pos > 0 THEN l_token := TRIM(SUBSTR(l_token, l_pos + 7)); END IF;
    END IF;
    l_qs := OWA_UTIL.GET_CGI_ENV('QUERY_STRING');
    l_cod_empresa := get_qs(l_qs, 'cod_empresa');
    l_id_factura  := get_qs(l_qs, 'id_factura');
    l_id_articulo := get_qs(l_qs, 'id_articulo');
    PKG_PRECIOS_VENTAS_LUBRIMEC.SUGERIR(
        p_token => l_token, p_cod_empresa => TO_NUMBER(l_cod_empresa),
        p_id_factura => TO_NUMBER(l_id_factura), p_id_articulo => TO_NUMBER(l_id_articulo));
END;
~');
  ORDS.DEFINE_PARAMETER(p_module_name => 'lubrimec', p_pattern => 'precios-ventas/sugerir', p_method => 'GET',
      p_name => 'Authorization', p_bind_variable_name => 'authorization',
      p_source_type => 'HEADER', p_param_type => 'STRING', p_access_method => 'IN');

  ----------------------------------------------------------------------------
  -- /precios-ventas/articulos  (LOV cascada, prioridad 1)
  ----------------------------------------------------------------------------
  BEGIN
    ORDS.DEFINE_TEMPLATE(p_module_name => 'lubrimec', p_pattern => 'precios-ventas/articulos',
        p_priority => 1, p_etag_type => 'HASH', p_comments => NULL);
  EXCEPTION WHEN OTHERS THEN NULL; END;

  ORDS.DEFINE_HANDLER(
      p_module_name => 'lubrimec', p_pattern => 'precios-ventas/articulos', p_method => 'GET',
      p_source_type => 'plsql/block',
      p_source      => q'~
DECLARE
    l_token VARCHAR2(256); l_pos PLS_INTEGER;
    l_qs VARCHAR2(4000); l_cod_empresa VARCHAR2(20); l_id_factura VARCHAR2(20);
    FUNCTION get_qs(p_qs IN VARCHAR2, p_key IN VARCHAR2) RETURN VARCHAR2 IS
        l_p PLS_INTEGER; l_e PLS_INTEGER; l_v VARCHAR2(4000);
    BEGIN
        l_p := INSTR('&' || p_qs, '&' || p_key || '=');
        IF l_p = 0 THEN RETURN NULL; END IF;
        l_p := l_p + LENGTH(p_key) + 1;
        l_e := INSTR(p_qs || '&', '&', l_p);
        l_v := SUBSTR(p_qs, l_p, l_e - l_p);
        l_v := REPLACE(l_v, '+', ' ');
        RETURN UTL_URL.UNESCAPE(l_v);
    END;
BEGIN
    OWA_UTIL.MIME_HEADER('application/json', FALSE);
    HTP.P('Access-Control-Allow-Origin: *');
    HTP.P('Access-Control-Allow-Methods: GET, OPTIONS');
    HTP.P('Access-Control-Allow-Headers: Authorization, Content-Type');
    OWA_UTIL.HTTP_HEADER_CLOSE;
    l_token := :authorization;
    IF l_token IS NOT NULL THEN
        l_pos := INSTR(UPPER(l_token), 'BEARER ');
        IF l_pos > 0 THEN l_token := TRIM(SUBSTR(l_token, l_pos + 7)); END IF;
    END IF;
    l_qs := OWA_UTIL.GET_CGI_ENV('QUERY_STRING');
    l_cod_empresa := get_qs(l_qs, 'cod_empresa');
    l_id_factura  := get_qs(l_qs, 'id_factura');
    PKG_PRECIOS_VENTAS_LUBRIMEC.ARTICULOS_FACTURA(
        p_token => l_token, p_cod_empresa => TO_NUMBER(l_cod_empresa),
        p_id_factura => TO_NUMBER(l_id_factura));
END;
~');
  ORDS.DEFINE_PARAMETER(p_module_name => 'lubrimec', p_pattern => 'precios-ventas/articulos', p_method => 'GET',
      p_name => 'Authorization', p_bind_variable_name => 'authorization',
      p_source_type => 'HEADER', p_param_type => 'STRING', p_access_method => 'IN');

  ----------------------------------------------------------------------------
  -- /precios-ventas/compras  (LOV de facturas, prioridad 1)
  ----------------------------------------------------------------------------
  BEGIN
    ORDS.DEFINE_TEMPLATE(p_module_name => 'lubrimec', p_pattern => 'precios-ventas/compras',
        p_priority => 1, p_etag_type => 'HASH', p_comments => NULL);
  EXCEPTION WHEN OTHERS THEN NULL; END;

  ORDS.DEFINE_HANDLER(
      p_module_name => 'lubrimec', p_pattern => 'precios-ventas/compras', p_method => 'GET',
      p_source_type => 'plsql/block',
      p_source      => q'~
DECLARE
    l_token VARCHAR2(256); l_pos PLS_INTEGER;
    l_qs VARCHAR2(4000); l_cod_empresa VARCHAR2(20);
    FUNCTION get_qs(p_qs IN VARCHAR2, p_key IN VARCHAR2) RETURN VARCHAR2 IS
        l_p PLS_INTEGER; l_e PLS_INTEGER; l_v VARCHAR2(4000);
    BEGIN
        l_p := INSTR('&' || p_qs, '&' || p_key || '=');
        IF l_p = 0 THEN RETURN NULL; END IF;
        l_p := l_p + LENGTH(p_key) + 1;
        l_e := INSTR(p_qs || '&', '&', l_p);
        l_v := SUBSTR(p_qs, l_p, l_e - l_p);
        l_v := REPLACE(l_v, '+', ' ');
        RETURN UTL_URL.UNESCAPE(l_v);
    END;
BEGIN
    OWA_UTIL.MIME_HEADER('application/json', FALSE);
    HTP.P('Access-Control-Allow-Origin: *');
    HTP.P('Access-Control-Allow-Methods: GET, OPTIONS');
    HTP.P('Access-Control-Allow-Headers: Authorization, Content-Type');
    OWA_UTIL.HTTP_HEADER_CLOSE;
    l_token := :authorization;
    IF l_token IS NOT NULL THEN
        l_pos := INSTR(UPPER(l_token), 'BEARER ');
        IF l_pos > 0 THEN l_token := TRIM(SUBSTR(l_token, l_pos + 7)); END IF;
    END IF;
    l_qs := OWA_UTIL.GET_CGI_ENV('QUERY_STRING');
    l_cod_empresa := get_qs(l_qs, 'cod_empresa');
    PKG_PRECIOS_VENTAS_LUBRIMEC.BUSCAR_COMPRAS(
        p_token => l_token, p_cod_empresa => TO_NUMBER(l_cod_empresa));
END;
~');
  ORDS.DEFINE_PARAMETER(p_module_name => 'lubrimec', p_pattern => 'precios-ventas/compras', p_method => 'GET',
      p_name => 'Authorization', p_bind_variable_name => 'authorization',
      p_source_type => 'HEADER', p_param_type => 'STRING', p_access_method => 'IN');

  ----------------------------------------------------------------------------
  -- /precios-ventas/:id
  ----------------------------------------------------------------------------
  BEGIN
    ORDS.DEFINE_TEMPLATE(p_module_name => 'lubrimec', p_pattern => 'precios-ventas/:id',
        p_priority => 0, p_etag_type => 'HASH', p_comments => NULL);
  EXCEPTION WHEN OTHERS THEN NULL; END;

  ORDS.DEFINE_HANDLER(
      p_module_name => 'lubrimec', p_pattern => 'precios-ventas/:id', p_method => 'GET',
      p_source_type => 'plsql/block',
      p_source      => q'~
DECLARE
    l_token VARCHAR2(256); l_pos PLS_INTEGER;
    l_qs VARCHAR2(4000); l_cod_empresa VARCHAR2(20);
    FUNCTION get_qs(p_qs IN VARCHAR2, p_key IN VARCHAR2) RETURN VARCHAR2 IS
        l_p PLS_INTEGER; l_e PLS_INTEGER; l_v VARCHAR2(4000);
    BEGIN
        l_p := INSTR('&' || p_qs, '&' || p_key || '=');
        IF l_p = 0 THEN RETURN NULL; END IF;
        l_p := l_p + LENGTH(p_key) + 1;
        l_e := INSTR(p_qs || '&', '&', l_p);
        l_v := SUBSTR(p_qs, l_p, l_e - l_p);
        l_v := REPLACE(l_v, '+', ' ');
        RETURN UTL_URL.UNESCAPE(l_v);
    END;
BEGIN
    OWA_UTIL.MIME_HEADER('application/json', FALSE);
    HTP.P('Access-Control-Allow-Origin: *');
    HTP.P('Access-Control-Allow-Methods: GET, POST, PUT, DELETE, OPTIONS');
    HTP.P('Access-Control-Allow-Headers: Authorization, Content-Type');
    OWA_UTIL.HTTP_HEADER_CLOSE;
    l_token := :authorization;
    IF l_token IS NOT NULL THEN
        l_pos := INSTR(UPPER(l_token), 'BEARER ');
        IF l_pos > 0 THEN l_token := TRIM(SUBSTR(l_token, l_pos + 7)); END IF;
    END IF;
    l_qs := OWA_UTIL.GET_CGI_ENV('QUERY_STRING');
    l_cod_empresa := get_qs(l_qs, 'cod_empresa');
    PKG_PRECIOS_VENTAS_LUBRIMEC.OBTENER(
        p_token => l_token, p_id_precio => TO_NUMBER(:id),
        p_cod_empresa => TO_NUMBER(l_cod_empresa));
END;
~');
  ORDS.DEFINE_PARAMETER(p_module_name => 'lubrimec', p_pattern => 'precios-ventas/:id', p_method => 'GET',
      p_name => 'Authorization', p_bind_variable_name => 'authorization',
      p_source_type => 'HEADER', p_param_type => 'STRING', p_access_method => 'IN');

  ORDS.DEFINE_HANDLER(
      p_module_name => 'lubrimec', p_pattern => 'precios-ventas/:id', p_method => 'PUT',
      p_source_type => 'plsql/block',
      p_source      => q'~
DECLARE l_token VARCHAR2(256); l_pos PLS_INTEGER;
BEGIN
    OWA_UTIL.MIME_HEADER('application/json', FALSE);
    HTP.P('Access-Control-Allow-Origin: *');
    HTP.P('Access-Control-Allow-Methods: GET, POST, PUT, DELETE, OPTIONS');
    HTP.P('Access-Control-Allow-Headers: Authorization, Content-Type');
    OWA_UTIL.HTTP_HEADER_CLOSE;
    l_token := :authorization;
    IF l_token IS NOT NULL THEN
        l_pos := INSTR(UPPER(l_token), 'BEARER ');
        IF l_pos > 0 THEN l_token := TRIM(SUBSTR(l_token, l_pos + 7)); END IF;
    END IF;
    PKG_PRECIOS_VENTAS_LUBRIMEC.ACTUALIZAR(
        p_token => l_token, p_id_precio => TO_NUMBER(:id),
        p_id_articulo => TO_NUMBER(:id_articulo),
        p_porc_recargo => TO_NUMBER(:porc_recargo),
        p_precio_compra => TO_NUMBER(:precio_compra),
        p_precio_venta => TO_NUMBER(:precio_venta),
        p_cod_empresa => TO_NUMBER(:cod_empresa),
        p_nro_linea => TO_NUMBER(:nro_linea),
        p_id_factura => TO_NUMBER(:id_factura));
END;
~');
  ORDS.DEFINE_PARAMETER(p_module_name => 'lubrimec', p_pattern => 'precios-ventas/:id', p_method => 'PUT',
      p_name => 'Authorization', p_bind_variable_name => 'authorization',
      p_source_type => 'HEADER', p_param_type => 'STRING', p_access_method => 'IN');

  ORDS.DEFINE_HANDLER(
      p_module_name => 'lubrimec', p_pattern => 'precios-ventas/:id', p_method => 'DELETE',
      p_source_type => 'plsql/block',
      p_source      => q'~
DECLARE
    l_token VARCHAR2(256); l_pos PLS_INTEGER;
    l_qs VARCHAR2(4000); l_cod_empresa VARCHAR2(20);
    FUNCTION get_qs(p_qs IN VARCHAR2, p_key IN VARCHAR2) RETURN VARCHAR2 IS
        l_p PLS_INTEGER; l_e PLS_INTEGER; l_v VARCHAR2(4000);
    BEGIN
        l_p := INSTR('&' || p_qs, '&' || p_key || '=');
        IF l_p = 0 THEN RETURN NULL; END IF;
        l_p := l_p + LENGTH(p_key) + 1;
        l_e := INSTR(p_qs || '&', '&', l_p);
        l_v := SUBSTR(p_qs, l_p, l_e - l_p);
        l_v := REPLACE(l_v, '+', ' ');
        RETURN UTL_URL.UNESCAPE(l_v);
    END;
BEGIN
    OWA_UTIL.MIME_HEADER('application/json', FALSE);
    HTP.P('Access-Control-Allow-Origin: *');
    HTP.P('Access-Control-Allow-Methods: GET, POST, PUT, DELETE, OPTIONS');
    HTP.P('Access-Control-Allow-Headers: Authorization, Content-Type');
    OWA_UTIL.HTTP_HEADER_CLOSE;
    l_token := :authorization;
    IF l_token IS NOT NULL THEN
        l_pos := INSTR(UPPER(l_token), 'BEARER ');
        IF l_pos > 0 THEN l_token := TRIM(SUBSTR(l_token, l_pos + 7)); END IF;
    END IF;
    l_qs := OWA_UTIL.GET_CGI_ENV('QUERY_STRING');
    l_cod_empresa := get_qs(l_qs, 'cod_empresa');
    PKG_PRECIOS_VENTAS_LUBRIMEC.ELIMINAR(
        p_token => l_token, p_id_precio => TO_NUMBER(:id),
        p_cod_empresa => TO_NUMBER(l_cod_empresa));
END;
~');
  ORDS.DEFINE_PARAMETER(p_module_name => 'lubrimec', p_pattern => 'precios-ventas/:id', p_method => 'DELETE',
      p_name => 'Authorization', p_bind_variable_name => 'authorization',
      p_source_type => 'HEADER', p_param_type => 'STRING', p_access_method => 'IN');

  COMMIT;
EXCEPTION
  WHEN OTHERS THEN
    ROLLBACK;
    RAISE;
END;
/
