--------------------------------------------------------------------------------
-- RENDICIONES_CAJAS (pagina APEX 73 grilla + 74 modal) — paquete CRUD + ORDS.
-- Ejecutar completo como el esquema JOSEGALVEZ. Requiere PKG_AUTH_LUBRIMEC.
--
-- PK id_cierre GENERATED BY DEFAULT ON NULL AS IDENTITY (no se pasa en el INSERT).
-- Filtra por cod_empresa (multiempresa). Campos NOT NULL: cod_empresa, fecha,
-- total_caja_anterior, total_venta, total_retiro, total_caja. total_pago y
-- observacion son opcionales.
--
-- SUGERIDOS: replica los auto-calculos del modal APEX 74 (Dynamic Actions).
--   - total_caja_anterior = total_caja de la ultima rendicion con fecha < :fecha
--   - total_venta = SUM(V_COBROS_CLIENTES.total) de cobros efectivo (id_forma=1,
--     cod_vendedor IN 101,102) desde la ultima rendicion hasta :fecha
--   - total_pago  = SUM(compras_detalle) con fec_comprobante desde la ultima
--     rendicion hasta :fecha, excluyendo id_comprador 81
--
-- === 1) PAQUETE PKG_RENDICIONES_CAJAS_LUBRIMEC =============================
--------------------------------------------------------------------------------

CREATE OR REPLACE PACKAGE PKG_RENDICIONES_CAJAS_LUBRIMEC AS

  PROCEDURE LISTAR(p_token IN VARCHAR2, p_cod_empresa IN NUMBER);
  PROCEDURE OBTENER(p_token IN VARCHAR2, p_id_cierre IN NUMBER, p_cod_empresa IN NUMBER);
  PROCEDURE SUGERIDOS(p_token IN VARCHAR2, p_cod_empresa IN NUMBER, p_fecha IN VARCHAR2);
  PROCEDURE INSERTAR(
      p_token IN VARCHAR2, p_cod_empresa IN NUMBER, p_fecha IN VARCHAR2,
      p_total_caja_anterior IN NUMBER, p_total_venta IN NUMBER,
      p_total_retiro IN NUMBER, p_total_caja IN NUMBER,
      p_total_pago IN NUMBER, p_observacion IN VARCHAR2);
  PROCEDURE ACTUALIZAR(
      p_token IN VARCHAR2, p_id_cierre IN NUMBER, p_cod_empresa IN NUMBER, p_fecha IN VARCHAR2,
      p_total_caja_anterior IN NUMBER, p_total_venta IN NUMBER,
      p_total_retiro IN NUMBER, p_total_caja IN NUMBER,
      p_total_pago IN NUMBER, p_observacion IN VARCHAR2);
  PROCEDURE ELIMINAR(p_token IN VARCHAR2, p_id_cierre IN NUMBER, p_cod_empresa IN NUMBER);

END PKG_RENDICIONES_CAJAS_LUBRIMEC;
/

CREATE OR REPLACE PACKAGE BODY PKG_RENDICIONES_CAJAS_LUBRIMEC AS

  PROCEDURE p_error(p_status IN NUMBER, p_reason IN VARCHAR2, p_message IN VARCHAR2) IS
  BEGIN
    OWA_UTIL.STATUS_LINE(p_status, p_reason, FALSE);
    APEX_JSON.OPEN_OBJECT;
    APEX_JSON.WRITE('success', FALSE);
    APEX_JSON.WRITE('message', p_message);
    APEX_JSON.CLOSE_OBJECT;
  END p_error;

  FUNCTION f_usuario(p_token IN VARCHAR2) RETURN VARCHAR2 IS
  BEGIN
    RETURN PKG_AUTH_LUBRIMEC.VALIDAR_TOKEN(p_token);
  END f_usuario;

  --------------------------------------------------------------------------
  -- LISTAR
  --------------------------------------------------------------------------
  PROCEDURE LISTAR(p_token IN VARCHAR2, p_cod_empresa IN NUMBER) IS
    l_usuario VARCHAR2(255);
  BEGIN
    l_usuario := f_usuario(p_token);
    IF l_usuario IS NULL THEN
      p_error(401, 'Unauthorized', 'Token invalido o expirado');
      RETURN;
    END IF;

    APEX_JSON.OPEN_OBJECT;
    APEX_JSON.WRITE('success', TRUE);
    APEX_JSON.OPEN_ARRAY('data');
    FOR r IN (
        SELECT id_cierre, cod_empresa,
               TO_CHAR(fecha, 'YYYY-MM-DD') fecha,
               total_caja_anterior, total_venta, total_retiro,
               total_caja, total_pago, observacion
          FROM rendiciones_cajas
         WHERE cod_empresa = p_cod_empresa
         ORDER BY fecha DESC, id_cierre DESC
    ) LOOP
      APEX_JSON.OPEN_OBJECT;
      APEX_JSON.WRITE('id_cierre', r.id_cierre);
      APEX_JSON.WRITE('cod_empresa', r.cod_empresa);
      APEX_JSON.WRITE('fecha', r.fecha);
      APEX_JSON.WRITE('total_caja_anterior', r.total_caja_anterior);
      APEX_JSON.WRITE('total_venta', r.total_venta);
      APEX_JSON.WRITE('total_retiro', r.total_retiro);
      APEX_JSON.WRITE('total_caja', r.total_caja);
      APEX_JSON.WRITE('total_pago', r.total_pago);
      APEX_JSON.WRITE('observacion', r.observacion);
      APEX_JSON.CLOSE_OBJECT;
    END LOOP;
    APEX_JSON.CLOSE_ARRAY;
    APEX_JSON.CLOSE_OBJECT;
  EXCEPTION
    WHEN OTHERS THEN
      p_error(500, 'Internal Server Error', 'Error: ' || SQLERRM);
  END LISTAR;

  --------------------------------------------------------------------------
  -- OBTENER
  --------------------------------------------------------------------------
  PROCEDURE OBTENER(p_token IN VARCHAR2, p_id_cierre IN NUMBER, p_cod_empresa IN NUMBER) IS
    l_usuario VARCHAR2(255);
    r         rendiciones_cajas%ROWTYPE;
  BEGIN
    l_usuario := f_usuario(p_token);
    IF l_usuario IS NULL THEN
      p_error(401, 'Unauthorized', 'Token invalido o expirado');
      RETURN;
    END IF;

    BEGIN
      SELECT * INTO r
        FROM rendiciones_cajas
       WHERE id_cierre = p_id_cierre
         AND cod_empresa = p_cod_empresa;
    EXCEPTION
      WHEN NO_DATA_FOUND THEN
        p_error(404, 'Not Found', 'Rendicion no encontrada');
        RETURN;
    END;

    APEX_JSON.OPEN_OBJECT;
    APEX_JSON.WRITE('success', TRUE);
    APEX_JSON.OPEN_OBJECT('data');
    APEX_JSON.WRITE('id_cierre', r.id_cierre);
    APEX_JSON.WRITE('cod_empresa', r.cod_empresa);
    APEX_JSON.WRITE('fecha', TO_CHAR(r.fecha, 'YYYY-MM-DD'));
    APEX_JSON.WRITE('total_caja_anterior', r.total_caja_anterior);
    APEX_JSON.WRITE('total_venta', r.total_venta);
    APEX_JSON.WRITE('total_retiro', r.total_retiro);
    APEX_JSON.WRITE('total_caja', r.total_caja);
    APEX_JSON.WRITE('total_pago', r.total_pago);
    APEX_JSON.WRITE('observacion', r.observacion);
    APEX_JSON.CLOSE_OBJECT;
    APEX_JSON.CLOSE_OBJECT;
  EXCEPTION
    WHEN OTHERS THEN
      p_error(500, 'Internal Server Error', 'Error: ' || SQLERRM);
  END OBTENER;

  --------------------------------------------------------------------------
  -- SUGERIDOS (auto-calculo del modal APEX 74)
  --------------------------------------------------------------------------
  PROCEDURE SUGERIDOS(p_token IN VARCHAR2, p_cod_empresa IN NUMBER, p_fecha IN VARCHAR2) IS
    l_usuario        VARCHAR2(255);
    l_fecha          DATE;
    l_fecha_ant      DATE;     -- fecha de la ultima rendicion anterior a l_fecha
    l_caja_anterior  NUMBER := 0;
    l_venta          NUMBER := 0;
    l_pago           NUMBER := 0;
  BEGIN
    l_usuario := f_usuario(p_token);
    IF l_usuario IS NULL THEN
      p_error(401, 'Unauthorized', 'Token invalido o expirado');
      RETURN;
    END IF;

    IF p_fecha IS NULL THEN
      p_error(400, 'Bad Request', 'La fecha es obligatoria');
      RETURN;
    END IF;
    l_fecha := TO_DATE(p_fecha, 'YYYY-MM-DD');

    -- Fecha de la ultima rendicion anterior a la elegida (define el corte de los sumatorios)
    BEGIN
      SELECT MAX(fecha) INTO l_fecha_ant
        FROM rendiciones_cajas
       WHERE cod_empresa = p_cod_empresa
         AND fecha < l_fecha;
    EXCEPTION WHEN OTHERS THEN l_fecha_ant := NULL; END;

    -- Total caja anterior: total_caja de esa ultima rendicion
    IF l_fecha_ant IS NOT NULL THEN
      BEGIN
        SELECT total_caja INTO l_caja_anterior
          FROM rendiciones_cajas
         WHERE cod_empresa = p_cod_empresa
           AND fecha = l_fecha_ant
           AND ROWNUM = 1;
      EXCEPTION WHEN OTHERS THEN l_caja_anterior := 0; END;
    END IF;

    -- Total venta: cobros efectivo desde la ultima rendicion hasta la fecha elegida
    BEGIN
      SELECT NVL(SUM(total), 0) INTO l_venta
        FROM v_cobros_clientes b
       WHERE b.cod_empresa = p_cod_empresa
         AND TO_DATE(b.fecha, 'dd/mm/yyyy') <= l_fecha
         AND b.cod_vendedor IN (101, 102)
         AND b.id_forma = 1
         AND (l_fecha_ant IS NULL OR TO_DATE(b.fecha, 'dd/mm/yyyy') > l_fecha_ant);
    EXCEPTION WHEN OTHERS THEN l_venta := 0; END;

    -- Total pago: compras desde la ultima rendicion hasta la fecha elegida
    BEGIN
      SELECT NVL(SUM(NVL(d.cantidad, 0) * NVL(d.precio, 0)), 0) INTO l_pago
        FROM compras_cabecera a, compras_detalle d
       WHERE a.cod_empresa = p_cod_empresa
         AND a.id_factura = d.id_factura
         AND a.fec_comprobante <= l_fecha
         AND a.id_comprador NOT IN (81)
         AND (l_fecha_ant IS NULL OR a.fec_comprobante > l_fecha_ant);
    EXCEPTION WHEN OTHERS THEN l_pago := 0; END;

    APEX_JSON.OPEN_OBJECT;
    APEX_JSON.WRITE('success', TRUE);
    APEX_JSON.OPEN_OBJECT('data');
    APEX_JSON.WRITE('total_caja_anterior', l_caja_anterior);
    APEX_JSON.WRITE('total_venta', l_venta);
    APEX_JSON.WRITE('total_pago', l_pago);
    APEX_JSON.CLOSE_OBJECT;
    APEX_JSON.CLOSE_OBJECT;
  EXCEPTION
    WHEN OTHERS THEN
      p_error(500, 'Internal Server Error', 'Error: ' || SQLERRM);
  END SUGERIDOS;

  --------------------------------------------------------------------------
  -- INSERTAR (id por IDENTITY)
  --------------------------------------------------------------------------
  PROCEDURE INSERTAR(
      p_token IN VARCHAR2, p_cod_empresa IN NUMBER, p_fecha IN VARCHAR2,
      p_total_caja_anterior IN NUMBER, p_total_venta IN NUMBER,
      p_total_retiro IN NUMBER, p_total_caja IN NUMBER,
      p_total_pago IN NUMBER, p_observacion IN VARCHAR2) IS
    l_usuario   VARCHAR2(255);
    l_id_cierre rendiciones_cajas.id_cierre%TYPE;
    l_fecha     DATE;
  BEGIN
    l_usuario := f_usuario(p_token);
    IF l_usuario IS NULL THEN
      p_error(401, 'Unauthorized', 'Token invalido o expirado');
      RETURN;
    END IF;

    IF p_cod_empresa IS NULL THEN
      p_error(400, 'Bad Request', 'La empresa es obligatoria');
      RETURN;
    END IF;
    IF p_fecha IS NULL THEN
      p_error(400, 'Bad Request', 'La fecha es obligatoria');
      RETURN;
    END IF;
    l_fecha := TO_DATE(p_fecha, 'YYYY-MM-DD');

    INSERT INTO rendiciones_cajas (
        cod_empresa, fecha, total_caja_anterior, total_venta,
        total_retiro, total_caja, total_pago, observacion)
    VALUES (
        p_cod_empresa, l_fecha, NVL(p_total_caja_anterior, 0), NVL(p_total_venta, 0),
        NVL(p_total_retiro, 0), NVL(p_total_caja, 0), p_total_pago, p_observacion)
    RETURNING id_cierre INTO l_id_cierre;
    COMMIT;

    OWA_UTIL.STATUS_LINE(201, 'Created', FALSE);
    APEX_JSON.OPEN_OBJECT;
    APEX_JSON.WRITE('success', TRUE);
    APEX_JSON.WRITE('message', 'Rendicion creada');
    APEX_JSON.WRITE('id_cierre', l_id_cierre);
    APEX_JSON.CLOSE_OBJECT;
  EXCEPTION
    WHEN OTHERS THEN
      ROLLBACK;
      IF SQLCODE = -2291 THEN
        p_error(400, 'Bad Request', 'La empresa indicada no existe');
      ELSE
        p_error(500, 'Internal Server Error', 'Error: ' || SQLERRM);
      END IF;
  END INSERTAR;

  --------------------------------------------------------------------------
  -- ACTUALIZAR
  --------------------------------------------------------------------------
  PROCEDURE ACTUALIZAR(
      p_token IN VARCHAR2, p_id_cierre IN NUMBER, p_cod_empresa IN NUMBER, p_fecha IN VARCHAR2,
      p_total_caja_anterior IN NUMBER, p_total_venta IN NUMBER,
      p_total_retiro IN NUMBER, p_total_caja IN NUMBER,
      p_total_pago IN NUMBER, p_observacion IN VARCHAR2) IS
    l_usuario VARCHAR2(255);
    l_fecha   DATE;
  BEGIN
    l_usuario := f_usuario(p_token);
    IF l_usuario IS NULL THEN
      p_error(401, 'Unauthorized', 'Token invalido o expirado');
      RETURN;
    END IF;

    IF p_fecha IS NULL THEN
      p_error(400, 'Bad Request', 'La fecha es obligatoria');
      RETURN;
    END IF;
    l_fecha := TO_DATE(p_fecha, 'YYYY-MM-DD');

    UPDATE rendiciones_cajas
       SET fecha               = l_fecha,
           total_caja_anterior = NVL(p_total_caja_anterior, 0),
           total_venta         = NVL(p_total_venta, 0),
           total_retiro        = NVL(p_total_retiro, 0),
           total_caja          = NVL(p_total_caja, 0),
           total_pago          = p_total_pago,
           observacion         = p_observacion
     WHERE id_cierre = p_id_cierre
       AND cod_empresa = p_cod_empresa;

    IF SQL%ROWCOUNT = 0 THEN
      ROLLBACK;
      p_error(404, 'Not Found', 'Rendicion no encontrada');
      RETURN;
    END IF;
    COMMIT;

    APEX_JSON.OPEN_OBJECT;
    APEX_JSON.WRITE('success', TRUE);
    APEX_JSON.WRITE('message', 'Rendicion actualizada');
    APEX_JSON.CLOSE_OBJECT;
  EXCEPTION
    WHEN OTHERS THEN
      ROLLBACK;
      p_error(500, 'Internal Server Error', 'Error: ' || SQLERRM);
  END ACTUALIZAR;

  --------------------------------------------------------------------------
  -- ELIMINAR
  --------------------------------------------------------------------------
  PROCEDURE ELIMINAR(p_token IN VARCHAR2, p_id_cierre IN NUMBER, p_cod_empresa IN NUMBER) IS
    l_usuario VARCHAR2(255);
  BEGIN
    l_usuario := f_usuario(p_token);
    IF l_usuario IS NULL THEN
      p_error(401, 'Unauthorized', 'Token invalido o expirado');
      RETURN;
    END IF;

    DELETE FROM rendiciones_cajas
     WHERE id_cierre = p_id_cierre
       AND cod_empresa = p_cod_empresa;

    IF SQL%ROWCOUNT = 0 THEN
      ROLLBACK;
      p_error(404, 'Not Found', 'Rendicion no encontrada');
      RETURN;
    END IF;
    COMMIT;

    APEX_JSON.OPEN_OBJECT;
    APEX_JSON.WRITE('success', TRUE);
    APEX_JSON.WRITE('message', 'Rendicion eliminada');
    APEX_JSON.CLOSE_OBJECT;
  EXCEPTION
    WHEN OTHERS THEN
      ROLLBACK;
      p_error(500, 'Internal Server Error', 'Error: ' || SQLERRM);
  END ELIMINAR;

END PKG_RENDICIONES_CAJAS_LUBRIMEC;
/

--------------------------------------------------------------------------------
-- === 2) ENDPOINTS ORDS =====================================================
--
--   GET    /lubrimec/rendiciones?cod_empresa=:n           -> listar
--   GET    /lubrimec/rendiciones/sugeridos?cod_empresa&fecha -> auto-calculo
--   GET    /lubrimec/rendiciones/:id?cod_empresa=:n       -> obtener
--   POST   /lubrimec/rendiciones                          -> insertar
--   PUT    /lubrimec/rendiciones/:id                      -> actualizar
--   DELETE /lubrimec/rendiciones/:id?cod_empresa=:n       -> eliminar
--
-- NOTA: /rendiciones/sugeridos usa p_priority => 1 para matchear ANTES que
-- /rendiciones/:id (que va con prioridad 0). Si no, "sugeridos" caeria en :id y
-- TO_NUMBER('sugeridos') revienta -> 400.
--------------------------------------------------------------------------------

BEGIN
  BEGIN ORDS.DELETE_HANDLER('lubrimec', 'rendiciones', 'GET');            EXCEPTION WHEN OTHERS THEN NULL; END;
  BEGIN ORDS.DELETE_HANDLER('lubrimec', 'rendiciones', 'POST');           EXCEPTION WHEN OTHERS THEN NULL; END;
  BEGIN ORDS.DELETE_HANDLER('lubrimec', 'rendiciones/sugeridos', 'GET');  EXCEPTION WHEN OTHERS THEN NULL; END;
  BEGIN ORDS.DELETE_HANDLER('lubrimec', 'rendiciones/:id', 'GET');        EXCEPTION WHEN OTHERS THEN NULL; END;
  BEGIN ORDS.DELETE_HANDLER('lubrimec', 'rendiciones/:id', 'PUT');        EXCEPTION WHEN OTHERS THEN NULL; END;
  BEGIN ORDS.DELETE_HANDLER('lubrimec', 'rendiciones/:id', 'DELETE');     EXCEPTION WHEN OTHERS THEN NULL; END;

  ----------------------------------------------------------------------------
  -- /rendiciones  (coleccion: GET listar, POST insertar)
  ----------------------------------------------------------------------------
  BEGIN
    ORDS.DEFINE_TEMPLATE(p_module_name => 'lubrimec', p_pattern => 'rendiciones',
        p_priority => 0, p_etag_type => 'HASH', p_comments => NULL);
  EXCEPTION WHEN OTHERS THEN NULL; END;

  ORDS.DEFINE_HANDLER(
      p_module_name => 'lubrimec', p_pattern => 'rendiciones', p_method => 'GET',
      p_source_type => 'plsql/block',
      p_source      => q'~
DECLARE
    l_token VARCHAR2(256); l_pos PLS_INTEGER;
    l_qs VARCHAR2(4000); l_cod_empresa VARCHAR2(20);
    FUNCTION get_qs(p_qs IN VARCHAR2, p_key IN VARCHAR2) RETURN VARCHAR2 IS
        l_p PLS_INTEGER; l_e PLS_INTEGER; l_v VARCHAR2(4000);
    BEGIN
        l_p := INSTR('&' || p_qs, '&' || p_key || '=');
        IF l_p = 0 THEN RETURN NULL; END IF;
        l_p := l_p + LENGTH(p_key) + 1;
        l_e := INSTR(p_qs || '&', '&', l_p);
        l_v := SUBSTR(p_qs, l_p, l_e - l_p);
        l_v := REPLACE(l_v, '+', ' ');
        RETURN UTL_URL.UNESCAPE(l_v);
    END;
BEGIN
    OWA_UTIL.MIME_HEADER('application/json', FALSE);
    HTP.P('Access-Control-Allow-Origin: *');
    HTP.P('Access-Control-Allow-Methods: GET, POST, PUT, DELETE, OPTIONS');
    HTP.P('Access-Control-Allow-Headers: Authorization, Content-Type');
    OWA_UTIL.HTTP_HEADER_CLOSE;
    l_token := :authorization;
    IF l_token IS NOT NULL THEN
        l_pos := INSTR(UPPER(l_token), 'BEARER ');
        IF l_pos > 0 THEN l_token := TRIM(SUBSTR(l_token, l_pos + 7)); END IF;
    END IF;
    l_qs := OWA_UTIL.GET_CGI_ENV('QUERY_STRING');
    l_cod_empresa := get_qs(l_qs, 'cod_empresa');
    PKG_RENDICIONES_CAJAS_LUBRIMEC.LISTAR(
        p_token => l_token, p_cod_empresa => TO_NUMBER(l_cod_empresa));
END;
~');
  ORDS.DEFINE_PARAMETER(p_module_name => 'lubrimec', p_pattern => 'rendiciones', p_method => 'GET',
      p_name => 'Authorization', p_bind_variable_name => 'authorization',
      p_source_type => 'HEADER', p_param_type => 'STRING', p_access_method => 'IN');

  ORDS.DEFINE_HANDLER(
      p_module_name => 'lubrimec', p_pattern => 'rendiciones', p_method => 'POST',
      p_source_type => 'plsql/block',
      p_source      => q'~
DECLARE l_token VARCHAR2(256); l_pos PLS_INTEGER;
BEGIN
    OWA_UTIL.MIME_HEADER('application/json', FALSE);
    HTP.P('Access-Control-Allow-Origin: *');
    HTP.P('Access-Control-Allow-Methods: GET, POST, PUT, DELETE, OPTIONS');
    HTP.P('Access-Control-Allow-Headers: Authorization, Content-Type');
    OWA_UTIL.HTTP_HEADER_CLOSE;
    l_token := :authorization;
    IF l_token IS NOT NULL THEN
        l_pos := INSTR(UPPER(l_token), 'BEARER ');
        IF l_pos > 0 THEN l_token := TRIM(SUBSTR(l_token, l_pos + 7)); END IF;
    END IF;
    PKG_RENDICIONES_CAJAS_LUBRIMEC.INSERTAR(
        p_token => l_token, p_cod_empresa => TO_NUMBER(:cod_empresa), p_fecha => :fecha,
        p_total_caja_anterior => TO_NUMBER(:total_caja_anterior),
        p_total_venta => TO_NUMBER(:total_venta),
        p_total_retiro => TO_NUMBER(:total_retiro),
        p_total_caja => TO_NUMBER(:total_caja),
        p_total_pago => TO_NUMBER(:total_pago),
        p_observacion => :observacion);
END;
~');
  ORDS.DEFINE_PARAMETER(p_module_name => 'lubrimec', p_pattern => 'rendiciones', p_method => 'POST',
      p_name => 'Authorization', p_bind_variable_name => 'authorization',
      p_source_type => 'HEADER', p_param_type => 'STRING', p_access_method => 'IN');

  ----------------------------------------------------------------------------
  -- /rendiciones/sugeridos  (segmento fijo, prioridad 1 para ganar a :id)
  ----------------------------------------------------------------------------
  BEGIN
    ORDS.DEFINE_TEMPLATE(p_module_name => 'lubrimec', p_pattern => 'rendiciones/sugeridos',
        p_priority => 1, p_etag_type => 'HASH', p_comments => NULL);
  EXCEPTION WHEN OTHERS THEN NULL; END;

  ORDS.DEFINE_HANDLER(
      p_module_name => 'lubrimec', p_pattern => 'rendiciones/sugeridos', p_method => 'GET',
      p_source_type => 'plsql/block',
      p_source      => q'~
DECLARE
    l_token VARCHAR2(256); l_pos PLS_INTEGER;
    l_qs VARCHAR2(4000); l_cod_empresa VARCHAR2(20); l_fecha VARCHAR2(20);
    FUNCTION get_qs(p_qs IN VARCHAR2, p_key IN VARCHAR2) RETURN VARCHAR2 IS
        l_p PLS_INTEGER; l_e PLS_INTEGER; l_v VARCHAR2(4000);
    BEGIN
        l_p := INSTR('&' || p_qs, '&' || p_key || '=');
        IF l_p = 0 THEN RETURN NULL; END IF;
        l_p := l_p + LENGTH(p_key) + 1;
        l_e := INSTR(p_qs || '&', '&', l_p);
        l_v := SUBSTR(p_qs, l_p, l_e - l_p);
        l_v := REPLACE(l_v, '+', ' ');
        RETURN UTL_URL.UNESCAPE(l_v);
    END;
BEGIN
    OWA_UTIL.MIME_HEADER('application/json', FALSE);
    HTP.P('Access-Control-Allow-Origin: *');
    HTP.P('Access-Control-Allow-Methods: GET, OPTIONS');
    HTP.P('Access-Control-Allow-Headers: Authorization, Content-Type');
    OWA_UTIL.HTTP_HEADER_CLOSE;
    l_token := :authorization;
    IF l_token IS NOT NULL THEN
        l_pos := INSTR(UPPER(l_token), 'BEARER ');
        IF l_pos > 0 THEN l_token := TRIM(SUBSTR(l_token, l_pos + 7)); END IF;
    END IF;
    l_qs := OWA_UTIL.GET_CGI_ENV('QUERY_STRING');
    l_cod_empresa := get_qs(l_qs, 'cod_empresa');
    l_fecha       := get_qs(l_qs, 'fecha');
    PKG_RENDICIONES_CAJAS_LUBRIMEC.SUGERIDOS(
        p_token => l_token, p_cod_empresa => TO_NUMBER(l_cod_empresa), p_fecha => l_fecha);
END;
~');
  ORDS.DEFINE_PARAMETER(p_module_name => 'lubrimec', p_pattern => 'rendiciones/sugeridos', p_method => 'GET',
      p_name => 'Authorization', p_bind_variable_name => 'authorization',
      p_source_type => 'HEADER', p_param_type => 'STRING', p_access_method => 'IN');

  ----------------------------------------------------------------------------
  -- /rendiciones/:id  (item: GET obtener, PUT, DELETE)
  ----------------------------------------------------------------------------
  BEGIN
    ORDS.DEFINE_TEMPLATE(p_module_name => 'lubrimec', p_pattern => 'rendiciones/:id',
        p_priority => 0, p_etag_type => 'HASH', p_comments => NULL);
  EXCEPTION WHEN OTHERS THEN NULL; END;

  ORDS.DEFINE_HANDLER(
      p_module_name => 'lubrimec', p_pattern => 'rendiciones/:id', p_method => 'GET',
      p_source_type => 'plsql/block',
      p_source      => q'~
DECLARE
    l_token VARCHAR2(256); l_pos PLS_INTEGER;
    l_qs VARCHAR2(4000); l_cod_empresa VARCHAR2(20);
    FUNCTION get_qs(p_qs IN VARCHAR2, p_key IN VARCHAR2) RETURN VARCHAR2 IS
        l_p PLS_INTEGER; l_e PLS_INTEGER; l_v VARCHAR2(4000);
    BEGIN
        l_p := INSTR('&' || p_qs, '&' || p_key || '=');
        IF l_p = 0 THEN RETURN NULL; END IF;
        l_p := l_p + LENGTH(p_key) + 1;
        l_e := INSTR(p_qs || '&', '&', l_p);
        l_v := SUBSTR(p_qs, l_p, l_e - l_p);
        l_v := REPLACE(l_v, '+', ' ');
        RETURN UTL_URL.UNESCAPE(l_v);
    END;
BEGIN
    OWA_UTIL.MIME_HEADER('application/json', FALSE);
    HTP.P('Access-Control-Allow-Origin: *');
    HTP.P('Access-Control-Allow-Methods: GET, POST, PUT, DELETE, OPTIONS');
    HTP.P('Access-Control-Allow-Headers: Authorization, Content-Type');
    OWA_UTIL.HTTP_HEADER_CLOSE;
    l_token := :authorization;
    IF l_token IS NOT NULL THEN
        l_pos := INSTR(UPPER(l_token), 'BEARER ');
        IF l_pos > 0 THEN l_token := TRIM(SUBSTR(l_token, l_pos + 7)); END IF;
    END IF;
    l_qs := OWA_UTIL.GET_CGI_ENV('QUERY_STRING');
    l_cod_empresa := get_qs(l_qs, 'cod_empresa');
    PKG_RENDICIONES_CAJAS_LUBRIMEC.OBTENER(
        p_token => l_token, p_id_cierre => TO_NUMBER(:id),
        p_cod_empresa => TO_NUMBER(l_cod_empresa));
END;
~');
  ORDS.DEFINE_PARAMETER(p_module_name => 'lubrimec', p_pattern => 'rendiciones/:id', p_method => 'GET',
      p_name => 'Authorization', p_bind_variable_name => 'authorization',
      p_source_type => 'HEADER', p_param_type => 'STRING', p_access_method => 'IN');

  ORDS.DEFINE_HANDLER(
      p_module_name => 'lubrimec', p_pattern => 'rendiciones/:id', p_method => 'PUT',
      p_source_type => 'plsql/block',
      p_source      => q'~
DECLARE l_token VARCHAR2(256); l_pos PLS_INTEGER;
BEGIN
    OWA_UTIL.MIME_HEADER('application/json', FALSE);
    HTP.P('Access-Control-Allow-Origin: *');
    HTP.P('Access-Control-Allow-Methods: GET, POST, PUT, DELETE, OPTIONS');
    HTP.P('Access-Control-Allow-Headers: Authorization, Content-Type');
    OWA_UTIL.HTTP_HEADER_CLOSE;
    l_token := :authorization;
    IF l_token IS NOT NULL THEN
        l_pos := INSTR(UPPER(l_token), 'BEARER ');
        IF l_pos > 0 THEN l_token := TRIM(SUBSTR(l_token, l_pos + 7)); END IF;
    END IF;
    PKG_RENDICIONES_CAJAS_LUBRIMEC.ACTUALIZAR(
        p_token => l_token, p_id_cierre => TO_NUMBER(:id),
        p_cod_empresa => TO_NUMBER(:cod_empresa), p_fecha => :fecha,
        p_total_caja_anterior => TO_NUMBER(:total_caja_anterior),
        p_total_venta => TO_NUMBER(:total_venta),
        p_total_retiro => TO_NUMBER(:total_retiro),
        p_total_caja => TO_NUMBER(:total_caja),
        p_total_pago => TO_NUMBER(:total_pago),
        p_observacion => :observacion);
END;
~');
  ORDS.DEFINE_PARAMETER(p_module_name => 'lubrimec', p_pattern => 'rendiciones/:id', p_method => 'PUT',
      p_name => 'Authorization', p_bind_variable_name => 'authorization',
      p_source_type => 'HEADER', p_param_type => 'STRING', p_access_method => 'IN');

  ORDS.DEFINE_HANDLER(
      p_module_name => 'lubrimec', p_pattern => 'rendiciones/:id', p_method => 'DELETE',
      p_source_type => 'plsql/block',
      p_source      => q'~
DECLARE
    l_token VARCHAR2(256); l_pos PLS_INTEGER;
    l_qs VARCHAR2(4000); l_cod_empresa VARCHAR2(20);
    FUNCTION get_qs(p_qs IN VARCHAR2, p_key IN VARCHAR2) RETURN VARCHAR2 IS
        l_p PLS_INTEGER; l_e PLS_INTEGER; l_v VARCHAR2(4000);
    BEGIN
        l_p := INSTR('&' || p_qs, '&' || p_key || '=');
        IF l_p = 0 THEN RETURN NULL; END IF;
        l_p := l_p + LENGTH(p_key) + 1;
        l_e := INSTR(p_qs || '&', '&', l_p);
        l_v := SUBSTR(p_qs, l_p, l_e - l_p);
        l_v := REPLACE(l_v, '+', ' ');
        RETURN UTL_URL.UNESCAPE(l_v);
    END;
BEGIN
    OWA_UTIL.MIME_HEADER('application/json', FALSE);
    HTP.P('Access-Control-Allow-Origin: *');
    HTP.P('Access-Control-Allow-Methods: GET, POST, PUT, DELETE, OPTIONS');
    HTP.P('Access-Control-Allow-Headers: Authorization, Content-Type');
    OWA_UTIL.HTTP_HEADER_CLOSE;
    l_token := :authorization;
    IF l_token IS NOT NULL THEN
        l_pos := INSTR(UPPER(l_token), 'BEARER ');
        IF l_pos > 0 THEN l_token := TRIM(SUBSTR(l_token, l_pos + 7)); END IF;
    END IF;
    l_qs := OWA_UTIL.GET_CGI_ENV('QUERY_STRING');
    l_cod_empresa := get_qs(l_qs, 'cod_empresa');
    PKG_RENDICIONES_CAJAS_LUBRIMEC.ELIMINAR(
        p_token => l_token, p_id_cierre => TO_NUMBER(:id),
        p_cod_empresa => TO_NUMBER(l_cod_empresa));
END;
~');
  ORDS.DEFINE_PARAMETER(p_module_name => 'lubrimec', p_pattern => 'rendiciones/:id', p_method => 'DELETE',
      p_name => 'Authorization', p_bind_variable_name => 'authorization',
      p_source_type => 'HEADER', p_param_type => 'STRING', p_access_method => 'IN');

  COMMIT;
EXCEPTION
  WHEN OTHERS THEN
    ROLLBACK;
    RAISE;
END;
/
