--------------------------------------------------------------------------------
-- TABLA_DESCUENTOS (pagina APEX 106) — paquete CRUD + endpoints ORDS.
-- Ejecutar completo como el esquema JOSEGALVEZ. Requiere PKG_AUTH_LUBRIMEC.
--
-- Descuentos escalonados por monto. PK id_tabla GENERATED BY DEFAULT AS IDENTITY
-- (no se pasa en el INSERT, se devuelve con RETURNING). SIN cod_empresa (global).
-- Todos NOT NULL: monto_desde, monto_hasta, porcentaje, venta_x, fecha_desde.
-- venta_x se calcula 1 - porcentaje/100 (el front lo manda; el back no lo recalcula).
-- rentabilidad_70 (70 - porcentaje) es solo display en la grilla, no se persiste.
--
-- === 1) PAQUETE PKG_TABLA_DESCUENTOS_LUBRIMEC ==============================
--------------------------------------------------------------------------------

CREATE OR REPLACE PACKAGE PKG_TABLA_DESCUENTOS_LUBRIMEC AS

  PROCEDURE LISTAR(p_token IN VARCHAR2);
  PROCEDURE OBTENER(p_token IN VARCHAR2, p_id IN NUMBER);
  PROCEDURE INSERTAR(
      p_token IN VARCHAR2, p_monto_desde IN NUMBER, p_monto_hasta IN NUMBER,
      p_porcentaje IN NUMBER, p_venta_x IN NUMBER, p_fecha_desde IN VARCHAR2);
  PROCEDURE ACTUALIZAR(
      p_token IN VARCHAR2, p_id IN NUMBER, p_monto_desde IN NUMBER, p_monto_hasta IN NUMBER,
      p_porcentaje IN NUMBER, p_venta_x IN NUMBER, p_fecha_desde IN VARCHAR2);
  PROCEDURE ELIMINAR(p_token IN VARCHAR2, p_id IN NUMBER);

END PKG_TABLA_DESCUENTOS_LUBRIMEC;
/

CREATE OR REPLACE PACKAGE BODY PKG_TABLA_DESCUENTOS_LUBRIMEC AS

  PROCEDURE p_error(p_status IN NUMBER, p_reason IN VARCHAR2, p_message IN VARCHAR2) IS
  BEGIN
    OWA_UTIL.STATUS_LINE(p_status, p_reason, FALSE);
    APEX_JSON.OPEN_OBJECT;
    APEX_JSON.WRITE('success', FALSE);
    APEX_JSON.WRITE('message', p_message);
    APEX_JSON.CLOSE_OBJECT;
  END p_error;

  FUNCTION f_usuario(p_token IN VARCHAR2) RETURN VARCHAR2 IS
  BEGIN
    RETURN PKG_AUTH_LUBRIMEC.VALIDAR_TOKEN(p_token);
  END f_usuario;

  --------------------------------------------------------------------------
  -- LISTAR (rentabilidad_70 = 70 - porcentaje, solo lectura)
  --------------------------------------------------------------------------
  PROCEDURE LISTAR(p_token IN VARCHAR2) IS
    l_usuario VARCHAR2(255);
  BEGIN
    l_usuario := f_usuario(p_token);
    IF l_usuario IS NULL THEN
      p_error(401, 'Unauthorized', 'Token invalido o expirado');
      RETURN;
    END IF;

    APEX_JSON.OPEN_OBJECT;
    APEX_JSON.WRITE('success', TRUE);
    APEX_JSON.OPEN_ARRAY('data');
    FOR r IN (
        SELECT id_tabla, monto_desde, monto_hasta, porcentaje, venta_x, fecha_desde,
               (70 - porcentaje) AS rentabilidad_70
          FROM tabla_descuentos
         ORDER BY monto_desde
    ) LOOP
      APEX_JSON.OPEN_OBJECT;
      APEX_JSON.WRITE('id_tabla', r.id_tabla);
      APEX_JSON.WRITE('monto_desde', r.monto_desde);
      APEX_JSON.WRITE('monto_hasta', r.monto_hasta);
      APEX_JSON.WRITE('porcentaje', r.porcentaje);
      APEX_JSON.WRITE('venta_x', r.venta_x);
      APEX_JSON.WRITE('fecha_desde', TO_CHAR(r.fecha_desde, 'YYYY-MM-DD'));
      APEX_JSON.WRITE('rentabilidad_70', r.rentabilidad_70);
      APEX_JSON.CLOSE_OBJECT;
    END LOOP;
    APEX_JSON.CLOSE_ARRAY;
    APEX_JSON.CLOSE_OBJECT;
  EXCEPTION
    WHEN OTHERS THEN
      p_error(500, 'Internal Server Error', 'Error: ' || SQLERRM);
  END LISTAR;

  --------------------------------------------------------------------------
  -- OBTENER
  --------------------------------------------------------------------------
  PROCEDURE OBTENER(p_token IN VARCHAR2, p_id IN NUMBER) IS
    l_usuario     VARCHAR2(255);
    l_monto_desde tabla_descuentos.monto_desde%TYPE;
    l_monto_hasta tabla_descuentos.monto_hasta%TYPE;
    l_porcentaje  tabla_descuentos.porcentaje%TYPE;
    l_venta_x     tabla_descuentos.venta_x%TYPE;
    l_fecha_desde tabla_descuentos.fecha_desde%TYPE;
  BEGIN
    l_usuario := f_usuario(p_token);
    IF l_usuario IS NULL THEN
      p_error(401, 'Unauthorized', 'Token invalido o expirado');
      RETURN;
    END IF;

    BEGIN
      SELECT monto_desde, monto_hasta, porcentaje, venta_x, fecha_desde
        INTO l_monto_desde, l_monto_hasta, l_porcentaje, l_venta_x, l_fecha_desde
        FROM tabla_descuentos
       WHERE id_tabla = p_id;
    EXCEPTION
      WHEN NO_DATA_FOUND THEN
        p_error(404, 'Not Found', 'Descuento no encontrado');
        RETURN;
    END;

    APEX_JSON.OPEN_OBJECT;
    APEX_JSON.WRITE('success', TRUE);
    APEX_JSON.OPEN_OBJECT('data');
    APEX_JSON.WRITE('id_tabla', p_id);
    APEX_JSON.WRITE('monto_desde', l_monto_desde);
    APEX_JSON.WRITE('monto_hasta', l_monto_hasta);
    APEX_JSON.WRITE('porcentaje', l_porcentaje);
    APEX_JSON.WRITE('venta_x', l_venta_x);
    APEX_JSON.WRITE('fecha_desde', TO_CHAR(l_fecha_desde, 'YYYY-MM-DD'));
    APEX_JSON.WRITE('rentabilidad_70', 70 - l_porcentaje);
    APEX_JSON.CLOSE_OBJECT;
    APEX_JSON.CLOSE_OBJECT;
  EXCEPTION
    WHEN OTHERS THEN
      p_error(500, 'Internal Server Error', 'Error: ' || SQLERRM);
  END OBTENER;

  --------------------------------------------------------------------------
  -- INSERTAR (PK IDENTITY; RETURNING). Todos los campos son obligatorios.
  --------------------------------------------------------------------------
  PROCEDURE INSERTAR(
      p_token IN VARCHAR2, p_monto_desde IN NUMBER, p_monto_hasta IN NUMBER,
      p_porcentaje IN NUMBER, p_venta_x IN NUMBER, p_fecha_desde IN VARCHAR2) IS
    l_usuario     VARCHAR2(255);
    l_id          tabla_descuentos.id_tabla%TYPE;
    l_fecha_desde DATE := TO_DATE(p_fecha_desde, 'YYYY-MM-DD');
  BEGIN
    l_usuario := f_usuario(p_token);
    IF l_usuario IS NULL THEN
      p_error(401, 'Unauthorized', 'Token invalido o expirado');
      RETURN;
    END IF;

    IF p_monto_desde IS NULL THEN
      p_error(400, 'Bad Request', 'El monto desde es obligatorio'); RETURN;
    END IF;
    IF p_monto_hasta IS NULL THEN
      p_error(400, 'Bad Request', 'El monto hasta es obligatorio'); RETURN;
    END IF;
    IF p_porcentaje IS NULL THEN
      p_error(400, 'Bad Request', 'El porcentaje es obligatorio'); RETURN;
    END IF;
    IF p_venta_x IS NULL THEN
      p_error(400, 'Bad Request', 'Venta X es obligatorio'); RETURN;
    END IF;
    IF l_fecha_desde IS NULL THEN
      p_error(400, 'Bad Request', 'La fecha desde es obligatoria'); RETURN;
    END IF;

    INSERT INTO tabla_descuentos (monto_desde, monto_hasta, porcentaje, venta_x, fecha_desde)
    VALUES (p_monto_desde, p_monto_hasta, p_porcentaje, p_venta_x, l_fecha_desde)
    RETURNING id_tabla INTO l_id;
    COMMIT;

    OWA_UTIL.STATUS_LINE(201, 'Created', FALSE);
    APEX_JSON.OPEN_OBJECT;
    APEX_JSON.WRITE('success', TRUE);
    APEX_JSON.WRITE('message', 'Descuento creado');
    APEX_JSON.WRITE('id_tabla', l_id);
    APEX_JSON.CLOSE_OBJECT;
  EXCEPTION
    WHEN OTHERS THEN
      ROLLBACK;
      p_error(500, 'Internal Server Error', 'Error: ' || SQLERRM);
  END INSERTAR;

  --------------------------------------------------------------------------
  -- ACTUALIZAR
  --------------------------------------------------------------------------
  PROCEDURE ACTUALIZAR(
      p_token IN VARCHAR2, p_id IN NUMBER, p_monto_desde IN NUMBER, p_monto_hasta IN NUMBER,
      p_porcentaje IN NUMBER, p_venta_x IN NUMBER, p_fecha_desde IN VARCHAR2) IS
    l_usuario     VARCHAR2(255);
    l_fecha_desde DATE := TO_DATE(p_fecha_desde, 'YYYY-MM-DD');
  BEGIN
    l_usuario := f_usuario(p_token);
    IF l_usuario IS NULL THEN
      p_error(401, 'Unauthorized', 'Token invalido o expirado');
      RETURN;
    END IF;

    IF p_monto_desde IS NULL THEN
      p_error(400, 'Bad Request', 'El monto desde es obligatorio'); RETURN;
    END IF;
    IF p_monto_hasta IS NULL THEN
      p_error(400, 'Bad Request', 'El monto hasta es obligatorio'); RETURN;
    END IF;
    IF p_porcentaje IS NULL THEN
      p_error(400, 'Bad Request', 'El porcentaje es obligatorio'); RETURN;
    END IF;
    IF p_venta_x IS NULL THEN
      p_error(400, 'Bad Request', 'Venta X es obligatorio'); RETURN;
    END IF;
    IF l_fecha_desde IS NULL THEN
      p_error(400, 'Bad Request', 'La fecha desde es obligatoria'); RETURN;
    END IF;

    UPDATE tabla_descuentos
       SET monto_desde = p_monto_desde,
           monto_hasta = p_monto_hasta,
           porcentaje  = p_porcentaje,
           venta_x     = p_venta_x,
           fecha_desde = l_fecha_desde
     WHERE id_tabla = p_id;

    IF SQL%ROWCOUNT = 0 THEN
      ROLLBACK;
      p_error(404, 'Not Found', 'Descuento no encontrado');
      RETURN;
    END IF;
    COMMIT;

    APEX_JSON.OPEN_OBJECT;
    APEX_JSON.WRITE('success', TRUE);
    APEX_JSON.WRITE('message', 'Descuento actualizado');
    APEX_JSON.CLOSE_OBJECT;
  EXCEPTION
    WHEN OTHERS THEN
      ROLLBACK;
      p_error(500, 'Internal Server Error', 'Error: ' || SQLERRM);
  END ACTUALIZAR;

  --------------------------------------------------------------------------
  -- ELIMINAR
  --------------------------------------------------------------------------
  PROCEDURE ELIMINAR(p_token IN VARCHAR2, p_id IN NUMBER) IS
    l_usuario VARCHAR2(255);
  BEGIN
    l_usuario := f_usuario(p_token);
    IF l_usuario IS NULL THEN
      p_error(401, 'Unauthorized', 'Token invalido o expirado');
      RETURN;
    END IF;

    DELETE FROM tabla_descuentos WHERE id_tabla = p_id;

    IF SQL%ROWCOUNT = 0 THEN
      ROLLBACK;
      p_error(404, 'Not Found', 'Descuento no encontrado');
      RETURN;
    END IF;
    COMMIT;

    APEX_JSON.OPEN_OBJECT;
    APEX_JSON.WRITE('success', TRUE);
    APEX_JSON.WRITE('message', 'Descuento eliminado');
    APEX_JSON.CLOSE_OBJECT;
  EXCEPTION
    WHEN OTHERS THEN
      ROLLBACK;
      p_error(500, 'Internal Server Error', 'Error: ' || SQLERRM);
  END ELIMINAR;

END PKG_TABLA_DESCUENTOS_LUBRIMEC;
/

--------------------------------------------------------------------------------
-- === 2) ENDPOINTS ORDS =====================================================
--
--   GET    /lubrimec/descuentos-escalonados       -> listar
--   GET    /lubrimec/descuentos-escalonados/:id    -> obtener
--   POST   /lubrimec/descuentos-escalonados        -> insertar
--   PUT    /lubrimec/descuentos-escalonados/:id     -> actualizar
--   DELETE /lubrimec/descuentos-escalonados/:id     -> eliminar
--------------------------------------------------------------------------------

BEGIN
  BEGIN ORDS.DELETE_HANDLER('lubrimec', 'descuentos-escalonados', 'GET');        EXCEPTION WHEN OTHERS THEN NULL; END;
  BEGIN ORDS.DELETE_HANDLER('lubrimec', 'descuentos-escalonados', 'POST');       EXCEPTION WHEN OTHERS THEN NULL; END;
  BEGIN ORDS.DELETE_HANDLER('lubrimec', 'descuentos-escalonados/:id', 'GET');    EXCEPTION WHEN OTHERS THEN NULL; END;
  BEGIN ORDS.DELETE_HANDLER('lubrimec', 'descuentos-escalonados/:id', 'PUT');    EXCEPTION WHEN OTHERS THEN NULL; END;
  BEGIN ORDS.DELETE_HANDLER('lubrimec', 'descuentos-escalonados/:id', 'DELETE'); EXCEPTION WHEN OTHERS THEN NULL; END;

  ----------------------------------------------------------------------------
  -- Plantilla coleccion: /descuentos-escalonados
  ----------------------------------------------------------------------------
  BEGIN
    ORDS.DEFINE_TEMPLATE(
        p_module_name => 'lubrimec',
        p_pattern     => 'descuentos-escalonados',
        p_priority    => 0,
        p_etag_type   => 'HASH',
        p_comments    => NULL);
  EXCEPTION WHEN OTHERS THEN NULL; END;

  -- GET /descuentos-escalonados  -> listar
  ORDS.DEFINE_HANDLER(
      p_module_name => 'lubrimec',
      p_pattern     => 'descuentos-escalonados',
      p_method      => 'GET',
      p_source_type => 'plsql/block',
      p_source      => q'~
DECLARE l_token VARCHAR2(256); l_pos PLS_INTEGER;
BEGIN
    OWA_UTIL.MIME_HEADER('application/json', FALSE);
    HTP.P('Access-Control-Allow-Origin: *');
    HTP.P('Access-Control-Allow-Methods: GET, POST, PUT, DELETE, OPTIONS');
    HTP.P('Access-Control-Allow-Headers: Authorization, Content-Type');
    OWA_UTIL.HTTP_HEADER_CLOSE;
    l_token := :authorization;
    IF l_token IS NOT NULL THEN
        l_pos := INSTR(UPPER(l_token), 'BEARER ');
        IF l_pos > 0 THEN l_token := TRIM(SUBSTR(l_token, l_pos + 7)); END IF;
    END IF;
    PKG_TABLA_DESCUENTOS_LUBRIMEC.LISTAR(p_token => l_token);
END;
~');

  ORDS.DEFINE_PARAMETER(
      p_module_name        => 'lubrimec',
      p_pattern            => 'descuentos-escalonados',
      p_method             => 'GET',
      p_name               => 'Authorization',
      p_bind_variable_name => 'authorization',
      p_source_type        => 'HEADER',
      p_param_type         => 'STRING',
      p_access_method      => 'IN');

  -- POST /descuentos-escalonados  -> insertar
  ORDS.DEFINE_HANDLER(
      p_module_name => 'lubrimec',
      p_pattern     => 'descuentos-escalonados',
      p_method      => 'POST',
      p_source_type => 'plsql/block',
      p_source      => q'~
DECLARE l_token VARCHAR2(256); l_pos PLS_INTEGER;
BEGIN
    OWA_UTIL.MIME_HEADER('application/json', FALSE);
    HTP.P('Access-Control-Allow-Origin: *');
    HTP.P('Access-Control-Allow-Methods: GET, POST, PUT, DELETE, OPTIONS');
    HTP.P('Access-Control-Allow-Headers: Authorization, Content-Type');
    OWA_UTIL.HTTP_HEADER_CLOSE;
    l_token := :authorization;
    IF l_token IS NOT NULL THEN
        l_pos := INSTR(UPPER(l_token), 'BEARER ');
        IF l_pos > 0 THEN l_token := TRIM(SUBSTR(l_token, l_pos + 7)); END IF;
    END IF;
    PKG_TABLA_DESCUENTOS_LUBRIMEC.INSERTAR(
        p_token => l_token, p_monto_desde => TO_NUMBER(:monto_desde),
        p_monto_hasta => TO_NUMBER(:monto_hasta), p_porcentaje => TO_NUMBER(:porcentaje),
        p_venta_x => TO_NUMBER(:venta_x), p_fecha_desde => :fecha_desde);
END;
~');

  ORDS.DEFINE_PARAMETER(
      p_module_name        => 'lubrimec',
      p_pattern            => 'descuentos-escalonados',
      p_method             => 'POST',
      p_name               => 'Authorization',
      p_bind_variable_name => 'authorization',
      p_source_type        => 'HEADER',
      p_param_type         => 'STRING',
      p_access_method      => 'IN');

  ----------------------------------------------------------------------------
  -- Plantilla item: /descuentos-escalonados/:id
  ----------------------------------------------------------------------------
  BEGIN
    ORDS.DEFINE_TEMPLATE(
        p_module_name => 'lubrimec',
        p_pattern     => 'descuentos-escalonados/:id',
        p_priority    => 0,
        p_etag_type   => 'HASH',
        p_comments    => NULL);
  EXCEPTION WHEN OTHERS THEN NULL; END;

  -- GET /descuentos-escalonados/:id  -> obtener
  ORDS.DEFINE_HANDLER(
      p_module_name => 'lubrimec',
      p_pattern     => 'descuentos-escalonados/:id',
      p_method      => 'GET',
      p_source_type => 'plsql/block',
      p_source      => q'~
DECLARE l_token VARCHAR2(256); l_pos PLS_INTEGER;
BEGIN
    OWA_UTIL.MIME_HEADER('application/json', FALSE);
    HTP.P('Access-Control-Allow-Origin: *');
    HTP.P('Access-Control-Allow-Methods: GET, POST, PUT, DELETE, OPTIONS');
    HTP.P('Access-Control-Allow-Headers: Authorization, Content-Type');
    OWA_UTIL.HTTP_HEADER_CLOSE;
    l_token := :authorization;
    IF l_token IS NOT NULL THEN
        l_pos := INSTR(UPPER(l_token), 'BEARER ');
        IF l_pos > 0 THEN l_token := TRIM(SUBSTR(l_token, l_pos + 7)); END IF;
    END IF;
    PKG_TABLA_DESCUENTOS_LUBRIMEC.OBTENER(p_token => l_token, p_id => TO_NUMBER(:id));
END;
~');

  ORDS.DEFINE_PARAMETER(
      p_module_name        => 'lubrimec',
      p_pattern            => 'descuentos-escalonados/:id',
      p_method             => 'GET',
      p_name               => 'Authorization',
      p_bind_variable_name => 'authorization',
      p_source_type        => 'HEADER',
      p_param_type         => 'STRING',
      p_access_method      => 'IN');

  -- PUT /descuentos-escalonados/:id  -> actualizar
  ORDS.DEFINE_HANDLER(
      p_module_name => 'lubrimec',
      p_pattern     => 'descuentos-escalonados/:id',
      p_method      => 'PUT',
      p_source_type => 'plsql/block',
      p_source      => q'~
DECLARE l_token VARCHAR2(256); l_pos PLS_INTEGER;
BEGIN
    OWA_UTIL.MIME_HEADER('application/json', FALSE);
    HTP.P('Access-Control-Allow-Origin: *');
    HTP.P('Access-Control-Allow-Methods: GET, POST, PUT, DELETE, OPTIONS');
    HTP.P('Access-Control-Allow-Headers: Authorization, Content-Type');
    OWA_UTIL.HTTP_HEADER_CLOSE;
    l_token := :authorization;
    IF l_token IS NOT NULL THEN
        l_pos := INSTR(UPPER(l_token), 'BEARER ');
        IF l_pos > 0 THEN l_token := TRIM(SUBSTR(l_token, l_pos + 7)); END IF;
    END IF;
    PKG_TABLA_DESCUENTOS_LUBRIMEC.ACTUALIZAR(
        p_token => l_token, p_id => TO_NUMBER(:id), p_monto_desde => TO_NUMBER(:monto_desde),
        p_monto_hasta => TO_NUMBER(:monto_hasta), p_porcentaje => TO_NUMBER(:porcentaje),
        p_venta_x => TO_NUMBER(:venta_x), p_fecha_desde => :fecha_desde);
END;
~');

  ORDS.DEFINE_PARAMETER(
      p_module_name        => 'lubrimec',
      p_pattern            => 'descuentos-escalonados/:id',
      p_method             => 'PUT',
      p_name               => 'Authorization',
      p_bind_variable_name => 'authorization',
      p_source_type        => 'HEADER',
      p_param_type         => 'STRING',
      p_access_method      => 'IN');

  -- DELETE /descuentos-escalonados/:id  -> eliminar
  ORDS.DEFINE_HANDLER(
      p_module_name => 'lubrimec',
      p_pattern     => 'descuentos-escalonados/:id',
      p_method      => 'DELETE',
      p_source_type => 'plsql/block',
      p_source      => q'~
DECLARE l_token VARCHAR2(256); l_pos PLS_INTEGER;
BEGIN
    OWA_UTIL.MIME_HEADER('application/json', FALSE);
    HTP.P('Access-Control-Allow-Origin: *');
    HTP.P('Access-Control-Allow-Methods: GET, POST, PUT, DELETE, OPTIONS');
    HTP.P('Access-Control-Allow-Headers: Authorization, Content-Type');
    OWA_UTIL.HTTP_HEADER_CLOSE;
    l_token := :authorization;
    IF l_token IS NOT NULL THEN
        l_pos := INSTR(UPPER(l_token), 'BEARER ');
        IF l_pos > 0 THEN l_token := TRIM(SUBSTR(l_token, l_pos + 7)); END IF;
    END IF;
    PKG_TABLA_DESCUENTOS_LUBRIMEC.ELIMINAR(p_token => l_token, p_id => TO_NUMBER(:id));
END;
~');

  ORDS.DEFINE_PARAMETER(
      p_module_name        => 'lubrimec',
      p_pattern            => 'descuentos-escalonados/:id',
      p_method             => 'DELETE',
      p_name               => 'Authorization',
      p_bind_variable_name => 'authorization',
      p_source_type        => 'HEADER',
      p_param_type         => 'STRING',
      p_access_method      => 'IN');

  COMMIT;
EXCEPTION
  WHEN OTHERS THEN
    ROLLBACK;
    RAISE;
END;
/
