--------------------------------------------------------------------------------
-- TALONARIOS (pagina APEX 44) — paquete CRUD + endpoints ORDS.
-- Ejecutar completo como el esquema JOSEGALVEZ. Requiere PKG_AUTH_LUBRIMEC.
--
-- PK id_talonario GENERATED BY DEFAULT AS IDENTITY (no se pasa en el INSERT).
-- Multiempresa: listar filtra por cod_empresa (?cod_empresa=:n).
-- fecha_vigencia / fecha_vencimiento intercambiadas como texto 'YYYY-MM-DD'.
-- ind_ncr = 'S'/'N' (1 char). activo = 'S'/'N'.
--
-- === 1) PAQUETE PKG_TALONARIOS_LUBRIMEC ====================================
--------------------------------------------------------------------------------

CREATE OR REPLACE PACKAGE PKG_TALONARIOS_LUBRIMEC AS

  PROCEDURE LISTAR(p_token IN VARCHAR2, p_cod_empresa IN NUMBER);
  PROCEDURE OBTENER(p_token IN VARCHAR2, p_id_talonario IN NUMBER);
  PROCEDURE INSERTAR(
      p_token IN VARCHAR2, p_ser_timbrado IN VARCHAR2, p_nro_timbrado IN NUMBER,
      p_fecha_vigencia IN VARCHAR2, p_fecha_vencimiento IN VARCHAR2,
      p_nro_inicial IN NUMBER, p_nro_final IN NUMBER, p_ind_ncr IN VARCHAR2,
      p_cod_empresa IN NUMBER, p_activo IN VARCHAR2);
  PROCEDURE ACTUALIZAR(
      p_token IN VARCHAR2, p_id_talonario IN NUMBER, p_ser_timbrado IN VARCHAR2,
      p_nro_timbrado IN NUMBER, p_fecha_vigencia IN VARCHAR2, p_fecha_vencimiento IN VARCHAR2,
      p_nro_inicial IN NUMBER, p_nro_final IN NUMBER, p_ind_ncr IN VARCHAR2,
      p_cod_empresa IN NUMBER, p_activo IN VARCHAR2);
  PROCEDURE ELIMINAR(p_token IN VARCHAR2, p_id_talonario IN NUMBER);

END PKG_TALONARIOS_LUBRIMEC;
/

CREATE OR REPLACE PACKAGE BODY PKG_TALONARIOS_LUBRIMEC AS

  PROCEDURE p_error(p_status IN NUMBER, p_reason IN VARCHAR2, p_message IN VARCHAR2) IS
  BEGIN
    OWA_UTIL.STATUS_LINE(p_status, p_reason, FALSE);
    APEX_JSON.OPEN_OBJECT;
    APEX_JSON.WRITE('success', FALSE);
    APEX_JSON.WRITE('message', p_message);
    APEX_JSON.CLOSE_OBJECT;
  END p_error;

  FUNCTION f_usuario(p_token IN VARCHAR2) RETURN VARCHAR2 IS
  BEGIN
    RETURN PKG_AUTH_LUBRIMEC.VALIDAR_TOKEN(p_token);
  END f_usuario;

  -- Texto 'YYYY-MM-DD' -> DATE (NULL si vacio o no parseable).
  FUNCTION f_fecha(p_txt IN VARCHAR2) RETURN DATE IS
  BEGIN
    IF p_txt IS NULL OR TRIM(p_txt) IS NULL THEN RETURN NULL; END IF;
    RETURN TO_DATE(p_txt, 'YYYY-MM-DD');
  EXCEPTION
    WHEN OTHERS THEN RETURN NULL;
  END f_fecha;

  -- Escribe una fila de talonarios como objeto JSON (reusado en LISTAR/OBTENER).
  PROCEDURE w_talonario(
      p_id_talonario     NUMBER,   p_ser_timbrado VARCHAR2, p_nro_timbrado NUMBER,
      p_fecha_vigencia   DATE,     p_fecha_vencimiento DATE,
      p_nro_inicial      NUMBER,   p_nro_final NUMBER,      p_ind_ncr VARCHAR2,
      p_cod_empresa      NUMBER,   p_activo VARCHAR2) IS
  BEGIN
    APEX_JSON.OPEN_OBJECT;
    APEX_JSON.WRITE('id_talonario', p_id_talonario);
    APEX_JSON.WRITE('ser_timbrado', p_ser_timbrado);
    APEX_JSON.WRITE('nro_timbrado', p_nro_timbrado);
    APEX_JSON.WRITE('fecha_vigencia',
        CASE WHEN p_fecha_vigencia IS NULL THEN NULL
             ELSE TO_CHAR(p_fecha_vigencia, 'YYYY-MM-DD') END);
    APEX_JSON.WRITE('fecha_vencimiento',
        CASE WHEN p_fecha_vencimiento IS NULL THEN NULL
             ELSE TO_CHAR(p_fecha_vencimiento, 'YYYY-MM-DD') END);
    APEX_JSON.WRITE('nro_inicial', p_nro_inicial);
    APEX_JSON.WRITE('nro_final', p_nro_final);
    APEX_JSON.WRITE('ind_ncr', p_ind_ncr);
    APEX_JSON.WRITE('cod_empresa', p_cod_empresa);
    APEX_JSON.WRITE('activo', p_activo);
    APEX_JSON.CLOSE_OBJECT;
  END w_talonario;

  --------------------------------------------------------------------------
  -- LISTAR
  --------------------------------------------------------------------------
  PROCEDURE LISTAR(p_token IN VARCHAR2, p_cod_empresa IN NUMBER) IS
    l_usuario VARCHAR2(255);
  BEGIN
    l_usuario := f_usuario(p_token);
    IF l_usuario IS NULL THEN
      p_error(401, 'Unauthorized', 'Token invalido o expirado');
      RETURN;
    END IF;

    APEX_JSON.OPEN_OBJECT;
    APEX_JSON.WRITE('success', TRUE);
    APEX_JSON.OPEN_ARRAY('data');
    FOR r IN (
        SELECT id_talonario, ser_timbrado, nro_timbrado, fecha_vigencia,
               fecha_vencimiento, nro_inicial, nro_final, ind_ncr, cod_empresa, activo
          FROM talonarios
         WHERE (p_cod_empresa IS NULL OR cod_empresa = p_cod_empresa)
         ORDER BY id_talonario DESC
    ) LOOP
      w_talonario(r.id_talonario, r.ser_timbrado, r.nro_timbrado, r.fecha_vigencia,
                  r.fecha_vencimiento, r.nro_inicial, r.nro_final, r.ind_ncr,
                  r.cod_empresa, r.activo);
    END LOOP;
    APEX_JSON.CLOSE_ARRAY;
    APEX_JSON.CLOSE_OBJECT;
  EXCEPTION
    WHEN OTHERS THEN
      p_error(500, 'Internal Server Error', 'Error: ' || SQLERRM);
  END LISTAR;

  --------------------------------------------------------------------------
  -- OBTENER
  --------------------------------------------------------------------------
  PROCEDURE OBTENER(p_token IN VARCHAR2, p_id_talonario IN NUMBER) IS
    l_usuario VARCHAR2(255);
    r         talonarios%ROWTYPE;
  BEGIN
    l_usuario := f_usuario(p_token);
    IF l_usuario IS NULL THEN
      p_error(401, 'Unauthorized', 'Token invalido o expirado');
      RETURN;
    END IF;

    BEGIN
      SELECT * INTO r FROM talonarios WHERE id_talonario = p_id_talonario;
    EXCEPTION
      WHEN NO_DATA_FOUND THEN
        p_error(404, 'Not Found', 'Talonario no encontrado');
        RETURN;
    END;

    APEX_JSON.OPEN_OBJECT;
    APEX_JSON.WRITE('success', TRUE);
    APEX_JSON.OPEN_OBJECT('data');
    APEX_JSON.WRITE('id_talonario', r.id_talonario);
    APEX_JSON.WRITE('ser_timbrado', r.ser_timbrado);
    APEX_JSON.WRITE('nro_timbrado', r.nro_timbrado);
    APEX_JSON.WRITE('fecha_vigencia',
        CASE WHEN r.fecha_vigencia IS NULL THEN NULL
             ELSE TO_CHAR(r.fecha_vigencia, 'YYYY-MM-DD') END);
    APEX_JSON.WRITE('fecha_vencimiento',
        CASE WHEN r.fecha_vencimiento IS NULL THEN NULL
             ELSE TO_CHAR(r.fecha_vencimiento, 'YYYY-MM-DD') END);
    APEX_JSON.WRITE('nro_inicial', r.nro_inicial);
    APEX_JSON.WRITE('nro_final', r.nro_final);
    APEX_JSON.WRITE('ind_ncr', r.ind_ncr);
    APEX_JSON.WRITE('cod_empresa', r.cod_empresa);
    APEX_JSON.WRITE('activo', r.activo);
    APEX_JSON.CLOSE_OBJECT;
    APEX_JSON.CLOSE_OBJECT;
  EXCEPTION
    WHEN OTHERS THEN
      p_error(500, 'Internal Server Error', 'Error: ' || SQLERRM);
  END OBTENER;

  --------------------------------------------------------------------------
  -- INSERTAR (id por IDENTITY)
  --------------------------------------------------------------------------
  PROCEDURE INSERTAR(
      p_token IN VARCHAR2, p_ser_timbrado IN VARCHAR2, p_nro_timbrado IN NUMBER,
      p_fecha_vigencia IN VARCHAR2, p_fecha_vencimiento IN VARCHAR2,
      p_nro_inicial IN NUMBER, p_nro_final IN NUMBER, p_ind_ncr IN VARCHAR2,
      p_cod_empresa IN NUMBER, p_activo IN VARCHAR2) IS
    l_usuario      VARCHAR2(255);
    l_id_talonario talonarios.id_talonario%TYPE;
    l_fec_vig      DATE;
    l_fec_ven      DATE;
  BEGIN
    l_usuario := f_usuario(p_token);
    IF l_usuario IS NULL THEN
      p_error(401, 'Unauthorized', 'Token invalido o expirado');
      RETURN;
    END IF;

    IF p_ser_timbrado IS NULL THEN
      p_error(400, 'Bad Request', 'La serie del timbrado es obligatoria');
      RETURN;
    END IF;
    IF p_nro_timbrado IS NULL THEN
      p_error(400, 'Bad Request', 'El numero de timbrado es obligatorio');
      RETURN;
    END IF;
    IF p_cod_empresa IS NULL THEN
      p_error(400, 'Bad Request', 'La empresa es obligatoria');
      RETURN;
    END IF;

    l_fec_vig := f_fecha(p_fecha_vigencia);
    l_fec_ven := f_fecha(p_fecha_vencimiento);

    INSERT INTO talonarios (
        ser_timbrado, nro_timbrado, fecha_vigencia, fecha_vencimiento,
        nro_inicial, nro_final, ind_ncr, cod_empresa, activo)
    VALUES (
        p_ser_timbrado, p_nro_timbrado, l_fec_vig, l_fec_ven,
        NVL(p_nro_inicial, 1), NVL(p_nro_final, 0), NVL(p_ind_ncr, 'N'),
        p_cod_empresa, NVL(p_activo, 'S'))
    RETURNING id_talonario INTO l_id_talonario;
    COMMIT;

    OWA_UTIL.STATUS_LINE(201, 'Created', FALSE);
    APEX_JSON.OPEN_OBJECT;
    APEX_JSON.WRITE('success', TRUE);
    APEX_JSON.WRITE('message', 'Talonario creado');
    APEX_JSON.WRITE('id_talonario', l_id_talonario);
    APEX_JSON.CLOSE_OBJECT;
  EXCEPTION
    WHEN OTHERS THEN
      ROLLBACK;
      p_error(500, 'Internal Server Error', 'Error: ' || SQLERRM);
  END INSERTAR;

  --------------------------------------------------------------------------
  -- ACTUALIZAR
  --------------------------------------------------------------------------
  PROCEDURE ACTUALIZAR(
      p_token IN VARCHAR2, p_id_talonario IN NUMBER, p_ser_timbrado IN VARCHAR2,
      p_nro_timbrado IN NUMBER, p_fecha_vigencia IN VARCHAR2, p_fecha_vencimiento IN VARCHAR2,
      p_nro_inicial IN NUMBER, p_nro_final IN NUMBER, p_ind_ncr IN VARCHAR2,
      p_cod_empresa IN NUMBER, p_activo IN VARCHAR2) IS
    l_usuario VARCHAR2(255);
    l_fec_vig DATE;
    l_fec_ven DATE;
  BEGIN
    l_usuario := f_usuario(p_token);
    IF l_usuario IS NULL THEN
      p_error(401, 'Unauthorized', 'Token invalido o expirado');
      RETURN;
    END IF;

    IF p_ser_timbrado IS NULL THEN
      p_error(400, 'Bad Request', 'La serie del timbrado es obligatoria');
      RETURN;
    END IF;
    IF p_nro_timbrado IS NULL THEN
      p_error(400, 'Bad Request', 'El numero de timbrado es obligatorio');
      RETURN;
    END IF;
    IF p_cod_empresa IS NULL THEN
      p_error(400, 'Bad Request', 'La empresa es obligatoria');
      RETURN;
    END IF;

    l_fec_vig := f_fecha(p_fecha_vigencia);
    l_fec_ven := f_fecha(p_fecha_vencimiento);

    UPDATE talonarios
       SET ser_timbrado      = p_ser_timbrado,
           nro_timbrado      = p_nro_timbrado,
           fecha_vigencia    = l_fec_vig,
           fecha_vencimiento = l_fec_ven,
           nro_inicial       = NVL(p_nro_inicial, 1),
           nro_final         = NVL(p_nro_final, 0),
           ind_ncr           = NVL(p_ind_ncr, 'N'),
           cod_empresa       = p_cod_empresa,
           activo            = NVL(p_activo, 'S')
     WHERE id_talonario = p_id_talonario;

    IF SQL%ROWCOUNT = 0 THEN
      ROLLBACK;
      p_error(404, 'Not Found', 'Talonario no encontrado');
      RETURN;
    END IF;
    COMMIT;

    APEX_JSON.OPEN_OBJECT;
    APEX_JSON.WRITE('success', TRUE);
    APEX_JSON.WRITE('message', 'Talonario actualizado');
    APEX_JSON.CLOSE_OBJECT;
  EXCEPTION
    WHEN OTHERS THEN
      ROLLBACK;
      p_error(500, 'Internal Server Error', 'Error: ' || SQLERRM);
  END ACTUALIZAR;

  --------------------------------------------------------------------------
  -- ELIMINAR
  --------------------------------------------------------------------------
  PROCEDURE ELIMINAR(p_token IN VARCHAR2, p_id_talonario IN NUMBER) IS
    l_usuario VARCHAR2(255);
  BEGIN
    l_usuario := f_usuario(p_token);
    IF l_usuario IS NULL THEN
      p_error(401, 'Unauthorized', 'Token invalido o expirado');
      RETURN;
    END IF;

    DELETE FROM talonarios WHERE id_talonario = p_id_talonario;

    IF SQL%ROWCOUNT = 0 THEN
      ROLLBACK;
      p_error(404, 'Not Found', 'Talonario no encontrado');
      RETURN;
    END IF;
    COMMIT;

    APEX_JSON.OPEN_OBJECT;
    APEX_JSON.WRITE('success', TRUE);
    APEX_JSON.WRITE('message', 'Talonario eliminado');
    APEX_JSON.CLOSE_OBJECT;
  EXCEPTION
    WHEN OTHERS THEN
      ROLLBACK;
      IF SQLCODE = -2292 THEN
        p_error(409, 'Conflict', 'No se puede eliminar: el talonario tiene documentos asociados');
      ELSE
        p_error(500, 'Internal Server Error', 'Error: ' || SQLERRM);
      END IF;
  END ELIMINAR;

END PKG_TALONARIOS_LUBRIMEC;
/

--------------------------------------------------------------------------------
-- === 2) ENDPOINTS ORDS =====================================================
--
--   GET    /lubrimec/talonarios?cod_empresa=:n  -> listar
--   GET    /lubrimec/talonarios/:id             -> obtener
--   POST   /lubrimec/talonarios                 -> insertar
--   PUT    /lubrimec/talonarios/:id             -> actualizar
--   DELETE /lubrimec/talonarios/:id             -> eliminar
--------------------------------------------------------------------------------

BEGIN
  BEGIN ORDS.DELETE_HANDLER('lubrimec', 'talonarios', 'GET');        EXCEPTION WHEN OTHERS THEN NULL; END;
  BEGIN ORDS.DELETE_HANDLER('lubrimec', 'talonarios', 'POST');       EXCEPTION WHEN OTHERS THEN NULL; END;
  BEGIN ORDS.DELETE_HANDLER('lubrimec', 'talonarios/:id', 'GET');    EXCEPTION WHEN OTHERS THEN NULL; END;
  BEGIN ORDS.DELETE_HANDLER('lubrimec', 'talonarios/:id', 'PUT');    EXCEPTION WHEN OTHERS THEN NULL; END;
  BEGIN ORDS.DELETE_HANDLER('lubrimec', 'talonarios/:id', 'DELETE'); EXCEPTION WHEN OTHERS THEN NULL; END;

  ----------------------------------------------------------------------------
  -- /talonarios
  ----------------------------------------------------------------------------
  BEGIN
    ORDS.DEFINE_TEMPLATE(p_module_name => 'lubrimec', p_pattern => 'talonarios',
        p_priority => 0, p_etag_type => 'HASH', p_comments => NULL);
  EXCEPTION WHEN OTHERS THEN NULL; END;

  ORDS.DEFINE_HANDLER(
      p_module_name => 'lubrimec', p_pattern => 'talonarios', p_method => 'GET',
      p_source_type => 'plsql/block',
      p_source      => q'~
DECLARE
  l_token VARCHAR2(256); l_pos PLS_INTEGER;
  l_qs    VARCHAR2(4000); l_ce VARCHAR2(100);
BEGIN
    OWA_UTIL.MIME_HEADER('application/json', FALSE);
    HTP.P('Access-Control-Allow-Origin: *');
    HTP.P('Access-Control-Allow-Methods: GET, POST, PUT, DELETE, OPTIONS');
    HTP.P('Access-Control-Allow-Headers: Authorization, Content-Type');
    OWA_UTIL.HTTP_HEADER_CLOSE;
    l_token := :authorization;
    IF l_token IS NOT NULL THEN
        l_pos := INSTR(UPPER(l_token), 'BEARER ');
        IF l_pos > 0 THEN l_token := TRIM(SUBSTR(l_token, l_pos + 7)); END IF;
    END IF;
    -- cod_empresa del query string (los query params no se auto-bindean fiable)
    l_qs := OWA_UTIL.GET_CGI_ENV('QUERY_STRING');
    IF l_qs IS NOT NULL THEN
        l_pos := INSTR(l_qs, 'cod_empresa=');
        IF l_pos > 0 THEN
            l_ce := SUBSTR(l_qs, l_pos + 12);
            l_pos := INSTR(l_ce, '&');
            IF l_pos > 0 THEN l_ce := SUBSTR(l_ce, 1, l_pos - 1); END IF;
        END IF;
    END IF;
    PKG_TALONARIOS_LUBRIMEC.LISTAR(
        p_token => l_token,
        p_cod_empresa => CASE WHEN l_ce IS NULL THEN NULL ELSE TO_NUMBER(l_ce) END);
END;
~');
  ORDS.DEFINE_PARAMETER(p_module_name => 'lubrimec', p_pattern => 'talonarios', p_method => 'GET',
      p_name => 'Authorization', p_bind_variable_name => 'authorization',
      p_source_type => 'HEADER', p_param_type => 'STRING', p_access_method => 'IN');

  ORDS.DEFINE_HANDLER(
      p_module_name => 'lubrimec', p_pattern => 'talonarios', p_method => 'POST',
      p_source_type => 'plsql/block',
      p_source      => q'~
DECLARE l_token VARCHAR2(256); l_pos PLS_INTEGER;
BEGIN
    OWA_UTIL.MIME_HEADER('application/json', FALSE);
    HTP.P('Access-Control-Allow-Origin: *');
    HTP.P('Access-Control-Allow-Methods: GET, POST, PUT, DELETE, OPTIONS');
    HTP.P('Access-Control-Allow-Headers: Authorization, Content-Type');
    OWA_UTIL.HTTP_HEADER_CLOSE;
    l_token := :authorization;
    IF l_token IS NOT NULL THEN
        l_pos := INSTR(UPPER(l_token), 'BEARER ');
        IF l_pos > 0 THEN l_token := TRIM(SUBSTR(l_token, l_pos + 7)); END IF;
    END IF;
    PKG_TALONARIOS_LUBRIMEC.INSERTAR(
        p_token => l_token, p_ser_timbrado => :ser_timbrado,
        p_nro_timbrado => TO_NUMBER(:nro_timbrado),
        p_fecha_vigencia => :fecha_vigencia, p_fecha_vencimiento => :fecha_vencimiento,
        p_nro_inicial => TO_NUMBER(:nro_inicial), p_nro_final => TO_NUMBER(:nro_final),
        p_ind_ncr => :ind_ncr, p_cod_empresa => TO_NUMBER(:cod_empresa), p_activo => :activo);
END;
~');
  ORDS.DEFINE_PARAMETER(p_module_name => 'lubrimec', p_pattern => 'talonarios', p_method => 'POST',
      p_name => 'Authorization', p_bind_variable_name => 'authorization',
      p_source_type => 'HEADER', p_param_type => 'STRING', p_access_method => 'IN');

  ----------------------------------------------------------------------------
  -- /talonarios/:id
  ----------------------------------------------------------------------------
  BEGIN
    ORDS.DEFINE_TEMPLATE(p_module_name => 'lubrimec', p_pattern => 'talonarios/:id',
        p_priority => 0, p_etag_type => 'HASH', p_comments => NULL);
  EXCEPTION WHEN OTHERS THEN NULL; END;

  ORDS.DEFINE_HANDLER(
      p_module_name => 'lubrimec', p_pattern => 'talonarios/:id', p_method => 'GET',
      p_source_type => 'plsql/block',
      p_source      => q'~
DECLARE l_token VARCHAR2(256); l_pos PLS_INTEGER;
BEGIN
    OWA_UTIL.MIME_HEADER('application/json', FALSE);
    HTP.P('Access-Control-Allow-Origin: *');
    HTP.P('Access-Control-Allow-Methods: GET, POST, PUT, DELETE, OPTIONS');
    HTP.P('Access-Control-Allow-Headers: Authorization, Content-Type');
    OWA_UTIL.HTTP_HEADER_CLOSE;
    l_token := :authorization;
    IF l_token IS NOT NULL THEN
        l_pos := INSTR(UPPER(l_token), 'BEARER ');
        IF l_pos > 0 THEN l_token := TRIM(SUBSTR(l_token, l_pos + 7)); END IF;
    END IF;
    PKG_TALONARIOS_LUBRIMEC.OBTENER(p_token => l_token, p_id_talonario => TO_NUMBER(:id));
END;
~');
  ORDS.DEFINE_PARAMETER(p_module_name => 'lubrimec', p_pattern => 'talonarios/:id', p_method => 'GET',
      p_name => 'Authorization', p_bind_variable_name => 'authorization',
      p_source_type => 'HEADER', p_param_type => 'STRING', p_access_method => 'IN');

  ORDS.DEFINE_HANDLER(
      p_module_name => 'lubrimec', p_pattern => 'talonarios/:id', p_method => 'PUT',
      p_source_type => 'plsql/block',
      p_source      => q'~
DECLARE l_token VARCHAR2(256); l_pos PLS_INTEGER;
BEGIN
    OWA_UTIL.MIME_HEADER('application/json', FALSE);
    HTP.P('Access-Control-Allow-Origin: *');
    HTP.P('Access-Control-Allow-Methods: GET, POST, PUT, DELETE, OPTIONS');
    HTP.P('Access-Control-Allow-Headers: Authorization, Content-Type');
    OWA_UTIL.HTTP_HEADER_CLOSE;
    l_token := :authorization;
    IF l_token IS NOT NULL THEN
        l_pos := INSTR(UPPER(l_token), 'BEARER ');
        IF l_pos > 0 THEN l_token := TRIM(SUBSTR(l_token, l_pos + 7)); END IF;
    END IF;
    PKG_TALONARIOS_LUBRIMEC.ACTUALIZAR(
        p_token => l_token, p_id_talonario => TO_NUMBER(:id),
        p_ser_timbrado => :ser_timbrado, p_nro_timbrado => TO_NUMBER(:nro_timbrado),
        p_fecha_vigencia => :fecha_vigencia, p_fecha_vencimiento => :fecha_vencimiento,
        p_nro_inicial => TO_NUMBER(:nro_inicial), p_nro_final => TO_NUMBER(:nro_final),
        p_ind_ncr => :ind_ncr, p_cod_empresa => TO_NUMBER(:cod_empresa), p_activo => :activo);
END;
~');
  ORDS.DEFINE_PARAMETER(p_module_name => 'lubrimec', p_pattern => 'talonarios/:id', p_method => 'PUT',
      p_name => 'Authorization', p_bind_variable_name => 'authorization',
      p_source_type => 'HEADER', p_param_type => 'STRING', p_access_method => 'IN');

  ORDS.DEFINE_HANDLER(
      p_module_name => 'lubrimec', p_pattern => 'talonarios/:id', p_method => 'DELETE',
      p_source_type => 'plsql/block',
      p_source      => q'~
DECLARE l_token VARCHAR2(256); l_pos PLS_INTEGER;
BEGIN
    OWA_UTIL.MIME_HEADER('application/json', FALSE);
    HTP.P('Access-Control-Allow-Origin: *');
    HTP.P('Access-Control-Allow-Methods: GET, POST, PUT, DELETE, OPTIONS');
    HTP.P('Access-Control-Allow-Headers: Authorization, Content-Type');
    OWA_UTIL.HTTP_HEADER_CLOSE;
    l_token := :authorization;
    IF l_token IS NOT NULL THEN
        l_pos := INSTR(UPPER(l_token), 'BEARER ');
        IF l_pos > 0 THEN l_token := TRIM(SUBSTR(l_token, l_pos + 7)); END IF;
    END IF;
    PKG_TALONARIOS_LUBRIMEC.ELIMINAR(p_token => l_token, p_id_talonario => TO_NUMBER(:id));
END;
~');
  ORDS.DEFINE_PARAMETER(p_module_name => 'lubrimec', p_pattern => 'talonarios/:id', p_method => 'DELETE',
      p_name => 'Authorization', p_bind_variable_name => 'authorization',
      p_source_type => 'HEADER', p_param_type => 'STRING', p_access_method => 'IN');

  COMMIT;
EXCEPTION
  WHEN OTHERS THEN
    ROLLBACK;
    RAISE;
END;
/
