--------------------------------------------------------------------------------
-- VENTAS_COBROS (pagina APEX 65) — paquete CRUD + endpoints ORDS.
-- Ejecutar completo como el esquema JOSEGALVEZ. Requiere PKG_AUTH_LUBRIMEC.
--
-- PK id_cobro GENERATED BY DEFAULT ON NULL AS IDENTITY (no se pasa en el INSERT).
-- La tabla NO tiene cod_empresa: se filtra por JOIN a VENTAS_CABECERA (id_factura).
-- NOT NULL: fecha, id_factura, id_forma, total, cod_moneda.
-- Opcionales: id_banco, nro_transaccion, observacion, efectivo_recibido,
--             efectivo_vuelto, ind_acreditado, monto_acreditado.
--
-- LISTAR/OBTENER hacen LEFT JOIN a VENTAS_CABECERA + PERSONAS (cliente) +
-- FORMA_COBRO_PAGO (desc_forma) + BANCOS (nombre_banco) + MONEDAS (desc_moneda).
-- BUSCAR_VENTAS alimenta el selector de factura (endpoint ventas/buscar).
--
-- === 1) PAQUETE PKG_VENTAS_COBROS_LUBRIMEC ================================
--------------------------------------------------------------------------------

CREATE OR REPLACE PACKAGE PKG_VENTAS_COBROS_LUBRIMEC AS

  PROCEDURE LISTAR(p_token IN VARCHAR2, p_cod_empresa IN NUMBER, p_id_factura IN NUMBER DEFAULT NULL);
  PROCEDURE OBTENER(p_token IN VARCHAR2, p_id_cobro IN NUMBER);
  PROCEDURE BUSCAR_VENTAS(p_token IN VARCHAR2, p_cod_empresa IN NUMBER, p_q IN VARCHAR2);
  PROCEDURE INSERTAR(
      p_token IN VARCHAR2, p_fecha IN VARCHAR2, p_id_factura IN NUMBER,
      p_id_forma IN NUMBER, p_id_banco IN NUMBER, p_nro_transaccion IN VARCHAR2,
      p_observacion IN VARCHAR2, p_total IN NUMBER, p_cod_moneda IN NUMBER,
      p_efectivo_recibido IN NUMBER, p_efectivo_vuelto IN NUMBER);
  PROCEDURE ACTUALIZAR(
      p_token IN VARCHAR2, p_id_cobro IN NUMBER, p_fecha IN VARCHAR2, p_id_factura IN NUMBER,
      p_id_forma IN NUMBER, p_id_banco IN NUMBER, p_nro_transaccion IN VARCHAR2,
      p_observacion IN VARCHAR2, p_total IN NUMBER, p_cod_moneda IN NUMBER,
      p_efectivo_recibido IN NUMBER, p_efectivo_vuelto IN NUMBER);
  PROCEDURE ELIMINAR(p_token IN VARCHAR2, p_id_cobro IN NUMBER);

END PKG_VENTAS_COBROS_LUBRIMEC;
/

CREATE OR REPLACE PACKAGE BODY PKG_VENTAS_COBROS_LUBRIMEC AS

  PROCEDURE p_error(p_status IN NUMBER, p_reason IN VARCHAR2, p_message IN VARCHAR2) IS
  BEGIN
    OWA_UTIL.STATUS_LINE(p_status, p_reason, FALSE);
    APEX_JSON.OPEN_OBJECT;
    APEX_JSON.WRITE('success', FALSE);
    APEX_JSON.WRITE('message', p_message);
    APEX_JSON.CLOSE_OBJECT;
  END p_error;

  FUNCTION f_usuario(p_token IN VARCHAR2) RETURN VARCHAR2 IS
  BEGIN
    RETURN PKG_AUTH_LUBRIMEC.VALIDAR_TOKEN(p_token);
  END f_usuario;

  --------------------------------------------------------------------------
  -- LISTAR (cobros de la empresa, via JOIN a VENTAS_CABECERA).
  -- p_id_factura opcional: cobros de UNA factura (modal de la pagina 60/110).
  --------------------------------------------------------------------------
  PROCEDURE LISTAR(p_token IN VARCHAR2, p_cod_empresa IN NUMBER, p_id_factura IN NUMBER DEFAULT NULL) IS
    l_usuario VARCHAR2(255);
  BEGIN
    l_usuario := f_usuario(p_token);
    IF l_usuario IS NULL THEN
      p_error(401, 'Unauthorized', 'Token invalido o expirado');
      RETURN;
    END IF;

    APEX_JSON.OPEN_OBJECT;
    APEX_JSON.WRITE('success', TRUE);
    APEX_JSON.OPEN_ARRAY('data');
    FOR r IN (
        SELECT a.id_cobro,
               TO_CHAR(a.fecha, 'YYYY-MM-DD') fecha,
               a.id_factura, a.id_forma, a.id_banco, a.nro_transaccion,
               a.observacion, a.total, a.cod_moneda,
               a.efectivo_recibido, a.efectivo_vuelto,
               b.tip_comprobante, b.ser_timbrado, b.nro_comprobante,
               NVL(pe.nombre_fantasia, pe.nombre) AS nombre_cliente,
               fp.descripcion AS descripcion_forma,
               ba.nombre      AS nombre_banco,
               mo.descripcion AS descripcion_moneda
          FROM ventas_cobros a
          JOIN ventas_cabecera b ON b.id_factura = a.id_factura
          LEFT JOIN personas pe  ON pe.cod_persona = b.cod_persona
                                 AND pe.cod_empresa = b.cod_empresa
          LEFT JOIN forma_cobro_pago fp ON fp.id_forma = a.id_forma
          LEFT JOIN bancos ba    ON ba.id_banco = a.id_banco
          LEFT JOIN monedas mo   ON mo.cod_moneda = a.cod_moneda
         WHERE b.cod_empresa = p_cod_empresa
           AND (p_id_factura IS NULL OR a.id_factura = p_id_factura)
         ORDER BY a.fecha DESC, a.id_cobro DESC
    ) LOOP
      APEX_JSON.OPEN_OBJECT;
      APEX_JSON.WRITE('id_cobro', r.id_cobro);
      APEX_JSON.WRITE('fecha', r.fecha);
      APEX_JSON.WRITE('id_factura', r.id_factura);
      APEX_JSON.WRITE('id_forma', r.id_forma);
      APEX_JSON.WRITE('id_banco', r.id_banco);
      APEX_JSON.WRITE('nro_transaccion', r.nro_transaccion);
      APEX_JSON.WRITE('observacion', r.observacion);
      APEX_JSON.WRITE('total', r.total);
      APEX_JSON.WRITE('cod_moneda', r.cod_moneda);
      APEX_JSON.WRITE('efectivo_recibido', r.efectivo_recibido);
      APEX_JSON.WRITE('efectivo_vuelto', r.efectivo_vuelto);
      APEX_JSON.WRITE('tip_comprobante', r.tip_comprobante);
      APEX_JSON.WRITE('ser_timbrado', r.ser_timbrado);
      APEX_JSON.WRITE('nro_comprobante', r.nro_comprobante);
      APEX_JSON.WRITE('nombre_cliente', r.nombre_cliente);
      APEX_JSON.WRITE('descripcion_forma', r.descripcion_forma);
      APEX_JSON.WRITE('nombre_banco', r.nombre_banco);
      APEX_JSON.WRITE('descripcion_moneda', r.descripcion_moneda);
      APEX_JSON.CLOSE_OBJECT;
    END LOOP;
    APEX_JSON.CLOSE_ARRAY;
    APEX_JSON.CLOSE_OBJECT;
  EXCEPTION
    WHEN OTHERS THEN
      p_error(500, 'Internal Server Error', 'Error: ' || SQLERRM);
  END LISTAR;

  --------------------------------------------------------------------------
  -- OBTENER
  --------------------------------------------------------------------------
  PROCEDURE OBTENER(p_token IN VARCHAR2, p_id_cobro IN NUMBER) IS
    l_usuario VARCHAR2(255);
    l_fecha             VARCHAR2(20);
    l_id_factura        ventas_cobros.id_factura%TYPE;
    l_id_forma          ventas_cobros.id_forma%TYPE;
    l_id_banco          ventas_cobros.id_banco%TYPE;
    l_nro_transaccion   ventas_cobros.nro_transaccion%TYPE;
    l_observacion       ventas_cobros.observacion%TYPE;
    l_total             ventas_cobros.total%TYPE;
    l_cod_moneda        ventas_cobros.cod_moneda%TYPE;
    l_efectivo_recibido ventas_cobros.efectivo_recibido%TYPE;
    l_efectivo_vuelto   ventas_cobros.efectivo_vuelto%TYPE;
    l_tip               ventas_cabecera.tip_comprobante%TYPE;
    l_ser               ventas_cabecera.ser_timbrado%TYPE;
    l_nro               ventas_cabecera.nro_comprobante%TYPE;
    l_cliente           VARCHAR2(500);
    l_desc_forma        forma_cobro_pago.descripcion%TYPE;
    l_nombre_banco      bancos.nombre%TYPE;
    l_desc_moneda       monedas.descripcion%TYPE;
  BEGIN
    l_usuario := f_usuario(p_token);
    IF l_usuario IS NULL THEN
      p_error(401, 'Unauthorized', 'Token invalido o expirado');
      RETURN;
    END IF;

    BEGIN
      SELECT TO_CHAR(a.fecha, 'YYYY-MM-DD'), a.id_factura, a.id_forma, a.id_banco,
             a.nro_transaccion, a.observacion, a.total, a.cod_moneda,
             a.efectivo_recibido, a.efectivo_vuelto,
             b.tip_comprobante, b.ser_timbrado, b.nro_comprobante,
             NVL(pe.nombre_fantasia, pe.nombre),
             fp.descripcion, ba.nombre, mo.descripcion
        INTO l_fecha, l_id_factura, l_id_forma, l_id_banco,
             l_nro_transaccion, l_observacion, l_total, l_cod_moneda,
             l_efectivo_recibido, l_efectivo_vuelto,
             l_tip, l_ser, l_nro, l_cliente, l_desc_forma, l_nombre_banco, l_desc_moneda
        FROM ventas_cobros a
        JOIN ventas_cabecera b ON b.id_factura = a.id_factura
        LEFT JOIN personas pe  ON pe.cod_persona = b.cod_persona
                               AND pe.cod_empresa = b.cod_empresa
        LEFT JOIN forma_cobro_pago fp ON fp.id_forma = a.id_forma
        LEFT JOIN bancos ba    ON ba.id_banco = a.id_banco
        LEFT JOIN monedas mo   ON mo.cod_moneda = a.cod_moneda
       WHERE a.id_cobro = p_id_cobro;
    EXCEPTION
      WHEN NO_DATA_FOUND THEN
        p_error(404, 'Not Found', 'Cobro no encontrado');
        RETURN;
    END;

    APEX_JSON.OPEN_OBJECT;
    APEX_JSON.WRITE('success', TRUE);
    APEX_JSON.OPEN_OBJECT('data');
    APEX_JSON.WRITE('id_cobro', p_id_cobro);
    APEX_JSON.WRITE('fecha', l_fecha);
    APEX_JSON.WRITE('id_factura', l_id_factura);
    APEX_JSON.WRITE('id_forma', l_id_forma);
    APEX_JSON.WRITE('id_banco', l_id_banco);
    APEX_JSON.WRITE('nro_transaccion', l_nro_transaccion);
    APEX_JSON.WRITE('observacion', l_observacion);
    APEX_JSON.WRITE('total', l_total);
    APEX_JSON.WRITE('cod_moneda', l_cod_moneda);
    APEX_JSON.WRITE('efectivo_recibido', l_efectivo_recibido);
    APEX_JSON.WRITE('efectivo_vuelto', l_efectivo_vuelto);
    APEX_JSON.WRITE('tip_comprobante', l_tip);
    APEX_JSON.WRITE('ser_timbrado', l_ser);
    APEX_JSON.WRITE('nro_comprobante', l_nro);
    APEX_JSON.WRITE('nombre_cliente', l_cliente);
    APEX_JSON.WRITE('descripcion_forma', l_desc_forma);
    APEX_JSON.WRITE('nombre_banco', l_nombre_banco);
    APEX_JSON.WRITE('descripcion_moneda', l_desc_moneda);
    APEX_JSON.CLOSE_OBJECT;
    APEX_JSON.CLOSE_OBJECT;
  EXCEPTION
    WHEN OTHERS THEN
      p_error(500, 'Internal Server Error', 'Error: ' || SQLERRM);
  END OBTENER;

  --------------------------------------------------------------------------
  -- BUSCAR_VENTAS (selector de factura). Hasta 30 facturas de la empresa que
  -- matcheen por id_factura / nro_comprobante / ser_timbrado / nombre cliente.
  --------------------------------------------------------------------------
  PROCEDURE BUSCAR_VENTAS(p_token IN VARCHAR2, p_cod_empresa IN NUMBER, p_q IN VARCHAR2) IS
    l_usuario VARCHAR2(255);
    l_q       VARCHAR2(400) := '%' || UPPER(TRIM(p_q)) || '%';
  BEGIN
    l_usuario := f_usuario(p_token);
    IF l_usuario IS NULL THEN
      p_error(401, 'Unauthorized', 'Token invalido o expirado');
      RETURN;
    END IF;

    APEX_JSON.OPEN_OBJECT;
    APEX_JSON.WRITE('success', TRUE);
    APEX_JSON.OPEN_ARRAY('data');
    FOR r IN (
        SELECT b.id_factura, b.nro_comprobante, b.ser_timbrado, b.tip_comprobante,
               b.fec_comprobante,
               NVL(pe.nombre_fantasia, pe.nombre) AS nombre_cliente
          FROM ventas_cabecera b
          LEFT JOIN personas pe ON pe.cod_persona = b.cod_persona
                                AND pe.cod_empresa = b.cod_empresa
         WHERE b.cod_empresa = p_cod_empresa
           AND (
                 TRIM(p_q) IS NULL
                 OR TO_CHAR(b.id_factura) LIKE l_q
                 OR TO_CHAR(b.nro_comprobante) LIKE l_q
                 OR UPPER(b.ser_timbrado) LIKE l_q
                 OR UPPER(pe.nombre) LIKE l_q
                 OR UPPER(pe.nombre_fantasia) LIKE l_q
               )
         ORDER BY b.fec_comprobante DESC, b.id_factura DESC
         FETCH FIRST 30 ROWS ONLY
    ) LOOP
      APEX_JSON.OPEN_OBJECT;
      APEX_JSON.WRITE('id_factura', r.id_factura);
      APEX_JSON.WRITE('nro_comprobante', r.nro_comprobante);
      APEX_JSON.WRITE('ser_timbrado', r.ser_timbrado);
      APEX_JSON.WRITE('tip_comprobante', r.tip_comprobante);
      APEX_JSON.WRITE('fec_comprobante', TO_CHAR(r.fec_comprobante, 'YYYY-MM-DD'));
      APEX_JSON.WRITE('nombre_cliente', r.nombre_cliente);
      APEX_JSON.CLOSE_OBJECT;
    END LOOP;
    APEX_JSON.CLOSE_ARRAY;
    APEX_JSON.CLOSE_OBJECT;
  EXCEPTION
    WHEN OTHERS THEN
      p_error(500, 'Internal Server Error', 'Error: ' || SQLERRM);
  END BUSCAR_VENTAS;

  --------------------------------------------------------------------------
  -- INSERTAR (id por IDENTITY)
  --------------------------------------------------------------------------
  PROCEDURE INSERTAR(
      p_token IN VARCHAR2, p_fecha IN VARCHAR2, p_id_factura IN NUMBER,
      p_id_forma IN NUMBER, p_id_banco IN NUMBER, p_nro_transaccion IN VARCHAR2,
      p_observacion IN VARCHAR2, p_total IN NUMBER, p_cod_moneda IN NUMBER,
      p_efectivo_recibido IN NUMBER, p_efectivo_vuelto IN NUMBER) IS
    l_usuario  VARCHAR2(255);
    l_id_cobro ventas_cobros.id_cobro%TYPE;
    l_fecha    DATE;
  BEGIN
    l_usuario := f_usuario(p_token);
    IF l_usuario IS NULL THEN
      p_error(401, 'Unauthorized', 'Token invalido o expirado');
      RETURN;
    END IF;

    IF p_fecha IS NULL THEN
      p_error(400, 'Bad Request', 'La fecha es obligatoria'); RETURN;
    END IF;
    IF p_id_factura IS NULL THEN
      p_error(400, 'Bad Request', 'La factura es obligatoria'); RETURN;
    END IF;
    IF p_id_forma IS NULL THEN
      p_error(400, 'Bad Request', 'La forma de cobro es obligatoria'); RETURN;
    END IF;
    IF p_total IS NULL THEN
      p_error(400, 'Bad Request', 'El total es obligatorio'); RETURN;
    END IF;
    IF p_cod_moneda IS NULL THEN
      p_error(400, 'Bad Request', 'La moneda es obligatoria'); RETURN;
    END IF;
    l_fecha := TO_DATE(p_fecha, 'YYYY-MM-DD');

    INSERT INTO ventas_cobros (
        fecha, id_factura, id_forma, id_banco, nro_transaccion, observacion,
        total, cod_moneda, efectivo_recibido, efectivo_vuelto)
    VALUES (
        l_fecha, p_id_factura, p_id_forma, p_id_banco, p_nro_transaccion, p_observacion,
        p_total, p_cod_moneda, p_efectivo_recibido, p_efectivo_vuelto)
    RETURNING id_cobro INTO l_id_cobro;
    COMMIT;

    OWA_UTIL.STATUS_LINE(201, 'Created', FALSE);
    APEX_JSON.OPEN_OBJECT;
    APEX_JSON.WRITE('success', TRUE);
    APEX_JSON.WRITE('message', 'Cobro creado');
    APEX_JSON.WRITE('id_cobro', l_id_cobro);
    APEX_JSON.CLOSE_OBJECT;
  EXCEPTION
    WHEN OTHERS THEN
      ROLLBACK;
      IF SQLCODE = -2291 THEN
        p_error(400, 'Bad Request', 'Factura, forma, banco o moneda inexistente');
      ELSE
        p_error(500, 'Internal Server Error', 'Error: ' || SQLERRM);
      END IF;
  END INSERTAR;

  --------------------------------------------------------------------------
  -- ACTUALIZAR
  --------------------------------------------------------------------------
  PROCEDURE ACTUALIZAR(
      p_token IN VARCHAR2, p_id_cobro IN NUMBER, p_fecha IN VARCHAR2, p_id_factura IN NUMBER,
      p_id_forma IN NUMBER, p_id_banco IN NUMBER, p_nro_transaccion IN VARCHAR2,
      p_observacion IN VARCHAR2, p_total IN NUMBER, p_cod_moneda IN NUMBER,
      p_efectivo_recibido IN NUMBER, p_efectivo_vuelto IN NUMBER) IS
    l_usuario VARCHAR2(255);
    l_fecha   DATE;
  BEGIN
    l_usuario := f_usuario(p_token);
    IF l_usuario IS NULL THEN
      p_error(401, 'Unauthorized', 'Token invalido o expirado');
      RETURN;
    END IF;

    IF p_fecha IS NULL THEN
      p_error(400, 'Bad Request', 'La fecha es obligatoria'); RETURN;
    END IF;
    IF p_id_factura IS NULL THEN
      p_error(400, 'Bad Request', 'La factura es obligatoria'); RETURN;
    END IF;
    IF p_id_forma IS NULL THEN
      p_error(400, 'Bad Request', 'La forma de cobro es obligatoria'); RETURN;
    END IF;
    IF p_total IS NULL THEN
      p_error(400, 'Bad Request', 'El total es obligatorio'); RETURN;
    END IF;
    IF p_cod_moneda IS NULL THEN
      p_error(400, 'Bad Request', 'La moneda es obligatoria'); RETURN;
    END IF;
    l_fecha := TO_DATE(p_fecha, 'YYYY-MM-DD');

    UPDATE ventas_cobros
       SET fecha             = l_fecha,
           id_factura        = p_id_factura,
           id_forma          = p_id_forma,
           id_banco          = p_id_banco,
           nro_transaccion   = p_nro_transaccion,
           observacion       = p_observacion,
           total             = p_total,
           cod_moneda        = p_cod_moneda,
           efectivo_recibido = p_efectivo_recibido,
           efectivo_vuelto   = p_efectivo_vuelto
     WHERE id_cobro = p_id_cobro;

    IF SQL%ROWCOUNT = 0 THEN
      ROLLBACK;
      p_error(404, 'Not Found', 'Cobro no encontrado');
      RETURN;
    END IF;
    COMMIT;

    APEX_JSON.OPEN_OBJECT;
    APEX_JSON.WRITE('success', TRUE);
    APEX_JSON.WRITE('message', 'Cobro actualizado');
    APEX_JSON.CLOSE_OBJECT;
  EXCEPTION
    WHEN OTHERS THEN
      ROLLBACK;
      IF SQLCODE = -2291 THEN
        p_error(400, 'Bad Request', 'Factura, forma, banco o moneda inexistente');
      ELSE
        p_error(500, 'Internal Server Error', 'Error: ' || SQLERRM);
      END IF;
  END ACTUALIZAR;

  --------------------------------------------------------------------------
  -- ELIMINAR
  --------------------------------------------------------------------------
  PROCEDURE ELIMINAR(p_token IN VARCHAR2, p_id_cobro IN NUMBER) IS
    l_usuario VARCHAR2(255);
  BEGIN
    l_usuario := f_usuario(p_token);
    IF l_usuario IS NULL THEN
      p_error(401, 'Unauthorized', 'Token invalido o expirado');
      RETURN;
    END IF;

    DELETE FROM ventas_cobros WHERE id_cobro = p_id_cobro;

    IF SQL%ROWCOUNT = 0 THEN
      ROLLBACK;
      p_error(404, 'Not Found', 'Cobro no encontrado');
      RETURN;
    END IF;
    COMMIT;

    APEX_JSON.OPEN_OBJECT;
    APEX_JSON.WRITE('success', TRUE);
    APEX_JSON.WRITE('message', 'Cobro eliminado');
    APEX_JSON.CLOSE_OBJECT;
  EXCEPTION
    WHEN OTHERS THEN
      ROLLBACK;
      p_error(500, 'Internal Server Error', 'Error: ' || SQLERRM);
  END ELIMINAR;

END PKG_VENTAS_COBROS_LUBRIMEC;
/

--------------------------------------------------------------------------------
-- === 2) ENDPOINTS ORDS =====================================================
--
--   GET    /lubrimec/ventas-cobros?cod_empresa=:n      -> listar
--   GET    /lubrimec/ventas/buscar?cod_empresa=:n&q=:q -> selector de facturas
--   GET    /lubrimec/ventas-cobros/:id                 -> obtener
--   POST   /lubrimec/ventas-cobros                     -> insertar
--   PUT    /lubrimec/ventas-cobros/:id                 -> actualizar
--   DELETE /lubrimec/ventas-cobros/:id                 -> eliminar
--------------------------------------------------------------------------------

BEGIN
  BEGIN ORDS.DELETE_HANDLER('lubrimec', 'ventas-cobros', 'GET');        EXCEPTION WHEN OTHERS THEN NULL; END;
  BEGIN ORDS.DELETE_HANDLER('lubrimec', 'ventas-cobros', 'POST');       EXCEPTION WHEN OTHERS THEN NULL; END;
  BEGIN ORDS.DELETE_HANDLER('lubrimec', 'ventas/buscar', 'GET');        EXCEPTION WHEN OTHERS THEN NULL; END;
  BEGIN ORDS.DELETE_HANDLER('lubrimec', 'ventas-cobros/:id', 'GET');    EXCEPTION WHEN OTHERS THEN NULL; END;
  BEGIN ORDS.DELETE_HANDLER('lubrimec', 'ventas-cobros/:id', 'PUT');    EXCEPTION WHEN OTHERS THEN NULL; END;
  BEGIN ORDS.DELETE_HANDLER('lubrimec', 'ventas-cobros/:id', 'DELETE'); EXCEPTION WHEN OTHERS THEN NULL; END;

  ----------------------------------------------------------------------------
  -- /ventas-cobros  (coleccion: GET listar, POST insertar)
  ----------------------------------------------------------------------------
  BEGIN
    ORDS.DEFINE_TEMPLATE(p_module_name => 'lubrimec', p_pattern => 'ventas-cobros',
        p_priority => 0, p_etag_type => 'HASH', p_comments => NULL);
  EXCEPTION WHEN OTHERS THEN NULL; END;

  ORDS.DEFINE_HANDLER(
      p_module_name => 'lubrimec', p_pattern => 'ventas-cobros', p_method => 'GET',
      p_source_type => 'plsql/block',
      p_source      => q'~
DECLARE
    l_token VARCHAR2(256); l_pos PLS_INTEGER;
    l_qs VARCHAR2(4000); l_cod_empresa VARCHAR2(20); l_id_factura VARCHAR2(20);
    FUNCTION get_qs(p_qs IN VARCHAR2, p_key IN VARCHAR2) RETURN VARCHAR2 IS
        l_p PLS_INTEGER; l_e PLS_INTEGER; l_v VARCHAR2(4000);
    BEGIN
        l_p := INSTR('&' || p_qs, '&' || p_key || '=');
        IF l_p = 0 THEN RETURN NULL; END IF;
        l_p := l_p + LENGTH(p_key) + 1;
        l_e := INSTR(p_qs || '&', '&', l_p);
        l_v := SUBSTR(p_qs, l_p, l_e - l_p);
        l_v := REPLACE(l_v, '+', ' ');
        RETURN UTL_URL.UNESCAPE(l_v);
    END;
BEGIN
    OWA_UTIL.MIME_HEADER('application/json', FALSE);
    HTP.P('Access-Control-Allow-Origin: *');
    HTP.P('Access-Control-Allow-Methods: GET, POST, PUT, DELETE, OPTIONS');
    HTP.P('Access-Control-Allow-Headers: Authorization, Content-Type');
    OWA_UTIL.HTTP_HEADER_CLOSE;
    l_token := :authorization;
    IF l_token IS NOT NULL THEN
        l_pos := INSTR(UPPER(l_token), 'BEARER ');
        IF l_pos > 0 THEN l_token := TRIM(SUBSTR(l_token, l_pos + 7)); END IF;
    END IF;
    l_qs := OWA_UTIL.GET_CGI_ENV('QUERY_STRING');
    l_cod_empresa := get_qs(l_qs, 'cod_empresa');
    l_id_factura  := get_qs(l_qs, 'id_factura');
    PKG_VENTAS_COBROS_LUBRIMEC.LISTAR(
        p_token => l_token, p_cod_empresa => TO_NUMBER(l_cod_empresa),
        p_id_factura => TO_NUMBER(l_id_factura));
END;
~');
  ORDS.DEFINE_PARAMETER(p_module_name => 'lubrimec', p_pattern => 'ventas-cobros', p_method => 'GET',
      p_name => 'Authorization', p_bind_variable_name => 'authorization',
      p_source_type => 'HEADER', p_param_type => 'STRING', p_access_method => 'IN');

  ORDS.DEFINE_HANDLER(
      p_module_name => 'lubrimec', p_pattern => 'ventas-cobros', p_method => 'POST',
      p_source_type => 'plsql/block',
      p_source      => q'~
DECLARE l_token VARCHAR2(256); l_pos PLS_INTEGER;
BEGIN
    OWA_UTIL.MIME_HEADER('application/json', FALSE);
    HTP.P('Access-Control-Allow-Origin: *');
    HTP.P('Access-Control-Allow-Methods: GET, POST, PUT, DELETE, OPTIONS');
    HTP.P('Access-Control-Allow-Headers: Authorization, Content-Type');
    OWA_UTIL.HTTP_HEADER_CLOSE;
    l_token := :authorization;
    IF l_token IS NOT NULL THEN
        l_pos := INSTR(UPPER(l_token), 'BEARER ');
        IF l_pos > 0 THEN l_token := TRIM(SUBSTR(l_token, l_pos + 7)); END IF;
    END IF;
    PKG_VENTAS_COBROS_LUBRIMEC.INSERTAR(
        p_token => l_token, p_fecha => :fecha, p_id_factura => TO_NUMBER(:id_factura),
        p_id_forma => TO_NUMBER(:id_forma), p_id_banco => TO_NUMBER(:id_banco),
        p_nro_transaccion => :nro_transaccion, p_observacion => :observacion,
        p_total => TO_NUMBER(:total), p_cod_moneda => TO_NUMBER(:cod_moneda),
        p_efectivo_recibido => TO_NUMBER(:efectivo_recibido),
        p_efectivo_vuelto => TO_NUMBER(:efectivo_vuelto));
END;
~');
  ORDS.DEFINE_PARAMETER(p_module_name => 'lubrimec', p_pattern => 'ventas-cobros', p_method => 'POST',
      p_name => 'Authorization', p_bind_variable_name => 'authorization',
      p_source_type => 'HEADER', p_param_type => 'STRING', p_access_method => 'IN');

  ----------------------------------------------------------------------------
  -- /ventas/buscar  -> selector de facturas del formulario
  ----------------------------------------------------------------------------
  BEGIN
    ORDS.DEFINE_TEMPLATE(p_module_name => 'lubrimec', p_pattern => 'ventas/buscar',
        p_priority => 0, p_etag_type => 'HASH', p_comments => NULL);
  EXCEPTION WHEN OTHERS THEN NULL; END;

  ORDS.DEFINE_HANDLER(
      p_module_name => 'lubrimec', p_pattern => 'ventas/buscar', p_method => 'GET',
      p_source_type => 'plsql/block',
      p_source      => q'~
DECLARE
    l_token VARCHAR2(256); l_pos PLS_INTEGER;
    l_qs VARCHAR2(4000); l_cod_empresa VARCHAR2(20); l_q VARCHAR2(400);
    FUNCTION get_qs(p_qs IN VARCHAR2, p_key IN VARCHAR2) RETURN VARCHAR2 IS
        l_p PLS_INTEGER; l_e PLS_INTEGER; l_v VARCHAR2(4000);
    BEGIN
        l_p := INSTR('&' || p_qs, '&' || p_key || '=');
        IF l_p = 0 THEN RETURN NULL; END IF;
        l_p := l_p + LENGTH(p_key) + 1;
        l_e := INSTR(p_qs || '&', '&', l_p);
        l_v := SUBSTR(p_qs, l_p, l_e - l_p);
        l_v := REPLACE(l_v, '+', ' ');
        RETURN UTL_URL.UNESCAPE(l_v);
    END;
BEGIN
    OWA_UTIL.MIME_HEADER('application/json', FALSE);
    HTP.P('Access-Control-Allow-Origin: *');
    HTP.P('Access-Control-Allow-Methods: GET, OPTIONS');
    HTP.P('Access-Control-Allow-Headers: Authorization, Content-Type');
    OWA_UTIL.HTTP_HEADER_CLOSE;
    l_token := :authorization;
    IF l_token IS NOT NULL THEN
        l_pos := INSTR(UPPER(l_token), 'BEARER ');
        IF l_pos > 0 THEN l_token := TRIM(SUBSTR(l_token, l_pos + 7)); END IF;
    END IF;
    l_qs := OWA_UTIL.GET_CGI_ENV('QUERY_STRING');
    l_cod_empresa := get_qs(l_qs, 'cod_empresa');
    l_q           := get_qs(l_qs, 'q');
    PKG_VENTAS_COBROS_LUBRIMEC.BUSCAR_VENTAS(
        p_token => l_token, p_cod_empresa => TO_NUMBER(l_cod_empresa), p_q => l_q);
END;
~');
  ORDS.DEFINE_PARAMETER(p_module_name => 'lubrimec', p_pattern => 'ventas/buscar', p_method => 'GET',
      p_name => 'Authorization', p_bind_variable_name => 'authorization',
      p_source_type => 'HEADER', p_param_type => 'STRING', p_access_method => 'IN');

  ----------------------------------------------------------------------------
  -- /ventas-cobros/:id  (item: GET obtener, PUT, DELETE)
  ----------------------------------------------------------------------------
  BEGIN
    ORDS.DEFINE_TEMPLATE(p_module_name => 'lubrimec', p_pattern => 'ventas-cobros/:id',
        p_priority => 0, p_etag_type => 'HASH', p_comments => NULL);
  EXCEPTION WHEN OTHERS THEN NULL; END;

  ORDS.DEFINE_HANDLER(
      p_module_name => 'lubrimec', p_pattern => 'ventas-cobros/:id', p_method => 'GET',
      p_source_type => 'plsql/block',
      p_source      => q'~
DECLARE l_token VARCHAR2(256); l_pos PLS_INTEGER;
BEGIN
    OWA_UTIL.MIME_HEADER('application/json', FALSE);
    HTP.P('Access-Control-Allow-Origin: *');
    HTP.P('Access-Control-Allow-Methods: GET, POST, PUT, DELETE, OPTIONS');
    HTP.P('Access-Control-Allow-Headers: Authorization, Content-Type');
    OWA_UTIL.HTTP_HEADER_CLOSE;
    l_token := :authorization;
    IF l_token IS NOT NULL THEN
        l_pos := INSTR(UPPER(l_token), 'BEARER ');
        IF l_pos > 0 THEN l_token := TRIM(SUBSTR(l_token, l_pos + 7)); END IF;
    END IF;
    PKG_VENTAS_COBROS_LUBRIMEC.OBTENER(p_token => l_token, p_id_cobro => TO_NUMBER(:id));
END;
~');
  ORDS.DEFINE_PARAMETER(p_module_name => 'lubrimec', p_pattern => 'ventas-cobros/:id', p_method => 'GET',
      p_name => 'Authorization', p_bind_variable_name => 'authorization',
      p_source_type => 'HEADER', p_param_type => 'STRING', p_access_method => 'IN');

  ORDS.DEFINE_HANDLER(
      p_module_name => 'lubrimec', p_pattern => 'ventas-cobros/:id', p_method => 'PUT',
      p_source_type => 'plsql/block',
      p_source      => q'~
DECLARE l_token VARCHAR2(256); l_pos PLS_INTEGER;
BEGIN
    OWA_UTIL.MIME_HEADER('application/json', FALSE);
    HTP.P('Access-Control-Allow-Origin: *');
    HTP.P('Access-Control-Allow-Methods: GET, POST, PUT, DELETE, OPTIONS');
    HTP.P('Access-Control-Allow-Headers: Authorization, Content-Type');
    OWA_UTIL.HTTP_HEADER_CLOSE;
    l_token := :authorization;
    IF l_token IS NOT NULL THEN
        l_pos := INSTR(UPPER(l_token), 'BEARER ');
        IF l_pos > 0 THEN l_token := TRIM(SUBSTR(l_token, l_pos + 7)); END IF;
    END IF;
    PKG_VENTAS_COBROS_LUBRIMEC.ACTUALIZAR(
        p_token => l_token, p_id_cobro => TO_NUMBER(:id), p_fecha => :fecha,
        p_id_factura => TO_NUMBER(:id_factura), p_id_forma => TO_NUMBER(:id_forma),
        p_id_banco => TO_NUMBER(:id_banco), p_nro_transaccion => :nro_transaccion,
        p_observacion => :observacion, p_total => TO_NUMBER(:total),
        p_cod_moneda => TO_NUMBER(:cod_moneda),
        p_efectivo_recibido => TO_NUMBER(:efectivo_recibido),
        p_efectivo_vuelto => TO_NUMBER(:efectivo_vuelto));
END;
~');
  ORDS.DEFINE_PARAMETER(p_module_name => 'lubrimec', p_pattern => 'ventas-cobros/:id', p_method => 'PUT',
      p_name => 'Authorization', p_bind_variable_name => 'authorization',
      p_source_type => 'HEADER', p_param_type => 'STRING', p_access_method => 'IN');

  ORDS.DEFINE_HANDLER(
      p_module_name => 'lubrimec', p_pattern => 'ventas-cobros/:id', p_method => 'DELETE',
      p_source_type => 'plsql/block',
      p_source      => q'~
DECLARE l_token VARCHAR2(256); l_pos PLS_INTEGER;
BEGIN
    OWA_UTIL.MIME_HEADER('application/json', FALSE);
    HTP.P('Access-Control-Allow-Origin: *');
    HTP.P('Access-Control-Allow-Methods: GET, POST, PUT, DELETE, OPTIONS');
    HTP.P('Access-Control-Allow-Headers: Authorization, Content-Type');
    OWA_UTIL.HTTP_HEADER_CLOSE;
    l_token := :authorization;
    IF l_token IS NOT NULL THEN
        l_pos := INSTR(UPPER(l_token), 'BEARER ');
        IF l_pos > 0 THEN l_token := TRIM(SUBSTR(l_token, l_pos + 7)); END IF;
    END IF;
    PKG_VENTAS_COBROS_LUBRIMEC.ELIMINAR(p_token => l_token, p_id_cobro => TO_NUMBER(:id));
END;
~');
  ORDS.DEFINE_PARAMETER(p_module_name => 'lubrimec', p_pattern => 'ventas-cobros/:id', p_method => 'DELETE',
      p_name => 'Authorization', p_bind_variable_name => 'authorization',
      p_source_type => 'HEADER', p_param_type => 'STRING', p_access_method => 'IN');

  COMMIT;
EXCEPTION
  WHEN OTHERS THEN
    ROLLBACK;
    RAISE;
END;
/
