--------------------------------------------------------------------------------
-- Objetos de soporte para la pagina 117 (Mensajes a WhatsApp).
-- Ejecutar como JOSEGALVEZ ANTES de PKG_WHATSAPP_LUBRIMEC.sql.
--------------------------------------------------------------------------------

-- Borrado idempotente para poder re-ejecutar el script.
BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE WHATSAPP_ENVIOS PURGE';
EXCEPTION WHEN OTHERS THEN
    IF SQLCODE != -942 THEN RAISE; END IF;  -- -942: la tabla no existe
END;
/

-- Cola de envios: desacopla el request HTTP del proceso en background.
-- El endpoint ENVIAR inserta una fila; el job la toma y procesa.
CREATE TABLE WHATSAPP_ENVIOS (
    id          NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    mensaje     VARCHAR2(4000),
    imagen_url  VARCHAR2(1000),        -- URL publica (NULL = solo texto)
    usuario     VARCHAR2(256),
    estado      VARCHAR2(20) DEFAULT 'PENDIENTE',  -- PENDIENTE | PROCESANDO | TERMINADO | ERROR
    resultado   VARCHAR2(1000),
    creado      TIMESTAMP DEFAULT SYSTIMESTAMP,
    terminado   TIMESTAMP
);

-- (La imagen no se guarda en Oracle: se sube a wasenderapi /api/upload desde
--  PKG_WHATSAPP_LUBRIMEC y wasender la sirve desde su propio CDN.)

-- fecha_registro en LOG_WHATSAPP (para el polling incremental del front).
-- Si la tabla ya tiene la columna, ignorar el error.
BEGIN
    EXECUTE IMMEDIATE
        'ALTER TABLE LOG_WHATSAPP ADD (fecha_registro TIMESTAMP DEFAULT SYSTIMESTAMP)';
EXCEPTION WHEN OTHERS THEN
    IF SQLCODE != -1430 THEN RAISE; END IF;  -- -1430: columna ya existe
END;
/

--------------------------------------------------------------------------------
-- Wrapper que corre en el job: lee el envio de la cola y llama al procedimiento.
--------------------------------------------------------------------------------
CREATE OR REPLACE PROCEDURE ENVIAR_MENSAJES_WHATSAPP_JOB (p_envio_id IN NUMBER) IS
    v_mensaje   VARCHAR2(4000);
    v_img_url   VARCHAR2(1000);
    v_error     VARCHAR2(4000);
    v_sqlerrm   VARCHAR2(1000);
BEGIN
    UPDATE WHATSAPP_ENVIOS SET estado = 'PROCESANDO' WHERE id = p_envio_id;
    COMMIT;

    SELECT mensaje, imagen_url
    INTO   v_mensaje, v_img_url
    FROM   WHATSAPP_ENVIOS WHERE id = p_envio_id;

    ENVIAR_MENSAJES_WHATSAPP(
        p_mensaje    => v_mensaje,
        p_imagen_url => v_img_url,
        p_error      => v_error);

    UPDATE WHATSAPP_ENVIOS
    SET    estado = 'TERMINADO', resultado = SUBSTR(v_error, 1, 1000), terminado = SYSTIMESTAMP
    WHERE  id = p_envio_id;
    COMMIT;
EXCEPTION WHEN OTHERS THEN
    v_sqlerrm := SQLERRM;
    UPDATE WHATSAPP_ENVIOS
    SET    estado = 'ERROR', resultado = v_sqlerrm, terminado = SYSTIMESTAMP
    WHERE  id = p_envio_id;
    COMMIT;
END ENVIAR_MENSAJES_WHATSAPP_JOB;
/
