--------------------------------------------------------------------------------
-- WHATSAPP (pagina APEX 117) — DDL + procedimiento de envio + paquete + ORDS.
-- Ejecutar completo como el esquema JOSEGALVEZ. Requiere PKG_AUTH_LUBRIMEC y las
-- tablas numeros_whatsapp / LOG_WHATSAPP.
--
-- Secciones (en orden de dependencia):
--   0) DDL de soporte           (tabla cola WHATSAPP_ENVIOS + columna fecha_registro)
--   1) PROC ENVIAR_MENSAJES_WHATSAPP  (envio real con reintentos/pausas/variantes)
--   2) PROC ENVIAR_MENSAJES_WHATSAPP_JOB (wrapper que corre en el job; usa el 1)
--   3) PAQUETE PKG_WHATSAPP_LUBRIMEC   (endpoints de la pagina)
--   4) ENDPOINTS ORDS
--------------------------------------------------------------------------------

--------------------------------------------------------------------------------
-- === 0) DDL DE SOPORTE ======================================================
--------------------------------------------------------------------------------

-- Borrado idempotente para poder re-ejecutar el script.
BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE WHATSAPP_ENVIOS PURGE';
EXCEPTION WHEN OTHERS THEN
    IF SQLCODE != -942 THEN RAISE; END IF;  -- -942: la tabla no existe
END;
/

-- Cola de envios: desacopla el request HTTP del proceso en background.
-- El endpoint ENVIAR inserta una fila; el job la toma y procesa.
CREATE TABLE WHATSAPP_ENVIOS (
    id             NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    mensaje        VARCHAR2(4000),
    imagen_url     VARCHAR2(1000),     -- URL publica (NULL = solo texto)
    numeros_manual CLOB,               -- JSON array de numeros (pestana Manual). NULL = envio a la base.
    usuario        VARCHAR2(256),
    estado         VARCHAR2(20) DEFAULT 'PENDIENTE',  -- PENDIENTE | PROCESANDO | TERMINADO | ERROR
    resultado      VARCHAR2(1000),
    creado         TIMESTAMP DEFAULT SYSTIMESTAMP,
    terminado      TIMESTAMP
);

-- (La imagen no se guarda en Oracle: se sube a wasenderapi /api/upload desde
--  PKG_WHATSAPP_LUBRIMEC y wasender la sirve desde su propio CDN.)

-- fecha_registro en LOG_WHATSAPP (para el polling incremental del front).
-- Si la tabla ya tiene la columna, ignorar el error.
BEGIN
    EXECUTE IMMEDIATE
        'ALTER TABLE LOG_WHATSAPP ADD (fecha_registro TIMESTAMP DEFAULT SYSTIMESTAMP)';
EXCEPTION WHEN OTHERS THEN
    IF SQLCODE != -1430 THEN RAISE; END IF;  -- -1430: columna ya existe
END;
/

--------------------------------------------------------------------------------
-- === 1) PROC ENVIAR_MENSAJES_WHATSAPP =======================================
-- Version extendida con soporte de imagen.
--
--   * Nuevo parametro p_imagen_url.
--   * Si hay imagen, el JSON incluye "imageUrl"; el texto va como caption ("text").
--   * El resto (reintentos, logs, mensajeado) se mantiene igual.
--   * Anti-bloqueo: lote de 100 numeros, pausa de 20s entre numeros y cada
--     20 numeros una pausa larga de 90s (simula descansos entre tandas).
--   * Variantes de texto: si el mensaje trae lineas separadoras "---", cada una
--     de las partes es una VARIANTE del mismo mensaje. Para cada numero se elige
--     una variante AL AZAR, de modo que no todos reciban el texto identico
--     (texto exacto masivo = principal senal de spam). Sin "---" = una variante.
--
-- wasenderapi (POST /api/send-message) envia imagen con el MISMO endpoint del texto:
--   { "to": "...", "text": "<caption>", "imageUrl": "<URL publica JPEG/PNG, max 5MB>" }
-- Solo acepta URL PUBLICA (no base64). El front sube la imagen al server Node
-- (src/routes/api/uploads.ts) y manda aca la URL resultante.
--------------------------------------------------------------------------------

CREATE OR REPLACE PROCEDURE ENVIAR_MENSAJES_WHATSAPP (
    p_mensaje        IN  VARCHAR2,
    p_imagen_url     IN  VARCHAR2 DEFAULT NULL,
    p_numeros_manual IN  CLOB     DEFAULT NULL,  -- JSON array: si viene, envia SOLO a estos
    p_error          OUT VARCHAR2
) AS

    v_api_url           VARCHAR2(500)  := 'https://wasenderapi.com/api/send-message';
    v_api_key           VARCHAR2(500)  := 'e83c588e35133bccc177db1df36ab10701640d02437dfb17438cc5aaa288350c';
    v_max_reintentos    NUMBER         := 3;
    v_pausa_segs        NUMBER         := 20;  -- pausa entre numeros
    v_tanda_numeros     NUMBER         := 20;  -- cada tantos numeros, pausa larga
    v_pausa_tanda_segs  NUMBER         := 90;  -- duracion de la pausa larga
    v_max_registros     NUMBER         := 100;
    v_numero_aviso      VARCHAR2(20)   := '0972111745';  -- avisar aqui al terminar

    v_request_body      CLOB;
    v_contador_enviados NUMBER         := 0;
    v_contador_errores  NUMBER         := 0;
    v_contador_invalidos NUMBER        := 0;
    v_contador_total    NUMBER         := 0;
    v_numero_original   VARCHAR2(100);
    v_numero_limpio     VARCHAR2(100);
    v_mensaje_esc       VARCHAR2(4000);
    v_img_json          VARCHAR2(200);   -- fragmento JSON del campo imagen (o vacio)

    -- Variantes del mensaje (partido por lineas "---"). Ver nota de cabecera.
    TYPE t_variantes IS TABLE OF VARCHAR2(4000);
    v_variantes         t_variantes := t_variantes();
    v_idx_variante      PLS_INTEGER;
    v_enviado           BOOLEAN;
    v_inicio_tiempo     TIMESTAMP;
    v_tiempo_total      NUMBER;

    TYPE t_numeros_table IS TABLE OF numeros_whatsapp%ROWTYPE;
    v_numeros_tabla     t_numeros_table;

    FUNCTION ESCAPAR_JSON(p_texto IN VARCHAR2) RETURN VARCHAR2 IS
        l_texto VARCHAR2(4000);
    BEGIN
        l_texto := p_texto;
        l_texto := REPLACE(l_texto, '\',     '\\');
        l_texto := REPLACE(l_texto, '"',     '\"');
        l_texto := REPLACE(l_texto, CHR(10), '\n');
        l_texto := REPLACE(l_texto, CHR(13), '\r');
        l_texto := REPLACE(l_texto, CHR(9),  '\t');
        RETURN l_texto;
    END ESCAPAR_JSON;

    -- Parte el mensaje en variantes usando lineas cuyo contenido (sin espacios) es
    -- exactamente "---". Descarta variantes vacias. Si no hay separador, devuelve
    -- una unica variante con el texto completo. Nunca deja la coleccion vacia.
    PROCEDURE PARSEAR_VARIANTES(p_texto IN VARCHAR2) IS
        l_resto   VARCHAR2(32767);
        l_linea   VARCHAR2(4000);
        l_acum    VARCHAR2(4000);
        l_nl      PLS_INTEGER;

        PROCEDURE CERRAR_VARIANTE IS
        BEGIN
            IF TRIM(l_acum) IS NOT NULL THEN
                v_variantes.EXTEND;
                v_variantes(v_variantes.COUNT) := l_acum;
            END IF;
            l_acum := NULL;
        END CERRAR_VARIANTE;
    BEGIN
        v_variantes := t_variantes();
        -- CR fuera; CHR(10) final asegura que se procese la ultima linea.
        l_resto := REPLACE(NVL(p_texto, ''), CHR(13), '') || CHR(10);
        WHILE l_resto IS NOT NULL AND LENGTH(l_resto) > 0 LOOP
            l_nl    := INSTR(l_resto, CHR(10));
            l_linea := SUBSTR(l_resto, 1, l_nl - 1);
            l_resto := SUBSTR(l_resto, l_nl + 1);
            IF TRIM(l_linea) = '---' THEN
                CERRAR_VARIANTE;
            ELSIF l_acum IS NULL THEN
                l_acum := l_linea;
            ELSE
                l_acum := l_acum || CHR(10) || l_linea;
            END IF;
        END LOOP;
        CERRAR_VARIANTE;

        IF v_variantes.COUNT = 0 THEN
            v_variantes.EXTEND;
            v_variantes(1) := '';
        END IF;
    END PARSEAR_VARIANTES;

    PROCEDURE REGISTRAR_LOG(
        p_numero_original VARCHAR2, p_numero_limpio VARCHAR2, p_estado VARCHAR2,
        p_http_status NUMBER, p_respuesta VARCHAR2, p_error VARCHAR2
    ) IS
    BEGIN
        BEGIN
            INSERT INTO LOG_WHATSAPP (
                NUMERO_ORIGINAL, NUMERO_LIMPIO, MENSAJE, ESTADO,
                HTTP_STATUS, RESPUESTA_API, DETALLE_ERROR
            ) VALUES (
                p_numero_original, p_numero_limpio, SUBSTR(p_mensaje, 1, 500), p_estado,
                p_http_status, SUBSTR(p_respuesta, 1, 500), SUBSTR(p_error, 1, 1000)
            );
            COMMIT;
        EXCEPTION WHEN OTHERS THEN
            apex_debug.message('Error al registrar log: ' || SQLERRM);
        END;
    END REGISTRAR_LOG;

    PROCEDURE ENVIAR_CON_REINTENTOS(
        p_id NUMBER, p_numero_original VARCHAR2, p_numero_limpio VARCHAR2,
        p_enviado OUT BOOLEAN
    ) IS
        v_intento_local  NUMBER := 0;
        v_enviado_local  BOOLEAN := FALSE;
        v_response_local CLOB;
        v_status_local   NUMBER;
        v_api_ok         BOOLEAN;  -- success del JSON que devuelve wasenderapi
        v_json_api       APEX_JSON.T_VALUES;
    BEGIN
        p_enviado := FALSE;
        WHILE v_intento_local < v_max_reintentos AND NOT v_enviado_local LOOP
            v_intento_local := v_intento_local + 1;
            BEGIN
                -- JSON: si hay imagen agrega el campo imageUrl; el texto va como caption/text.
                v_request_body :=
                    '{"to":"' || p_numero_limpio || '",' ||
                    v_img_json ||
                    '"text":"' || v_mensaje_esc || '"}';

                v_response_local := APEX_WEB_SERVICE.MAKE_REST_REQUEST(
                    p_url         => v_api_url,
                    p_http_method => 'POST',
                    p_body        => v_request_body);

                v_status_local := APEX_WEB_SERVICE.G_STATUS_CODE;

                IF v_status_local IN (200, 201, 202) THEN
                    -- wasenderapi puede responder 200 con {"success":false,...}. Parseamos
                    -- el JSON para no marcar como ENVIADO un mensaje que la API rechazo.
                    BEGIN
                        APEX_JSON.PARSE(v_json_api, v_response_local);
                        v_api_ok := UPPER(NVL(APEX_JSON.GET_VARCHAR2(
                                        p_path => 'success', p_values => v_json_api), 'TRUE')) = 'TRUE';
                    EXCEPTION WHEN OTHERS THEN
                        v_api_ok := TRUE;  -- si no es JSON parseable, nos guiamos por el HTTP 2xx
                    END;

                    IF v_api_ok THEN
                        IF p_id IS NOT NULL THEN
                            UPDATE numeros_whatsapp SET mensajeado = 'S' WHERE id = p_id;
                        END IF;
                        REGISTRAR_LOG(p_numero_original, p_numero_limpio, 'ENVIADO', v_status_local, v_response_local, NULL);
                        v_contador_enviados := v_contador_enviados + 1;
                    ELSE
                        IF p_id IS NOT NULL THEN
                            UPDATE numeros_whatsapp SET mensajeado = 'E' WHERE id = p_id;
                        END IF;
                        REGISTRAR_LOG(p_numero_original, p_numero_limpio, 'ERROR', v_status_local, v_response_local,
                                      'API respondio success=false');
                        v_contador_errores := v_contador_errores + 1;
                    END IF;
                    v_enviado_local := TRUE; p_enviado := TRUE;

                ELSIF v_status_local IN (429, 500, 502, 503, 504) THEN
                    IF v_intento_local < v_max_reintentos THEN
                        IF v_status_local = 429 THEN DBMS_SESSION.SLEEP(5); ELSE DBMS_SESSION.SLEEP(2); END IF;
                    ELSE
                        IF p_id IS NOT NULL THEN
                            UPDATE numeros_whatsapp SET mensajeado = 'E' WHERE id = p_id;
                        END IF;
                        REGISTRAR_LOG(p_numero_original, p_numero_limpio, 'ERROR', v_status_local, v_response_local,
                                      'Error temporal despues de ' || v_max_reintentos || ' intentos');
                        v_contador_errores := v_contador_errores + 1;
                        v_enviado_local := TRUE; p_enviado := TRUE;
                    END IF;

                ELSE
                    IF p_id IS NOT NULL THEN
                        UPDATE numeros_whatsapp SET mensajeado = 'E' WHERE id = p_id;
                    END IF;
                    REGISTRAR_LOG(p_numero_original, p_numero_limpio, 'ERROR', v_status_local, v_response_local,
                                  'Error HTTP ' || v_status_local);
                    v_contador_errores := v_contador_errores + 1;
                    v_enviado_local := TRUE; p_enviado := TRUE;
                END IF;

            EXCEPTION WHEN OTHERS THEN
                IF v_intento_local < v_max_reintentos THEN
                    DBMS_SESSION.SLEEP(2);
                ELSE
                    IF p_id IS NOT NULL THEN
                        UPDATE numeros_whatsapp SET mensajeado = 'E' WHERE id = p_id;
                    END IF;
                    REGISTRAR_LOG(p_numero_original, p_numero_limpio, 'EXCEPCION', NULL, NULL, SQLERRM);
                    v_contador_errores := v_contador_errores + 1;
                    v_enviado_local := TRUE; p_enviado := TRUE;
                END IF;
            END;
        END LOOP;
    END ENVIAR_CON_REINTENTOS;

BEGIN
    v_inicio_tiempo := SYSTIMESTAMP;

    IF p_mensaje IS NULL AND p_imagen_url IS NULL THEN
        p_error := 'El mensaje no puede estar vacio';
        RETURN;
    END IF;

    -- Variantes del texto (una sola si no hay lineas "---").
    PARSEAR_VARIANTES(NVL(p_mensaje, ''));

    -- Fragmento JSON de imagen (vacio si no hay). Ver nota de cabecera.
    IF p_imagen_url IS NOT NULL THEN
        v_img_json := '"imageUrl":"' || ESCAPAR_JSON(p_imagen_url) || '",';
    ELSE
        v_img_json := '';
    END IF;

    -- Origen de los numeros: MANUAL (lista recibida) o BASE (tabla numeros_whatsapp).
    IF p_numeros_manual IS NOT NULL AND DBMS_LOB.GETLENGTH(p_numeros_manual) > 0 THEN
        BEGIN
            APEX_JSON.PARSE(p_numeros_manual);
            v_contador_total := APEX_JSON.GET_COUNT('.');
        EXCEPTION WHEN OTHERS THEN
            p_error := 'Numeros manuales invalidos: ' || SQLERRM;
            RETURN;
        END;
        IF v_contador_total = 0 THEN
            p_error := 'No hay numeros para procesar';
            RETURN;
        END IF;
    ELSE
        BEGIN
            SELECT * BULK COLLECT INTO v_numeros_tabla
            FROM numeros_whatsapp
            WHERE NVL(mensajeado, 'N') = 'N'
            FETCH FIRST v_max_registros ROWS ONLY;

            v_contador_total := v_numeros_tabla.COUNT;
            IF v_contador_total = 0 THEN
                p_error := 'No hay numeros para procesar';
                RETURN;
            END IF;
        EXCEPTION WHEN OTHERS THEN
            p_error := 'Error al cargar numeros: ' || SQLERRM;
            RETURN;
        END;
    END IF;

    BEGIN
        APEX_WEB_SERVICE.SET_REQUEST_HEADERS(
            p_name_01 => 'Authorization', p_value_01 => 'Bearer ' || v_api_key,
            p_name_02 => 'Content-Type',  p_value_02 => 'application/json',
            p_name_03 => 'User-Agent',    p_value_03 => 'APEX-WhatsApp/4.0');
    EXCEPTION WHEN OTHERS THEN
        apex_debug.message('ERROR en headers: ' || SQLERRM);
    END;

    FOR i IN 1..v_contador_total LOOP
        BEGIN
            -- MANUAL: numero de la lista (sin id, no toca la tabla).
            -- BASE:   numero de la coleccion cargada de numeros_whatsapp.
            IF p_numeros_manual IS NOT NULL AND DBMS_LOB.GETLENGTH(p_numeros_manual) > 0 THEN
                v_numero_original := TRIM(APEX_JSON.GET_VARCHAR2('[%d]', i));
            ELSE
                v_numero_original := v_numeros_tabla(i).numero;
            END IF;

            v_numero_limpio := LIMPIAR_NUMERO(v_numero_original);

            IF v_numero_limpio IS NULL THEN
                IF p_numeros_manual IS NULL THEN
                    UPDATE numeros_whatsapp SET mensajeado = 'E' WHERE id = v_numeros_tabla(i).id;
                END IF;
                REGISTRAR_LOG(v_numero_original, NULL, 'INVALIDO', NULL, NULL,
                              'Numero invalido o sin suficientes digitos');
                v_contador_invalidos := v_contador_invalidos + 1;
            ELSE
                -- Variante de texto al azar para este numero (ENVIAR_CON_REINTENTOS
                -- arma el body con v_mensaje_esc). Con una sola variante siempre es esa.
                v_idx_variante := TRUNC(DBMS_RANDOM.VALUE(1, v_variantes.COUNT + 1));
                v_mensaje_esc  := ESCAPAR_JSON(v_variantes(v_idx_variante));

                -- p_id NULL en manual: no se actualiza numeros_whatsapp.
                IF p_numeros_manual IS NOT NULL AND DBMS_LOB.GETLENGTH(p_numeros_manual) > 0 THEN
                    ENVIAR_CON_REINTENTOS(NULL, v_numero_original, v_numero_limpio, v_enviado);
                ELSE
                    ENVIAR_CON_REINTENTOS(v_numeros_tabla(i).id, v_numero_original, v_numero_limpio, v_enviado);
                END IF;
            END IF;

            -- Pausa entre numeros; al completar una tanda, descanso largo.
            -- Tras el ultimo numero no se duerme (no queda nada por enviar).
            IF i < v_contador_total THEN
                IF MOD(i, v_tanda_numeros) = 0 THEN
                    DBMS_SESSION.SLEEP(v_pausa_tanda_segs);
                ELSE
                    DBMS_SESSION.SLEEP(v_pausa_segs);
                END IF;
            END IF;
        EXCEPTION WHEN OTHERS THEN
            v_contador_errores := v_contador_errores + 1;
        END;
    END LOOP;

    v_tiempo_total := EXTRACT(SECOND FROM (SYSTIMESTAMP - v_inicio_tiempo));

    p_error := 'Total: ' || v_contador_total ||
               ' | Enviados: ' || v_contador_enviados ||
               ' | Errores: ' || v_contador_errores ||
               ' | Invalidos: ' || v_contador_invalidos ||
               ' | Tiempo: ' || ROUND(v_tiempo_total / 60, 2) || ' min';
    COMMIT;

    -- Aviso de finalizacion al numero fijo (usa el resumen como texto, sin imagen).
    BEGIN
        v_img_json    := '';
        v_mensaje_esc := ESCAPAR_JSON(
            'Proceso de envio de mensajes de WhatsApp finalizado. ' || p_error);
        v_numero_limpio := LIMPIAR_NUMERO(v_numero_aviso);
        IF v_numero_limpio IS NOT NULL THEN
            ENVIAR_CON_REINTENTOS(NULL, v_numero_aviso, v_numero_limpio, v_enviado);
            COMMIT;
        END IF;
    EXCEPTION WHEN OTHERS THEN
        apex_debug.message('Error al enviar aviso de finalizacion: ' || SQLERRM);
    END;

EXCEPTION WHEN OTHERS THEN
    ROLLBACK;
    p_error := 'Error general: ' || SQLERRM;
END ENVIAR_MENSAJES_WHATSAPP;
/

--------------------------------------------------------------------------------
-- === 2) PROC ENVIAR_MENSAJES_WHATSAPP_JOB ===================================
-- Wrapper que corre en el job: lee el envio de la cola y llama al procedimiento
-- de la seccion 1. Va DESPUES de ENVIAR_MENSAJES_WHATSAPP (lo referencia).
--------------------------------------------------------------------------------
CREATE OR REPLACE PROCEDURE ENVIAR_MENSAJES_WHATSAPP_JOB (p_envio_id IN NUMBER) IS
    v_mensaje   VARCHAR2(4000);
    v_img_url   VARCHAR2(1000);
    v_manual    CLOB;
    v_error     VARCHAR2(4000);
    v_sqlerrm   VARCHAR2(1000);
BEGIN
    UPDATE WHATSAPP_ENVIOS SET estado = 'PROCESANDO' WHERE id = p_envio_id;
    COMMIT;

    SELECT mensaje, imagen_url, numeros_manual
    INTO   v_mensaje, v_img_url, v_manual
    FROM   WHATSAPP_ENVIOS WHERE id = p_envio_id;

    ENVIAR_MENSAJES_WHATSAPP(
        p_mensaje         => v_mensaje,
        p_imagen_url      => v_img_url,
        p_numeros_manual  => v_manual,
        p_error           => v_error);

    UPDATE WHATSAPP_ENVIOS
    SET    estado = 'TERMINADO', resultado = SUBSTR(v_error, 1, 1000), terminado = SYSTIMESTAMP
    WHERE  id = p_envio_id;
    COMMIT;
EXCEPTION WHEN OTHERS THEN
    v_sqlerrm := SQLERRM;
    UPDATE WHATSAPP_ENVIOS
    SET    estado = 'ERROR', resultado = v_sqlerrm, terminado = SYSTIMESTAMP
    WHERE  id = p_envio_id;
    COMMIT;
END ENVIAR_MENSAJES_WHATSAPP_JOB;
/

--------------------------------------------------------------------------------
-- === 3) PAQUETE PKG_WHATSAPP_LUBRIMEC =======================================
-- Endpoints de la pagina 117 (Mensajes a WhatsApp).
--
--   LISTAR_NUMEROS(token, solo_pendientes)  -> numeros de numeros_whatsapp
--   ENVIAR(token, mensaje, imagen_url, numeros_manual) -> lanza job y responde envio_id
--   LOGS(token, desde)                      -> filas de LOG_WHATSAPP para el polling
--   SUBIR_IMAGEN(token, base64, mime, nombre) -> sube a wasender /upload, responde {url}
--   CARGAR_NUMEROS(token, numeros)          -> carga masiva de numeros
--   BORRAR_NUMEROS(token)                   -> borra todos los numeros
--
-- El envio real corre en background (DBMS_SCHEDULER) porque hay pausas entre numeros
-- (20s, y 90s cada 20): un request HTTP no puede quedarse esperando ~40 min. El job invoca
-- ENVIAR_MENSAJES_WHATSAPP_JOB (seccion 2), que a su vez llama a ENVIAR_MENSAJES_WHATSAPP.
--------------------------------------------------------------------------------

CREATE OR REPLACE PACKAGE PKG_WHATSAPP_LUBRIMEC AS
    PROCEDURE LISTAR_NUMEROS(
        p_token           IN VARCHAR2,
        p_solo_pendientes IN VARCHAR2 DEFAULT 'S');

    -- p_numeros_manual: JSON array de strings, ej. '["595981...","595982..."]'.
    -- Si viene, esos numeros se insertan en numeros_whatsapp (pendientes) antes de enviar.
    -- p_imagen_url: URL publica de la imagen (wasender no acepta base64).
    PROCEDURE ENVIAR(
        p_token          IN VARCHAR2,
        p_mensaje        IN VARCHAR2,
        p_imagen_url     IN VARCHAR2 DEFAULT NULL,
        p_numeros_manual IN VARCHAR2 DEFAULT NULL);

    PROCEDURE LOGS(
        p_token IN VARCHAR2,
        p_desde IN VARCHAR2 DEFAULT NULL);  -- ISO timestamp; NULL = todo el dia

    -- Sube una imagen (base64) a wasenderapi /api/upload y responde {url} con la URL
    -- publica (CDN de wasender) que se usara como imageUrl. p_base64: data URL o base64 puro.
    PROCEDURE SUBIR_IMAGEN(
        p_token  IN VARCHAR2,
        p_base64 IN CLOB,
        p_mime   IN VARCHAR2 DEFAULT NULL,
        p_nombre IN VARCHAR2 DEFAULT NULL);

    -- Carga masiva: p_numeros es un JSON array de strings. Inserta los validos que no
    -- existan ya (mensajeado='N'). Responde {insertados, omitidos}.
    PROCEDURE CARGAR_NUMEROS(
        p_token   IN VARCHAR2,
        p_numeros IN CLOB);

    -- Borra TODOS los numeros de numeros_whatsapp.
    PROCEDURE BORRAR_NUMEROS(p_token IN VARCHAR2);
END PKG_WHATSAPP_LUBRIMEC;
/

CREATE OR REPLACE PACKAGE BODY PKG_WHATSAPP_LUBRIMEC AS

    -- API key de wasenderapi (la misma del envio). Se usa para subir la imagen a
    -- POST /api/upload, que devuelve una URL publica (CDN de wasender, valida 24h).
    C_WASENDER_KEY CONSTANT VARCHAR2(200) :=
        '95f3747b28d911bd7ea91f261101bd4bcc258a51bbebd55f439e673bba7929bd';

    -- Respuesta de error estandar del proyecto.
    PROCEDURE p_error(p_status IN NUMBER, p_message IN VARCHAR2) IS
    BEGIN
        OWA_UTIL.STATUS_LINE(p_status, NULL, FALSE);
        APEX_JSON.OPEN_OBJECT;
        APEX_JSON.WRITE('success', FALSE);
        APEX_JSON.WRITE('message', p_message);
        APEX_JSON.CLOSE_OBJECT;
    END p_error;

    -- Valida el token y devuelve el usuario (NULL si invalido).
    FUNCTION f_usuario(p_token IN VARCHAR2) RETURN VARCHAR2 IS
    BEGIN
        RETURN PKG_AUTH_LUBRIMEC.VALIDAR_TOKEN(p_token);
    EXCEPTION WHEN OTHERS THEN
        RETURN NULL;
    END f_usuario;

    ----------------------------------------------------------------------------
    PROCEDURE LISTAR_NUMEROS(
        p_token           IN VARCHAR2,
        p_solo_pendientes IN VARCHAR2 DEFAULT 'S')
    IS
        l_usuario VARCHAR2(256);
    BEGIN
        l_usuario := f_usuario(p_token);
        IF l_usuario IS NULL THEN
            p_error(401, 'Token invalido o expirado');
            RETURN;
        END IF;

        APEX_JSON.OPEN_OBJECT;
        APEX_JSON.WRITE('success', TRUE);
        APEX_JSON.OPEN_ARRAY('data');
        FOR r IN (
            SELECT id, numero, NVL(mensajeado, 'N') AS mensajeado
            FROM   numeros_whatsapp
            WHERE  (p_solo_pendientes = 'N' OR NVL(mensajeado, 'N') = 'N')
            ORDER  BY id
        ) LOOP
            APEX_JSON.OPEN_OBJECT;
            APEX_JSON.WRITE('id', r.id);
            APEX_JSON.WRITE('numero', r.numero);
            APEX_JSON.WRITE('mensajeado', r.mensajeado);
            APEX_JSON.CLOSE_OBJECT;
        END LOOP;
        APEX_JSON.CLOSE_ARRAY;
        APEX_JSON.CLOSE_OBJECT;
    EXCEPTION WHEN OTHERS THEN
        p_error(500, 'Error al listar numeros: ' || SQLERRM);
    END LISTAR_NUMEROS;

    ----------------------------------------------------------------------------
    PROCEDURE ENVIAR(
        p_token          IN VARCHAR2,
        p_mensaje        IN VARCHAR2,
        p_imagen_url     IN VARCHAR2 DEFAULT NULL,
        p_numeros_manual IN VARCHAR2 DEFAULT NULL)
    IS
        l_usuario   VARCHAR2(256);
        l_job       VARCHAR2(128);
        l_env_id    NUMBER;
    BEGIN
        l_usuario := f_usuario(p_token);
        IF l_usuario IS NULL THEN
            p_error(401, 'Token invalido o expirado');
            RETURN;
        END IF;

        IF p_mensaje IS NULL AND p_imagen_url IS NULL THEN
            p_error(400, 'Debe enviar un mensaje o una imagen');
            RETURN;
        END IF;

        -- Persistir el envio. Si p_numeros_manual viene (pestana Manual), se guarda
        -- la lista y el proc envia SOLO a esos numeros (no toca numeros_whatsapp).
        -- Si es NULL (pestana De la base), el proc procesa los pendientes de la tabla.
        INSERT INTO WHATSAPP_ENVIOS (mensaje, imagen_url, numeros_manual, usuario, estado)
        VALUES (p_mensaje, p_imagen_url, p_numeros_manual, l_usuario, 'PENDIENTE')
        RETURNING id INTO l_env_id;

        l_job := 'WSP_ENVIO_' || l_env_id;

        DBMS_SCHEDULER.CREATE_JOB(
            job_name   => l_job,
            job_type   => 'PLSQL_BLOCK',
            job_action => 'BEGIN ENVIAR_MENSAJES_WHATSAPP_JOB(' || l_env_id || '); END;',
            start_date => SYSTIMESTAMP,
            enabled    => TRUE,
            auto_drop  => TRUE);

        COMMIT;

        APEX_JSON.OPEN_OBJECT;
        APEX_JSON.WRITE('success', TRUE);
        APEX_JSON.WRITE('message', 'Envio iniciado');
        APEX_JSON.WRITE('envio_id', l_env_id);
        APEX_JSON.WRITE('job', l_job);
        APEX_JSON.CLOSE_OBJECT;
    EXCEPTION WHEN OTHERS THEN
        ROLLBACK;
        p_error(500, 'Error al iniciar envio: ' || SQLERRM);
    END ENVIAR;

    ----------------------------------------------------------------------------
    PROCEDURE LOGS(
        p_token IN VARCHAR2,
        p_desde IN VARCHAR2 DEFAULT NULL)
    IS
        l_usuario VARCHAR2(256);
        l_desde   TIMESTAMP;
    BEGIN
        l_usuario := f_usuario(p_token);
        IF l_usuario IS NULL THEN
            p_error(401, 'Token invalido o expirado');
            RETURN;
        END IF;

        BEGIN
            l_desde := TO_TIMESTAMP_TZ(p_desde, 'YYYY-MM-DD"T"HH24:MI:SS.FF3TZH:TZM');
        EXCEPTION WHEN OTHERS THEN
            l_desde := TRUNC(SYSTIMESTAMP);  -- por defecto: desde hoy
        END;

        APEX_JSON.OPEN_OBJECT;
        APEX_JSON.WRITE('success', TRUE);
        APEX_JSON.OPEN_ARRAY('data');
        FOR r IN (
            SELECT numero_original, numero_limpio, estado, http_status,
                   detalle_error, fecha_registro
            FROM   LOG_WHATSAPP
            WHERE  fecha_registro >= l_desde
            ORDER  BY fecha_registro
        ) LOOP
            APEX_JSON.OPEN_OBJECT;
            APEX_JSON.WRITE('numero',   NVL(r.numero_limpio, r.numero_original));
            APEX_JSON.WRITE('estado',   r.estado);
            APEX_JSON.WRITE('http',     r.http_status);
            APEX_JSON.WRITE('detalle',  r.detalle_error);
            APEX_JSON.WRITE('fecha',    TO_CHAR(r.fecha_registro, 'YYYY-MM-DD"T"HH24:MI:SS'));
            APEX_JSON.CLOSE_OBJECT;
        END LOOP;
        APEX_JSON.CLOSE_ARRAY;
        APEX_JSON.CLOSE_OBJECT;
    EXCEPTION WHEN OTHERS THEN
        p_error(500, 'Error al leer logs: ' || SQLERRM);
    END LOGS;

    ----------------------------------------------------------------------------
    -- Sube la imagen al propio wasenderapi (POST /api/upload) y devuelve su URL
    -- publica (CDN de wasender, valida 24h). Asi wasender descarga la imagen de su
    -- propio storage al enviar: sin imgbb ni ORDS sirviendo el BLOB (que daba timeout).
    -- Recibe el base64 puro + mime del front; arma el data URL que espera /api/upload.
    PROCEDURE SUBIR_IMAGEN(
        p_token  IN VARCHAR2,
        p_base64 IN CLOB,
        p_mime   IN VARCHAR2 DEFAULT NULL,
        p_nombre IN VARCHAR2 DEFAULT NULL)
    IS
        l_usuario  VARCHAR2(256);
        l_b64      CLOB;
        l_mime     VARCHAR2(100);
        l_datauri  CLOB;
        l_body     CLOB;
        l_response CLOB;
        l_status   NUMBER;
        l_url      VARCHAR2(1000);
        l_comma    PLS_INTEGER;
    BEGIN
        l_usuario := f_usuario(p_token);
        IF l_usuario IS NULL THEN
            p_error(401, 'Token invalido o expirado');
            RETURN;
        END IF;

        IF p_base64 IS NULL OR DBMS_LOB.GETLENGTH(p_base64) = 0 THEN
            p_error(400, 'Imagen vacia');
            RETURN;
        END IF;

        l_b64  := p_base64;
        l_mime := NVL(p_mime, 'image/jpeg');

        -- Normaliza a data URL "data:<mime>;base64,<datos>" (lo que espera /api/upload).
        IF DBMS_LOB.SUBSTR(l_b64, 5, 1) = 'data:' THEN
            l_datauri := l_b64;  -- ya viene como data URL
        ELSE
            l_datauri := 'data:' || l_mime || ';base64,' || l_b64;
        END IF;

        -- Body JSON: {"base64":"<data uri>"}. El base64 no tiene comillas ni backslash,
        -- asi que concatenar directo es seguro.
        l_body := '{"base64":"' || l_datauri || '"}';

        APEX_WEB_SERVICE.SET_REQUEST_HEADERS(
            p_name_01  => 'Authorization', p_value_01 => 'Bearer ' || C_WASENDER_KEY,
            p_name_02  => 'Content-Type',  p_value_02 => 'application/json',
            p_reset    => TRUE);

        l_response := APEX_WEB_SERVICE.MAKE_REST_REQUEST(
            p_url         => 'https://wasenderapi.com/api/upload',
            p_http_method => 'POST',
            p_body        => l_body);

        l_status := APEX_WEB_SERVICE.G_STATUS_CODE;

        IF l_status NOT IN (200, 201) THEN
            p_error(502, 'wasender /upload devolvio HTTP ' || l_status || ': ' ||
                         DBMS_LOB.SUBSTR(l_response, 300, 1));
            RETURN;
        END IF;

        APEX_JSON.PARSE(l_response);
        l_url := APEX_JSON.GET_VARCHAR2('publicUrl');

        IF l_url IS NULL THEN
            p_error(502, 'wasender /upload no devolvio publicUrl');
            RETURN;
        END IF;

        APEX_JSON.OPEN_OBJECT;
        APEX_JSON.WRITE('success', TRUE);
        APEX_JSON.WRITE('url', l_url);
        APEX_JSON.CLOSE_OBJECT;
    EXCEPTION WHEN OTHERS THEN
        p_error(500, 'Error al subir imagen: ' || SQLERRM);
    END SUBIR_IMAGEN;

    ----------------------------------------------------------------------------
    PROCEDURE CARGAR_NUMEROS(
        p_token   IN VARCHAR2,
        p_numeros IN CLOB)
    IS
        l_usuario     VARCHAR2(256);
        l_numero      VARCHAR2(100);
        l_existe      NUMBER;
        l_ins         NUMBER := 0;
        l_omit        NUMBER := 0;
    BEGIN
        l_usuario := f_usuario(p_token);
        IF l_usuario IS NULL THEN
            p_error(401, 'Token invalido o expirado');
            RETURN;
        END IF;

        APEX_JSON.PARSE(p_numeros);
        FOR i IN 1 .. APEX_JSON.GET_COUNT('.') LOOP
            l_numero := TRIM(APEX_JSON.GET_VARCHAR2('[%d]', i));
            IF l_numero IS NOT NULL THEN
                SELECT COUNT(*) INTO l_existe
                FROM   numeros_whatsapp WHERE numero = l_numero;
                IF l_existe = 0 THEN
                    INSERT INTO numeros_whatsapp (numero, mensajeado)
                    VALUES (l_numero, 'N');
                    l_ins := l_ins + 1;
                ELSE
                    l_omit := l_omit + 1;
                END IF;
            END IF;
        END LOOP;
        COMMIT;

        APEX_JSON.OPEN_OBJECT;
        APEX_JSON.WRITE('success', TRUE);
        APEX_JSON.WRITE('insertados', l_ins);
        APEX_JSON.WRITE('omitidos', l_omit);
        APEX_JSON.CLOSE_OBJECT;
    EXCEPTION WHEN OTHERS THEN
        ROLLBACK;
        p_error(500, 'Error al cargar numeros: ' || SQLERRM);
    END CARGAR_NUMEROS;

    ----------------------------------------------------------------------------
    PROCEDURE BORRAR_NUMEROS(p_token IN VARCHAR2) IS
        l_usuario VARCHAR2(256);
        l_borrados NUMBER;
    BEGIN
        l_usuario := f_usuario(p_token);
        IF l_usuario IS NULL THEN
            p_error(401, 'Token invalido o expirado');
            RETURN;
        END IF;

        DELETE FROM numeros_whatsapp;
        l_borrados := SQL%ROWCOUNT;
        COMMIT;

        APEX_JSON.OPEN_OBJECT;
        APEX_JSON.WRITE('success', TRUE);
        APEX_JSON.WRITE('borrados', l_borrados);
        APEX_JSON.CLOSE_OBJECT;
    EXCEPTION WHEN OTHERS THEN
        ROLLBACK;
        p_error(500, 'Error al borrar numeros: ' || SQLERRM);
    END BORRAR_NUMEROS;

END PKG_WHATSAPP_LUBRIMEC;
/

--------------------------------------------------------------------------------
-- === 4) ENDPOINTS ORDS ======================================================
--
--   GET    /lubrimec/whatsapp/numeros            -> listar numeros pendientes
--   DELETE /lubrimec/whatsapp/numeros            -> borrar numeros
--   POST   /lubrimec/whatsapp/numeros/cargar     -> cargar numeros manuales
--   POST   /lubrimec/whatsapp/enviar             -> lanzar envio (job background)
--   GET    /lubrimec/whatsapp/logs?desde=:ts     -> progreso (LOG_WHATSAPP)
--   POST   /lubrimec/whatsapp/imagen             -> subir imagen (base64)
--   GET    /lubrimec/whatsapp/imagen/:id         -> servir imagen
--------------------------------------------------------------------------------

BEGIN
  BEGIN ORDS.DELETE_HANDLER('lubrimec', 'whatsapp/numeros',        'GET');    EXCEPTION WHEN OTHERS THEN NULL; END;
  BEGIN ORDS.DELETE_HANDLER('lubrimec', 'whatsapp/numeros',        'DELETE'); EXCEPTION WHEN OTHERS THEN NULL; END;
  BEGIN ORDS.DELETE_HANDLER('lubrimec', 'whatsapp/numeros/cargar', 'POST');   EXCEPTION WHEN OTHERS THEN NULL; END;
  BEGIN ORDS.DELETE_HANDLER('lubrimec', 'whatsapp/enviar',     'POST'); EXCEPTION WHEN OTHERS THEN NULL; END;
  BEGIN ORDS.DELETE_HANDLER('lubrimec', 'whatsapp/logs',       'GET');  EXCEPTION WHEN OTHERS THEN NULL; END;
  BEGIN ORDS.DELETE_HANDLER('lubrimec', 'whatsapp/imagen',     'POST'); EXCEPTION WHEN OTHERS THEN NULL; END;

  ----------------------------------------------------------------------------
  -- GET /whatsapp/numeros
  ----------------------------------------------------------------------------
  BEGIN
    ORDS.DEFINE_TEMPLATE(p_module_name => 'lubrimec', p_pattern => 'whatsapp/numeros',
                         p_priority => 0, p_etag_type => 'HASH', p_comments => NULL);
  EXCEPTION WHEN OTHERS THEN NULL; END;

  ORDS.DEFINE_HANDLER(
      p_module_name => 'lubrimec', p_pattern => 'whatsapp/numeros', p_method => 'GET',
      p_source_type => 'plsql/block',
      p_source      => q'~
DECLARE
    l_token VARCHAR2(256);
    l_pos   PLS_INTEGER;
BEGIN
    OWA_UTIL.MIME_HEADER('application/json', FALSE);
    HTP.P('Access-Control-Allow-Origin: *');
    HTP.P('Access-Control-Allow-Headers: Authorization, Content-Type');
    OWA_UTIL.HTTP_HEADER_CLOSE;
    l_token := :authorization;
    IF l_token IS NOT NULL THEN
        l_pos := INSTR(UPPER(l_token), 'BEARER ');
        IF l_pos > 0 THEN l_token := TRIM(SUBSTR(l_token, l_pos + 7)); END IF;
    END IF;
    PKG_WHATSAPP_LUBRIMEC.LISTAR_NUMEROS(p_token => l_token, p_solo_pendientes => 'S');
END;
~');

  ORDS.DEFINE_PARAMETER(
      p_module_name => 'lubrimec', p_pattern => 'whatsapp/numeros', p_method => 'GET',
      p_name => 'Authorization', p_bind_variable_name => 'authorization',
      p_source_type => 'HEADER', p_param_type => 'STRING', p_access_method => 'IN');

  -- DELETE /whatsapp/numeros  -> borra todos
  ORDS.DEFINE_HANDLER(
      p_module_name => 'lubrimec', p_pattern => 'whatsapp/numeros', p_method => 'DELETE',
      p_source_type => 'plsql/block',
      p_source      => q'~
DECLARE
    l_token VARCHAR2(256);
    l_pos   PLS_INTEGER;
BEGIN
    OWA_UTIL.MIME_HEADER('application/json', FALSE);
    HTP.P('Access-Control-Allow-Origin: *');
    HTP.P('Access-Control-Allow-Headers: Authorization, Content-Type');
    OWA_UTIL.HTTP_HEADER_CLOSE;
    l_token := :authorization;
    IF l_token IS NOT NULL THEN
        l_pos := INSTR(UPPER(l_token), 'BEARER ');
        IF l_pos > 0 THEN l_token := TRIM(SUBSTR(l_token, l_pos + 7)); END IF;
    END IF;
    PKG_WHATSAPP_LUBRIMEC.BORRAR_NUMEROS(p_token => l_token);
END;
~');

  ORDS.DEFINE_PARAMETER(
      p_module_name => 'lubrimec', p_pattern => 'whatsapp/numeros', p_method => 'DELETE',
      p_name => 'Authorization', p_bind_variable_name => 'authorization',
      p_source_type => 'HEADER', p_param_type => 'STRING', p_access_method => 'IN');

  ----------------------------------------------------------------------------
  -- POST /whatsapp/numeros/cargar  -> carga masiva
  ----------------------------------------------------------------------------
  BEGIN
    ORDS.DEFINE_TEMPLATE(p_module_name => 'lubrimec', p_pattern => 'whatsapp/numeros/cargar',
                         p_priority => 0, p_etag_type => 'HASH', p_comments => NULL);
  EXCEPTION WHEN OTHERS THEN NULL; END;

  ORDS.DEFINE_HANDLER(
      p_module_name => 'lubrimec', p_pattern => 'whatsapp/numeros/cargar', p_method => 'POST',
      p_source_type => 'plsql/block',
      p_source      => q'~
DECLARE
    l_token VARCHAR2(256);
    l_pos   PLS_INTEGER;
BEGIN
    OWA_UTIL.MIME_HEADER('application/json', FALSE);
    HTP.P('Access-Control-Allow-Origin: *');
    HTP.P('Access-Control-Allow-Headers: Authorization, Content-Type');
    OWA_UTIL.HTTP_HEADER_CLOSE;
    l_token := :authorization;
    IF l_token IS NOT NULL THEN
        l_pos := INSTR(UPPER(l_token), 'BEARER ');
        IF l_pos > 0 THEN l_token := TRIM(SUBSTR(l_token, l_pos + 7)); END IF;
    END IF;
    PKG_WHATSAPP_LUBRIMEC.CARGAR_NUMEROS(p_token => l_token, p_numeros => :numeros);
END;
~');

  ORDS.DEFINE_PARAMETER(
      p_module_name => 'lubrimec', p_pattern => 'whatsapp/numeros/cargar', p_method => 'POST',
      p_name => 'Authorization', p_bind_variable_name => 'authorization',
      p_source_type => 'HEADER', p_param_type => 'STRING', p_access_method => 'IN');

  ----------------------------------------------------------------------------
  -- POST /whatsapp/enviar
  ----------------------------------------------------------------------------
  BEGIN
    ORDS.DEFINE_TEMPLATE(p_module_name => 'lubrimec', p_pattern => 'whatsapp/enviar',
                         p_priority => 0, p_etag_type => 'HASH', p_comments => NULL);
  EXCEPTION WHEN OTHERS THEN NULL; END;

  ORDS.DEFINE_HANDLER(
      p_module_name => 'lubrimec', p_pattern => 'whatsapp/enviar', p_method => 'POST',
      p_source_type => 'plsql/block',
      p_source      => q'~
DECLARE
    l_token VARCHAR2(256);
    l_pos   PLS_INTEGER;
BEGIN
    OWA_UTIL.MIME_HEADER('application/json', FALSE);
    HTP.P('Access-Control-Allow-Origin: *');
    HTP.P('Access-Control-Allow-Headers: Authorization, Content-Type');
    OWA_UTIL.HTTP_HEADER_CLOSE;
    l_token := :authorization;
    IF l_token IS NOT NULL THEN
        l_pos := INSTR(UPPER(l_token), 'BEARER ');
        IF l_pos > 0 THEN l_token := TRIM(SUBSTR(l_token, l_pos + 7)); END IF;
    END IF;
    PKG_WHATSAPP_LUBRIMEC.ENVIAR(
        p_token          => l_token,
        p_mensaje        => :mensaje,
        p_imagen_url     => :imagen_url,
        p_numeros_manual => :numeros_manual);
END;
~');

  ORDS.DEFINE_PARAMETER(
      p_module_name => 'lubrimec', p_pattern => 'whatsapp/enviar', p_method => 'POST',
      p_name => 'Authorization', p_bind_variable_name => 'authorization',
      p_source_type => 'HEADER', p_param_type => 'STRING', p_access_method => 'IN');

  ----------------------------------------------------------------------------
  -- GET /whatsapp/logs
  ----------------------------------------------------------------------------
  BEGIN
    ORDS.DEFINE_TEMPLATE(p_module_name => 'lubrimec', p_pattern => 'whatsapp/logs',
                         p_priority => 0, p_etag_type => 'HASH', p_comments => NULL);
  EXCEPTION WHEN OTHERS THEN NULL; END;

  ORDS.DEFINE_HANDLER(
      p_module_name => 'lubrimec', p_pattern => 'whatsapp/logs', p_method => 'GET',
      p_source_type => 'plsql/block',
      p_source      => q'~
DECLARE
    l_token VARCHAR2(256);
    l_pos   PLS_INTEGER;
    l_qs    VARCHAR2(4000);
    l_desde VARCHAR2(60);
    l_p     PLS_INTEGER;
BEGIN
    OWA_UTIL.MIME_HEADER('application/json', FALSE);
    HTP.P('Access-Control-Allow-Origin: *');
    HTP.P('Access-Control-Allow-Headers: Authorization, Content-Type');
    OWA_UTIL.HTTP_HEADER_CLOSE;
    l_token := :authorization;
    IF l_token IS NOT NULL THEN
        l_pos := INSTR(UPPER(l_token), 'BEARER ');
        IF l_pos > 0 THEN l_token := TRIM(SUBSTR(l_token, l_pos + 7)); END IF;
    END IF;

    -- Query params no se auto-bindean fiable: leer 'desde' del query string crudo.
    l_qs := OWA_UTIL.GET_CGI_ENV('QUERY_STRING');
    l_p  := INSTR(l_qs, 'desde=');
    IF l_p > 0 THEN
        l_desde := SUBSTR(l_qs, l_p + 6);
        l_p := INSTR(l_desde, '&');
        IF l_p > 0 THEN l_desde := SUBSTR(l_desde, 1, l_p - 1); END IF;
        l_desde := UTL_URL.UNESCAPE(l_desde);
    END IF;

    PKG_WHATSAPP_LUBRIMEC.LOGS(p_token => l_token, p_desde => l_desde);
END;
~');

  ORDS.DEFINE_PARAMETER(
      p_module_name => 'lubrimec', p_pattern => 'whatsapp/logs', p_method => 'GET',
      p_name => 'Authorization', p_bind_variable_name => 'authorization',
      p_source_type => 'HEADER', p_param_type => 'STRING', p_access_method => 'IN');

  ----------------------------------------------------------------------------
  -- POST /whatsapp/imagen  (sube base64, devuelve {id, url})
  ----------------------------------------------------------------------------
  BEGIN
    ORDS.DEFINE_TEMPLATE(p_module_name => 'lubrimec', p_pattern => 'whatsapp/imagen',
                         p_priority => 0, p_etag_type => 'HASH', p_comments => NULL);
  EXCEPTION WHEN OTHERS THEN NULL; END;

  ORDS.DEFINE_HANDLER(
      p_module_name => 'lubrimec', p_pattern => 'whatsapp/imagen', p_method => 'POST',
      p_source_type => 'plsql/block',
      p_source      => q'~
DECLARE
    l_token VARCHAR2(256);
    l_pos   PLS_INTEGER;
BEGIN
    OWA_UTIL.MIME_HEADER('application/json', FALSE);
    HTP.P('Access-Control-Allow-Origin: *');
    HTP.P('Access-Control-Allow-Headers: Authorization, Content-Type');
    OWA_UTIL.HTTP_HEADER_CLOSE;
    l_token := :authorization;
    IF l_token IS NOT NULL THEN
        l_pos := INSTR(UPPER(l_token), 'BEARER ');
        IF l_pos > 0 THEN l_token := TRIM(SUBSTR(l_token, l_pos + 7)); END IF;
    END IF;
    PKG_WHATSAPP_LUBRIMEC.SUBIR_IMAGEN(
        p_token  => l_token,
        p_base64 => :base64,
        p_mime   => :mime,
        p_nombre => :nombre);
END;
~');

  ORDS.DEFINE_PARAMETER(
      p_module_name => 'lubrimec', p_pattern => 'whatsapp/imagen', p_method => 'POST',
      p_name => 'Authorization', p_bind_variable_name => 'authorization',
      p_source_type => 'HEADER', p_param_type => 'STRING', p_access_method => 'IN');

  COMMIT;
EXCEPTION
  WHEN OTHERS THEN ROLLBACK; RAISE;
END;
/
